

? fresh a"o1", b"o1", c"o1", d"o1", e"o1", a"o2", b"o2", c"o2", d"o2", e"o2", a"o3", b"o3", c"o3", d"o3", e"o3", a"o4", b"o4", c"o4", d"o4", e"o4", a"o5", b"o5", c"o5", d"o5", e"o5" in
    (a"o1" == Yellow & 
    (a"o2" == Blue | 
    a"o2" == Red | 
    a"o2" == Ivory | 
    a"o2" == Green) | 
    a"o1" == Blue & 
    (a"o2" == Yellow | 
    a"o2" == Red | 
    a"o2" == Ivory | 
    a"o2" == Green) | 
    a"o1" == Red & 
    (a"o2" == Yellow | 
    a"o2" == Blue | 
    a"o2" == Ivory | 
    a"o2" == Green) | 
    a"o1" == Ivory & 
    (a"o2" == Yellow | 
    a"o2" == Blue | 
    a"o2" == Red | 
    a"o2" == Green) | 
    a"o1" == Green & 
    (a"o2" == Yellow | 
    a"o2" == Blue | 
    a"o2" == Red | 
    a"o2" == Ivory)) & 
    (b"o1" == Norwegean & 
    (b"o2" == Ukranian | 
    b"o2" == Englishman | 
    b"o2" == Spaniard | 
    b"o2" == Japanese) | 
    b"o1" == Ukranian & 
    (b"o2" == Norwegean | 
    b"o2" == Englishman | 
    b"o2" == Spaniard | 
    b"o2" == Japanese) | 
    b"o1" == Englishman & 
    (b"o2" == Norwegean | 
    b"o2" == Ukranian | 
    b"o2" == Spaniard | 
    b"o2" == Japanese) | 
    b"o1" == Spaniard & 
    (b"o2" == Norwegean | 
    b"o2" == Ukranian | 
    b"o2" == Englishman | 
    b"o2" == Japanese) | 
    b"o1" == Japanese & 
    (b"o2" == Norwegean | 
    b"o2" == Ukranian | 
    b"o2" == Englishman | 
    b"o2" == Spaniard)) & 
    (c"o1" == Water & 
    (c"o2" == Tea | 
    c"o2" == Milk | 
    c"o2" == Juice | 
    c"o2" == Coffee) | 
    c"o1" == Tea & 
    (c"o2" == Water | 
    c"o2" == Milk | 
    c"o2" == Juice | 
    c"o2" == Coffee) | 
    c"o1" == Milk & 
    (c"o2" == Water | 
    c"o2" == Tea | 
    c"o2" == Juice | 
    c"o2" == Coffee) | 
    c"o1" == Juice & 
    (c"o2" == Water | 
    c"o2" == Tea | 
    c"o2" == Milk | 
    c"o2" == Coffee) | 
    c"o1" == Coffee & 
    (c"o2" == Water | 
    c"o2" == Tea | 
    c"o2" == Milk | 
    c"o2" == Juice)) & 
    (d"o1" == Kools & 
    (d"o2" == Chesterfield | 
    d"o2" == OldGold | 
    d"o2" == LuckyStrike | 
    d"o2" == Parliament) | 
    d"o1" == Chesterfield & 
    (d"o2" == Kools | 
    d"o2" == OldGold | 
    d"o2" == LuckyStrike | 
    d"o2" == Parliament) | 
    d"o1" == OldGold & 
    (d"o2" == Kools | 
    d"o2" == Chesterfield | 
    d"o2" == LuckyStrike | 
    d"o2" == Parliament) | 
    d"o1" == LuckyStrike & 
    (d"o2" == Kools | 
    d"o2" == Chesterfield | 
    d"o2" == OldGold | 
    d"o2" == Parliament) | 
    d"o1" == Parliament & 
    (d"o2" == Kools | 
    d"o2" == Chesterfield | 
    d"o2" == OldGold | 
    d"o2" == LuckyStrike)) & 
    (e"o1" == Fox & 
    (e"o2" == Horse | 
    e"o2" == Snails | 
    e"o2" == Dog | 
    e"o2" == Zebra) | 
    e"o1" == Horse & 
    (e"o2" == Fox | 
    e"o2" == Snails | 
    e"o2" == Dog | 
    e"o2" == Zebra) | 
    e"o1" == Snails & 
    (e"o2" == Fox | 
    e"o2" == Horse | 
    e"o2" == Dog | 
    e"o2" == Zebra) | 
    e"o1" == Dog & 
    (e"o2" == Fox | 
    e"o2" == Horse | 
    e"o2" == Snails | 
    e"o2" == Zebra) | 
    e"o1" == Zebra & 
    (e"o2" == Fox | 
    e"o2" == Horse | 
    e"o2" == Snails | 
    e"o2" == Dog)) & 
    (a"o1" == Yellow & 
    (a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o1" == Blue & 
    (a"o3" == Yellow | 
    a"o3" == Red | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o1" == Red & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o1" == Ivory & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Green) | 
    a"o1" == Green & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Ivory)) & 
    (b"o1" == Norwegean & 
    (b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o1" == Ukranian & 
    (b"o3" == Norwegean | 
    b"o3" == Englishman | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o1" == Englishman & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o1" == Spaniard & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Japanese) | 
    b"o1" == Japanese & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Spaniard)) & 
    (c"o1" == Water & 
    (c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o1" == Tea & 
    (c"o3" == Water | 
    c"o3" == Milk | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o1" == Milk & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o1" == Juice & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Coffee) | 
    c"o1" == Coffee & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Juice)) & 
    (d"o1" == Kools & 
    (d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o1" == Chesterfield & 
    (d"o3" == Kools | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o1" == OldGold & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o1" == LuckyStrike & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == Parliament) | 
    d"o1" == Parliament & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike)) & 
    (e"o1" == Fox & 
    (e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o1" == Horse & 
    (e"o3" == Fox | 
    e"o3" == Snails | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o1" == Snails & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o1" == Dog & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Zebra) | 
    e"o1" == Zebra & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Dog)) & 
    (a"o1" == Yellow & 
    (a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o1" == Blue & 
    (a"o4" == Yellow | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o1" == Red & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o1" == Ivory & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Green) | 
    a"o1" == Green & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory)) & 
    (b"o1" == Norwegean & 
    (b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o1" == Ukranian & 
    (b"o4" == Norwegean | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o1" == Englishman & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o1" == Spaniard & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Japanese) | 
    b"o1" == Japanese & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard)) & 
    (c"o1" == Water & 
    (c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o1" == Tea & 
    (c"o4" == Water | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o1" == Milk & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o1" == Juice & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Coffee) | 
    c"o1" == Coffee & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice)) & 
    (d"o1" == Kools & 
    (d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o1" == Chesterfield & 
    (d"o4" == Kools | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o1" == OldGold & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o1" == LuckyStrike & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == Parliament) | 
    d"o1" == Parliament & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike)) & 
    (e"o1" == Fox & 
    (e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o1" == Horse & 
    (e"o4" == Fox | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o1" == Snails & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o1" == Dog & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Zebra) | 
    e"o1" == Zebra & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog)) & 
    (a"o1" == Yellow & 
    (a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o1" == Blue & 
    (a"o5" == Yellow | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o1" == Red & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o1" == Ivory & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Green) | 
    a"o1" == Green & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory)) & 
    (b"o1" == Norwegean & 
    (b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o1" == Ukranian & 
    (b"o5" == Norwegean | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o1" == Englishman & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o1" == Spaniard & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Japanese) | 
    b"o1" == Japanese & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard)) & 
    (c"o1" == Water & 
    (c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o1" == Tea & 
    (c"o5" == Water | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o1" == Milk & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o1" == Juice & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Coffee) | 
    c"o1" == Coffee & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice)) & 
    (d"o1" == Kools & 
    (d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o1" == Chesterfield & 
    (d"o5" == Kools | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o1" == OldGold & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o1" == LuckyStrike & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == Parliament) | 
    d"o1" == Parliament & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike)) & 
    (e"o1" == Fox & 
    (e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o1" == Horse & 
    (e"o5" == Fox | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o1" == Snails & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o1" == Dog & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Zebra) | 
    e"o1" == Zebra & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog)) & 
    (a"o2" == Yellow & 
    (a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o2" == Blue & 
    (a"o3" == Yellow | 
    a"o3" == Red | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o2" == Red & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Ivory | 
    a"o3" == Green) | 
    a"o2" == Ivory & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Green) | 
    a"o2" == Green & 
    (a"o3" == Yellow | 
    a"o3" == Blue | 
    a"o3" == Red | 
    a"o3" == Ivory)) & 
    (b"o2" == Norwegean & 
    (b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o2" == Ukranian & 
    (b"o3" == Norwegean | 
    b"o3" == Englishman | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o2" == Englishman & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Spaniard | 
    b"o3" == Japanese) | 
    b"o2" == Spaniard & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Japanese) | 
    b"o2" == Japanese & 
    (b"o3" == Norwegean | 
    b"o3" == Ukranian | 
    b"o3" == Englishman | 
    b"o3" == Spaniard)) & 
    (c"o2" == Water & 
    (c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o2" == Tea & 
    (c"o3" == Water | 
    c"o3" == Milk | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o2" == Milk & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Juice | 
    c"o3" == Coffee) | 
    c"o2" == Juice & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Coffee) | 
    c"o2" == Coffee & 
    (c"o3" == Water | 
    c"o3" == Tea | 
    c"o3" == Milk | 
    c"o3" == Juice)) & 
    (d"o2" == Kools & 
    (d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o2" == Chesterfield & 
    (d"o3" == Kools | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o2" == OldGold & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == LuckyStrike | 
    d"o3" == Parliament) | 
    d"o2" == LuckyStrike & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == Parliament) | 
    d"o2" == Parliament & 
    (d"o3" == Kools | 
    d"o3" == Chesterfield | 
    d"o3" == OldGold | 
    d"o3" == LuckyStrike)) & 
    (e"o2" == Fox & 
    (e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o2" == Horse & 
    (e"o3" == Fox | 
    e"o3" == Snails | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o2" == Snails & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Dog | 
    e"o3" == Zebra) | 
    e"o2" == Dog & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Zebra) | 
    e"o2" == Zebra & 
    (e"o3" == Fox | 
    e"o3" == Horse | 
    e"o3" == Snails | 
    e"o3" == Dog)) & 
    (a"o2" == Yellow & 
    (a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o2" == Blue & 
    (a"o4" == Yellow | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o2" == Red & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o2" == Ivory & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Green) | 
    a"o2" == Green & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory)) & 
    (b"o2" == Norwegean & 
    (b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o2" == Ukranian & 
    (b"o4" == Norwegean | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o2" == Englishman & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o2" == Spaniard & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Japanese) | 
    b"o2" == Japanese & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard)) & 
    (c"o2" == Water & 
    (c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o2" == Tea & 
    (c"o4" == Water | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o2" == Milk & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o2" == Juice & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Coffee) | 
    c"o2" == Coffee & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice)) & 
    (d"o2" == Kools & 
    (d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o2" == Chesterfield & 
    (d"o4" == Kools | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o2" == OldGold & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o2" == LuckyStrike & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == Parliament) | 
    d"o2" == Parliament & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike)) & 
    (e"o2" == Fox & 
    (e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o2" == Horse & 
    (e"o4" == Fox | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o2" == Snails & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o2" == Dog & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Zebra) | 
    e"o2" == Zebra & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog)) & 
    (a"o2" == Yellow & 
    (a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o2" == Blue & 
    (a"o5" == Yellow | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o2" == Red & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o2" == Ivory & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Green) | 
    a"o2" == Green & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory)) & 
    (b"o2" == Norwegean & 
    (b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o2" == Ukranian & 
    (b"o5" == Norwegean | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o2" == Englishman & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o2" == Spaniard & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Japanese) | 
    b"o2" == Japanese & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard)) & 
    (c"o2" == Water & 
    (c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o2" == Tea & 
    (c"o5" == Water | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o2" == Milk & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o2" == Juice & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Coffee) | 
    c"o2" == Coffee & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice)) & 
    (d"o2" == Kools & 
    (d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o2" == Chesterfield & 
    (d"o5" == Kools | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o2" == OldGold & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o2" == LuckyStrike & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == Parliament) | 
    d"o2" == Parliament & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike)) & 
    (e"o2" == Fox & 
    (e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o2" == Horse & 
    (e"o5" == Fox | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o2" == Snails & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o2" == Dog & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Zebra) | 
    e"o2" == Zebra & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog)) & 
    (a"o3" == Yellow & 
    (a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o3" == Blue & 
    (a"o4" == Yellow | 
    a"o4" == Red | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o3" == Red & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Ivory | 
    a"o4" == Green) | 
    a"o3" == Ivory & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Green) | 
    a"o3" == Green & 
    (a"o4" == Yellow | 
    a"o4" == Blue | 
    a"o4" == Red | 
    a"o4" == Ivory)) & 
    (b"o3" == Norwegean & 
    (b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o3" == Ukranian & 
    (b"o4" == Norwegean | 
    b"o4" == Englishman | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o3" == Englishman & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Spaniard | 
    b"o4" == Japanese) | 
    b"o3" == Spaniard & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Japanese) | 
    b"o3" == Japanese & 
    (b"o4" == Norwegean | 
    b"o4" == Ukranian | 
    b"o4" == Englishman | 
    b"o4" == Spaniard)) & 
    (c"o3" == Water & 
    (c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o3" == Tea & 
    (c"o4" == Water | 
    c"o4" == Milk | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o3" == Milk & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Juice | 
    c"o4" == Coffee) | 
    c"o3" == Juice & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Coffee) | 
    c"o3" == Coffee & 
    (c"o4" == Water | 
    c"o4" == Tea | 
    c"o4" == Milk | 
    c"o4" == Juice)) & 
    (d"o3" == Kools & 
    (d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o3" == Chesterfield & 
    (d"o4" == Kools | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o3" == OldGold & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == LuckyStrike | 
    d"o4" == Parliament) | 
    d"o3" == LuckyStrike & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == Parliament) | 
    d"o3" == Parliament & 
    (d"o4" == Kools | 
    d"o4" == Chesterfield | 
    d"o4" == OldGold | 
    d"o4" == LuckyStrike)) & 
    (e"o3" == Fox & 
    (e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o3" == Horse & 
    (e"o4" == Fox | 
    e"o4" == Snails | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o3" == Snails & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Dog | 
    e"o4" == Zebra) | 
    e"o3" == Dog & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Zebra) | 
    e"o3" == Zebra & 
    (e"o4" == Fox | 
    e"o4" == Horse | 
    e"o4" == Snails | 
    e"o4" == Dog)) & 
    (a"o3" == Yellow & 
    (a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o3" == Blue & 
    (a"o5" == Yellow | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o3" == Red & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o3" == Ivory & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Green) | 
    a"o3" == Green & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory)) & 
    (b"o3" == Norwegean & 
    (b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o3" == Ukranian & 
    (b"o5" == Norwegean | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o3" == Englishman & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o3" == Spaniard & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Japanese) | 
    b"o3" == Japanese & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard)) & 
    (c"o3" == Water & 
    (c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o3" == Tea & 
    (c"o5" == Water | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o3" == Milk & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o3" == Juice & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Coffee) | 
    c"o3" == Coffee & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice)) & 
    (d"o3" == Kools & 
    (d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o3" == Chesterfield & 
    (d"o5" == Kools | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o3" == OldGold & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o3" == LuckyStrike & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == Parliament) | 
    d"o3" == Parliament & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike)) & 
    (e"o3" == Fox & 
    (e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o3" == Horse & 
    (e"o5" == Fox | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o3" == Snails & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o3" == Dog & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Zebra) | 
    e"o3" == Zebra & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog)) & 
    (a"o4" == Yellow & 
    (a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o4" == Blue & 
    (a"o5" == Yellow | 
    a"o5" == Red | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o4" == Red & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Ivory | 
    a"o5" == Green) | 
    a"o4" == Ivory & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Green) | 
    a"o4" == Green & 
    (a"o5" == Yellow | 
    a"o5" == Blue | 
    a"o5" == Red | 
    a"o5" == Ivory)) & 
    (b"o4" == Norwegean & 
    (b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o4" == Ukranian & 
    (b"o5" == Norwegean | 
    b"o5" == Englishman | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o4" == Englishman & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Spaniard | 
    b"o5" == Japanese) | 
    b"o4" == Spaniard & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Japanese) | 
    b"o4" == Japanese & 
    (b"o5" == Norwegean | 
    b"o5" == Ukranian | 
    b"o5" == Englishman | 
    b"o5" == Spaniard)) & 
    (c"o4" == Water & 
    (c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o4" == Tea & 
    (c"o5" == Water | 
    c"o5" == Milk | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o4" == Milk & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Juice | 
    c"o5" == Coffee) | 
    c"o4" == Juice & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Coffee) | 
    c"o4" == Coffee & 
    (c"o5" == Water | 
    c"o5" == Tea | 
    c"o5" == Milk | 
    c"o5" == Juice)) & 
    (d"o4" == Kools & 
    (d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o4" == Chesterfield & 
    (d"o5" == Kools | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o4" == OldGold & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == LuckyStrike | 
    d"o5" == Parliament) | 
    d"o4" == LuckyStrike & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == Parliament) | 
    d"o4" == Parliament & 
    (d"o5" == Kools | 
    d"o5" == Chesterfield | 
    d"o5" == OldGold | 
    d"o5" == LuckyStrike)) & 
    (e"o4" == Fox & 
    (e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o4" == Horse & 
    (e"o5" == Fox | 
    e"o5" == Snails | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o4" == Snails & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Dog | 
    e"o5" == Zebra) | 
    e"o4" == Dog & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Zebra) | 
    e"o4" == Zebra & 
    (e"o5" == Fox | 
    e"o5" == Horse | 
    e"o5" == Snails | 
    e"o5" == Dog)) & 
    (b"o1" == Englishman & 
    a"o1" == Red | 
    b"o2" == Englishman & 
    a"o2" == Red | 
    b"o3" == Englishman & 
    a"o3" == Red | 
    b"o4" == Englishman & 
    a"o4" == Red | 
    b"o5" == Englishman & 
    a"o5" == Red) & 
    (b"o1" == Spaniard & 
    e"o1" == Dog | 
    b"o2" == Spaniard & 
    e"o2" == Dog | 
    b"o3" == Spaniard & 
    e"o3" == Dog | 
    b"o4" == Spaniard & 
    e"o4" == Dog | 
    b"o5" == Spaniard & 
    e"o5" == Dog) & 
    (a"o1" == Green & 
    c"o1" == Coffee | 
    a"o2" == Green & 
    c"o2" == Coffee | 
    a"o3" == Green & 
    c"o3" == Coffee | 
    a"o4" == Green & 
    c"o4" == Coffee | 
    a"o5" == Green & 
    c"o5" == Coffee) & 
    (b"o1" == Ukranian & 
    c"o1" == Tea | 
    b"o2" == Ukranian & 
    c"o2" == Tea | 
    b"o3" == Ukranian & 
    c"o3" == Tea | 
    b"o4" == Ukranian & 
    c"o4" == Tea | 
    b"o5" == Ukranian & 
    c"o5" == Tea) & 
    (a"o1" == Ivory & 
    a"o2" == Green | 
    a"o2" == Ivory & 
    a"o3" == Green | 
    a"o3" == Ivory & 
    a"o4" == Green | 
    a"o4" == Ivory & 
    a"o5" == Green) & 
    (d"o1" == OldGold & 
    e"o1" == Snails | 
    d"o2" == OldGold & 
    e"o2" == Snails | 
    d"o3" == OldGold & 
    e"o3" == Snails | 
    d"o4" == OldGold & 
    e"o4" == Snails | 
    d"o5" == OldGold & 
    e"o5" == Snails) & 
    (a"o1" == Yellow & 
    d"o1" == Kools | 
    a"o2" == Yellow & 
    d"o2" == Kools | 
    a"o3" == Yellow & 
    d"o3" == Kools | 
    a"o4" == Yellow & 
    d"o4" == Kools | 
    a"o5" == Yellow & 
    d"o5" == Kools) & 
    c"o3" == Milk & 
    b"o1" == Norwegean & 
    (d"o1" == Chesterfield & 
    e"o2" == Fox | 
    d"o2" == Chesterfield & 
    e"o1" == Fox | 
    d"o2" == Chesterfield & 
    e"o3" == Fox | 
    d"o3" == Chesterfield & 
    e"o2" == Fox | 
    d"o3" == Chesterfield & 
    e"o4" == Fox | 
    d"o4" == Chesterfield & 
    e"o3" == Fox | 
    d"o4" == Chesterfield & 
    e"o5" == Fox | 
    d"o5" == Chesterfield & 
    e"o4" == Fox) & 
    (e"o1" == Horse & 
    d"o2" == Kools | 
    e"o2" == Horse & 
    d"o1" == Kools | 
    e"o2" == Horse & 
    d"o3" == Kools | 
    e"o3" == Horse & 
    d"o2" == Kools | 
    e"o3" == Horse & 
    d"o4" == Kools | 
    e"o4" == Horse & 
    d"o3" == Kools | 
    e"o4" == Horse & 
    d"o5" == Kools | 
    e"o5" == Horse & 
    d"o4" == Kools) & 
    (d"o1" == LuckyStrike & 
    c"o1" == Juice | 
    d"o2" == LuckyStrike & 
    c"o2" == Juice | 
    d"o3" == LuckyStrike & 
    c"o3" == Juice | 
    d"o4" == LuckyStrike & 
    c"o4" == Juice | 
    d"o5" == LuckyStrike & 
    c"o5" == Juice) & 
    (b"o1" == Japanese & 
    d"o1" == Parliament | 
    b"o2" == Japanese & 
    d"o2" == Parliament | 
    b"o3" == Japanese & 
    d"o3" == Parliament | 
    b"o4" == Japanese & 
    d"o4" == Parliament | 
    b"o5" == Japanese & 
    d"o5" == Parliament) & 
    (b"o1" == Norwegean & 
    a"o2" == Blue | 
    b"o2" == Norwegean & 
    a"o1" == Blue | 
    b"o2" == Norwegean & 
    a"o3" == Blue | 
    b"o3" == Norwegean & 
    a"o2" == Blue | 
    b"o3" == Norwegean & 
    a"o4" == Blue | 
    b"o4" == Norwegean & 
    a"o3" == Blue | 
    b"o4" == Norwegean & 
    a"o5" == Blue | 
    b"o5" == Norwegean & 
    a"o4" == Blue)