
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 80 ms */
/* Unfolding time: 80 ms */
/* Post-Processing time: 80 ms */

/* Specialised Predicates:
maxLengtho__1(A,B,C) :- maxLengtho(A,B,C).
maxo1_conj__2(A,B,C) :- maxo1(A,o,B), lengtho(A,C).
maxo1_conj__3(A,B,C,D) :- maxo1(A,s(B),C), lengtho(A,D).
leo_conj__4(A,B,C,D,E) :- leo(A,s(B),true), maxo1(C,s(B),D), lengtho(C,E).
gto__5(A,B) :- gto(s(A),B,true).
leo__6(A,B) :- leo(A,B,true).
*/

maxLengtho(A,B,C) :-
  maxLengtho__1(A,B,C).
maxLengtho__1(nil,o,o).
maxLengtho__1(cons(o,A),B,s(C)) :-
  maxo1_conj__2(A,B,C).
maxLengtho__1(cons(s(A),B),C,s(D)) :-
  maxo1_conj__3(B,A,C,D).
maxo1_conj__2(nil,o,o).
maxo1_conj__2(cons(o,A),B,s(C)) :-
  maxo1_conj__2(A,B,C).
maxo1_conj__2(cons(s(A),B),C,s(D)) :-
  maxo1_conj__3(B,A,C,D).
maxo1_conj__3(nil,A,s(A),o).
maxo1_conj__3(cons(A,B),C,D,s(E)) :-
  leo_conj__4(A,C,B,D,E).
maxo1_conj__3(cons(s(s(A)),B),C,D,s(E)) :-
  gto__5(A,C),
  maxo1_conj__3(B,s(A),D,E).
leo_conj__4(o,A,B,C,D) :-
  maxo1_conj__3(B,A,C,D).
leo_conj__4(s(A),B,C,D,E) :-
  leo__6(A,B),
  maxo1_conj__3(C,B,D,E).
gto__5(A,o).
gto__5(s(A),s(B)) :-
  gto__5(A,B).
leo__6(o,A).
leo__6(s(A),s(B)) :-
  leo__6(A,B).