name:                uKanren-transformation
version:             0.1.0.0
github:              "kajigor/uKanren-transformation"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2019 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/uKanren-transformation#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- temporary
- text
- fgl
- graphviz
- transformers
- mtl
- extra
- directory
- timeit
- tasty-discover
- pretty-show
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- tasty-bench
- parsec
- filepath
- megaparsec
- parser-combinators
- optparse-applicative
- prettyprinter
- template-haskell >= 2.19.0.0
- split
- groups >= 0.5.3

ghc-options:
  - -fwarn-unused-imports

library:
  source-dirs:
  - src/

executables:
  exe:
    main: Main.hs
    source-dirs:
    - app/console/
    dependencies: uKanren-transformation

# executables:
#   exe:
#     main: Main.hs
#     source-dirs:
#       - bench/Contains1/
#     dependencies:
#       - uKanren-transformation
#       - tasty
#       - tasty-bench
#       - deepseq
#     ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"

  # cpd:
  #   main: Main.hs
  #   source-dirs:
  #   - test/cpd/
  #   dependencies: uKanren-transformation
  # main:
  #   main: Main.hs
  #   source-dirs:
  #   - app/
  #   - test/resources/
  #   dependencies: uKanren-transformation


tests:
  uKanren-transformation-test:
    main:                Test.hs
    source-dirs:
    - test/auto
    - test/resources
    dependencies:
    - uKanren-transformation
    - hedgehog
    - HUnit
    - tasty
    - tasty-hedgehog
    - tasty-hunit

benchmarks:
  uKanren-transformation-bench-applast1-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Applast1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-contains1-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Contains1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-deforestation1-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Deforestation1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-deforestation2-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Deforestation2
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-depth-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Depth
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-double-appendo-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/DoubleAppendo
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-ex_depth-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Ex_Depth
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-flip-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Flip
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-match-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Match
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-matchSimple-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/MatchSimple
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-multiply-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Multiply
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-regexp1-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Regexp1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-remove2-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Remove2
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-rotatePrune-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/RotatePrune
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-uptoSum1-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Upto.sum1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-vanilla-det:
    main: Main.hs
    source-dirs:
      - bench/DPPD/Vanilla
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-nthopt-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/NthOpt
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-list3-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/List3
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-list4-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/List4
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-sort-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Sort
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-goat-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Goat
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-rel-sort-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/RelSort
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-rel-sort7-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/RelSort7
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-hanoi-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Hanoi
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-hanoi5-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Hanoi5
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-prop-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Propo
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-goat-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Goat
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-prop-det:
  #   main: Main.hs
  #   source-dirs:
  #     - bench/Hanoi5
  #     - test/resources
  #   dependencies:
  #     - uKanren-transformation
  #     - tasty
  #     - tasty-bench
  #     - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
