name:                uKanren-transformation
version:             0.1.0.0
github:              "kajigor/uKanren-transformation"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2019 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/uKanren-transformation#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- temporary
- text
- fgl
- graphviz
- transformers
- mtl
- extra
- directory
- timeit
- tasty-discover
- pretty-show
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- parsec
- filepath
- megaparsec
- parser-combinators
- optparse-applicative
- prettyprinter

ghc-options:
  - -fwarn-unused-imports

library:
  source-dirs:
  - src/
  - test/resources/

executables:
  exe:
    main: Main.hs
    source-dirs:
    - app/console/
    - test/resources/
    dependencies: uKanren-transformation
  # cpd:
  #   main: Main.hs
  #   source-dirs:
  #   - test/cpd/
  #   dependencies: uKanren-transformation
  # main:
  #   main: Main.hs
  #   source-dirs:
  #   - app/
  #   - test/resources/
  #   dependencies: uKanren-transformation
  # bench:
  #   main: Main.hs
  #   source-dirs:
  #   - app/bench/
  #   - test/resources/
  #   dependencies: uKanren-transformation


tests:
  uKanren-transformation-test:
    main:                Test.hs
    source-dirs:
    - test/auto
    - test/resources
    dependencies:
    - uKanren-transformation
    - hedgehog
    - HUnit
    - tasty
    - tasty-hedgehog
    - tasty-hunit