name:                uKanren-transformation
version:             0.1.0.0
github:              "kajigor/uKanren-transformation"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2019 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kajigor/uKanren-transformation#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- temporary
- text
- fgl
- graphviz
- transformers
- mtl
- extra
- directory
- timeit
- tasty-discover
- pretty-show
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- tasty-bench
- parsec
- filepath
- megaparsec
- parser-combinators
- optparse-applicative
- prettyprinter
- template-haskell >= 2.19.0.0
- split
- groups >= 0.5.3

ghc-options:
  - -fwarn-unused-imports

library:
  source-dirs:
  - src/

executables:
  exe:
    main: Main.hs
    source-dirs:
    - app/console/
    dependencies: uKanren-transformation
  # cpd:
  #   main: Main.hs
  #   source-dirs:
  #   - test/cpd/
  #   dependencies: uKanren-transformation
  # main:
  #   main: Main.hs
  #   source-dirs:
  #   - app/
  #   - test/resources/
  #   dependencies: uKanren-transformation


tests:
  uKanren-transformation-test:
    main:                Test.hs
    source-dirs:
    - test/auto
    - test/resources
    dependencies:
    - uKanren-transformation
    - hedgehog
    - HUnit
    - tasty
    - tasty-hedgehog
    - tasty-hunit

benchmarks:
  # uKanren-transformation-bench-mulo:
  #   main: Main.hs
  #   source-dirs:
  #   - bench/Mulo
  #   - test/resources
  #   dependencies:
  #   - uKanren-transformation
  #   - tasty
  #   - tasty-bench
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-addo:
  #   main: Main.hs
  #   source-dirs:
  #   - bench/Addo
  #   - test/resources
  #   dependencies:
  #   - uKanren-transformation
  #   - tasty
  #   - tasty-bench
  #   - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-addo-det:
  #   main: Main.hs
  #   source-dirs:
  #   - bench/AddoDet
  #   - test/resources
  #   dependencies:
  #   - uKanren-transformation
  #   - tasty
  #   - tasty-bench
  #   - deepseq
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
#  uKanren-transformation-bench-addo-det:
#    main: Main.hs
#    source-dirs:
#    - bench/MuloDet
#    - test/resources
#    dependencies:
#    - uKanren-transformation
#    - tasty
#    - tasty-bench
#    - deepseq
#    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-deforestation1-det:
    main: Main.hs
    source-dirs:
      - bench/Deforestation1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
#  uKanren-transformation-bench-sort_check:
#    main: Main.hs
#    source-dirs:
#      - bench/SortCheck
#      - test/resources
#    dependencies:
#      - uKanren-transformation
#      - tasty
#      - tasty-bench
#      - deepseq
#    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-deforestation2-det:
    main: Main.hs
    source-dirs:
      - bench/Deforestation2
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-nthopt-det:
    main: Main.hs
    source-dirs:
      - bench/NthOpt
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-list4-det:
    main: Main.hs
    source-dirs:
      - bench/List4
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-sort-det:
    main: Main.hs
    source-dirs:
      - bench/Sort
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-applast1-det:
    main: Main.hs
    source-dirs:
      - bench/Applast1
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-depth-det:
    main: Main.hs
    source-dirs:
      - bench/Depth
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  uKanren-transformation-bench-rel-sort-det:
    main: Main.hs
    source-dirs:
      - bench/RelSort
      - test/resources
    dependencies:
      - uKanren-transformation
      - tasty
      - tasty-bench
      - deepseq
    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
#  uKanren-transformation-bench-double-appendo-det:
#    main: Main.hs
#    source-dirs:
#      - bench/DoubleAppendo
#      - test/resources
#    dependencies:
#      - uKanren-transformation
#      - tasty
#      - tasty-bench
#      - deepseq
#    ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"
  # uKanren-transformation-bench-prop:
  #   main: Main.hs
  #   source-dirs:
  #   - bench/Prop
  #   dependencies:
  #   - uKanren-transformation
  #   - tasty
  #   - tasty-bench
  #   ghc-options: "-with-rtsopts=-A32m -fproc-alignment=64"