evalo y0 = (fresh q1, q2 in ((y0 == Lit (Trueo) | (y0 == Neg (q1) & evaloEvalo q1) | (y0 == Neg (q1) & _evaloEvalo q1) | (y0 == Neg (q1) & __evaloEvalo q1) | (y0 == Disj (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Disj (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Disj (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2) | (y0 == Disj (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Disj (q1) (q2) & evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Disj (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y0 == Disj (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2) | (y0 == Disj (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y0 == Disj (q1) (q2) & ____evaloEvalo q1 & evaloEvalo q2) | (y0 == Disj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y0 == Disj (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y0 == Disj (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y0 == Disj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y0 == Disj (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y0 == Disj (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y0 == Conj (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Conj (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Conj (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2) | (y0 == Conj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y0 == Conj (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Conj (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2) | (y0 == Conj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y0 == Impl (q1) (q2) & evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Impl (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y0 == Impl (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Impl (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y0 == Impl (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y0 == Impl (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y0 == Impl (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Impl (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y0 == Impl (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2) | (y0 == Impl (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y0 == Impl (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y0 == Impl (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2) | (y0 == Impl (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y0 == Impl (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y0 == Impl (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2))));

evaloEvalo y1 = (fresh q1, q2 in ((y1 == Lit (Falso) | (y1 == Neg (q1) & ____evaloEvalo q1) | (y1 == Disj (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y1 == Conj (q1) (q2) & evaloEvalo q1 & ____evaloEvalo q2) | (y1 == Conj (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y1 == Conj (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y1 == Conj (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y1 == Conj (q1) (q2) & ____evaloEvalo q1 & evaloEvalo q2) | (y1 == Conj (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y1 == Conj (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y1 == Conj (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y1 == Conj (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y1 == Impl (q1) (q2) & ____evaloEvalo q1 & evaloEvalo q2))));

_evaloEvalo y2 = (fresh q1, q2 in (((y2 == Neg (q1) & __evaloEvalo q1) | (y2 == Disj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y2 == Disj (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y2 == Disj (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y2 == Conj (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y2 == Impl (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y2 == Impl (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y2 == Impl (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2))));

__evaloEvalo y3 = (fresh q1, q2 in (((y3 == Neg (q1) & _evaloEvalo q1) | (y3 == Disj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y3 == Disj (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y3 == Disj (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y3 == Conj (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y3 == Conj (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2) | (y3 == Conj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y3 == Impl (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y3 == Impl (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y3 == Impl (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2))));

____evaloEvalo y5 = (fresh q1, q2 in ((y5 == Lit (Trueo) | (y5 == Neg (q1) & evaloEvalo q1) | (y5 == Disj (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Disj (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Disj (q1) (q2) & ____evaloEvalo q1 & _evaloEvalo q2) | (y5 == Disj (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Disj (q1) (q2) & evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Disj (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y5 == Disj (q1) (q2) & ____evaloEvalo q1 & __evaloEvalo q2) | (y5 == Disj (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y5 == Disj (q1) (q2) & ____evaloEvalo q1 & evaloEvalo q2) | (y5 == Conj (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Impl (q1) (q2) & evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Impl (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y5 == Impl (q1) (q2) & __evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Impl (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y5 == Impl (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y5 == Impl (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y5 == Impl (q1) (q2) & _evaloEvalo q1 & ____evaloEvalo q2) | (y5 == Impl (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y5 == Impl (q1) (q2) & ____evaloEvalo q1 & ____evaloEvalo q2))));


? evalo x0