
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 1300 ms */
/* Unfolding time: 920 ms */
/* Post-Processing time: 1300 ms */

/* Specialised Predicates: 
checkAnswer__1(A,B,C) :- checkAnswer(A,B,C,true).
checkStep_conj__2(A,B,C,D,E) :- checkStep(pair(o,o),pair(A,B),C,true), doStep(pair(o,o),pair(A,B),C,F1), checkAnswer_0(F1,D,C,E,true).
checkAnswer_0__3(A,B,C,D) :- checkAnswer_0(pair(o,o),A,pair(B,C),D,true).
checkAnswer_0__4(A,B,C,D,E,F) :- checkAnswer_0(pair(A,B),C,pair(D,E),F,true).
isFinishState__5(A,B,C) :- isFinishState(pair(A,B),C,true).
checkStep_conj__6(A,B,C,D,E,F,G,H) :- checkStep(pair(A,B),pair(C,D),pair(E,F),true), doStep(pair(A,B),pair(C,D),pair(E,F),I1), checkAnswer_0(I1,G,pair(E,F),H,true).
fancyEq__7(A,B) :- fancyEq(A,B,false).
doStep_conj__8(A,B,C,D,E,F) :- doStep(pair(A,s(B)),pair(pour,snd),pair(C,D),G1), checkAnswer_0(G1,E,pair(C,D),F,true).
add_conj__9(A,B,C,D,E,F) :- add(A,B,C), greater(D,E,false), add(A,B,F).
greater__10(A,B) :- greater(A,B,false).
greater__11(A,B) :- greater(s(A),B,true).
add__12(A,B,C) :- add(A,B,C).
sub_conj__13(A,B,C,D,E,F,G,H,I) :- sub(s(A),B,C), checkAnswer_0(pair(D,E),F,pair(G,H),I,true).
sub_conj__14(A,B,C,D,E,F,G,H,I) :- sub(A,B,C), checkAnswer_0(pair(D,E),F,pair(G,H),I,true).
doStep_conj__15(A,B,C,D,E,F) :- doStep(pair(s(A),B),pair(pour,fst),pair(C,D),G1), checkAnswer_0(G1,E,pair(C,D),F,true).
fancyEq__16(A,B) :- fancyEq(A,B,true).
fancyEq_conj__17(A,B,C) :- fancyEq(A,B,false), fancyEq(C,B,true).
fancyEq__18(A,B) :- fancyEq(A,B,C1).
*/

checkAnswer(A,B,C,true) :- 
    checkAnswer__1(A,B,C).
checkAnswer__1(nil,A,o).
checkAnswer__1(cons(pair(A,B),C),D,E) :- 
    checkStep_conj__2(A,B,D,C,E).
checkStep_conj__2(fill,fst,pair(A,B),C,D) :- 
    checkAnswer_0__4(A,o,C,A,B,D).
checkStep_conj__2(fill,snd,pair(A,B),C,D) :- 
    checkAnswer_0__4(o,B,C,A,B,D).
checkStep_conj__2(empty,fst,pair(o,A),B,C) :- 
    checkAnswer_0__3(B,o,A,C).
checkStep_conj__2(empty,snd,pair(A,o),B,C) :- 
    checkAnswer_0__3(B,A,o,C).
checkAnswer_0__3(nil,A,B,o).
checkAnswer_0__3(cons(pair(A,B),C),D,E,F) :- 
    checkStep_conj__2(A,B,pair(D,E),C,F).
checkAnswer_0__4(A,B,nil,C,D,E) :- 
    isFinishState__5(A,B,E).
checkAnswer_0__4(A,B,cons(pair(C,D),E),F,G,H) :- 
    checkStep_conj__6(A,B,C,D,F,G,E,H).
isFinishState__5(A,B,C) :- 
    fancyEq__16(A,C), 
    fancyEq__18(B,C).
isFinishState__5(A,B,C) :- 
    fancyEq_conj__17(A,C,B).
checkStep_conj__6(o,A,fill,fst,B,C,D,E) :- 
    checkAnswer_0__4(B,A,D,B,C,E).
checkStep_conj__6(A,o,fill,snd,B,C,D,E) :- 
    checkAnswer_0__4(A,C,D,B,C,E).
checkStep_conj__6(A,B,empty,fst,C,D,E,F) :- 
    fancyEq__16(A,C), 
    checkAnswer_0__4(o,B,E,C,D,F).
checkStep_conj__6(A,B,empty,snd,C,D,E,F) :- 
    fancyEq__16(B,D), 
    checkAnswer_0__4(A,o,E,C,D,F).
checkStep_conj__6(s(A),B,pour,fst,C,D,E,F) :- 
    fancyEq__7(B,D), 
    doStep_conj__15(A,B,C,D,E,F).
checkStep_conj__6(A,s(B),pour,snd,C,D,E,F) :- 
    fancyEq__7(A,C), 
    doStep_conj__8(A,B,C,D,E,F).
fancyEq__7(o,s(A)).
fancyEq__7(s(A),o).
fancyEq__7(s(A),s(B)) :- 
    fancyEq__7(A,B).
doStep_conj__8(A,B,C,D,E,F) :- 
    add__12(A,s(B),s(G)), 
    greater__11(G,C), 
    add__12(A,s(B),s(H)), 
    sub_conj__13(H,C,I,C,I,E,C,D,F).
doStep_conj__8(A,B,s(C),D,E,F) :- 
    add_conj__9(A,s(B),s(G),G,C,s(H)), 
    checkAnswer_0__4(s(H),o,E,s(C),D,F).
add_conj__9(o,A,A,B,C,A) :- 
    greater__10(B,C).
add_conj__9(s(A),B,s(C),s(D),s(E),s(F)) :- 
    add_conj__9(A,B,C,D,E,F).
greater__10(o,A).
greater__10(s(A),s(B)) :- 
    greater__10(A,B).
greater__11(A,o).
greater__11(s(A),s(B)) :- 
    greater__11(A,B).
add__12(o,A,A).
add__12(s(A),B,s(C)) :- 
    add__12(A,B,C).
sub_conj__13(A,o,s(A),B,C,D,E,F,G) :- 
    checkAnswer_0__4(B,C,D,E,F,G).
sub_conj__13(A,s(B),C,D,E,F,G,H,I) :- 
    sub_conj__14(A,B,C,D,E,F,G,H,I).
sub_conj__14(A,o,A,B,C,D,E,F,G) :- 
    checkAnswer_0__4(B,C,D,E,F,G).
sub_conj__14(o,s(A),o,B,C,D,E,F,G) :- 
    checkAnswer_0__4(B,C,D,E,F,G).
sub_conj__14(s(A),s(B),C,D,E,F,G,H,I) :- 
    sub_conj__14(A,B,C,D,E,F,G,H,I).
doStep_conj__15(A,B,C,D,E,F) :- 
    add__12(A,B,G), 
    greater__11(G,D), 
    add__12(A,B,H), 
    sub_conj__13(H,D,I,I,D,E,C,D,F).
doStep_conj__15(A,B,C,s(D),E,F) :- 
    add_conj__9(A,B,G,G,D,H), 
    checkAnswer_0__4(o,s(H),E,C,s(D),F).
fancyEq__16(o,o).
fancyEq__16(s(A),s(B)) :- 
    fancyEq__16(A,B).
fancyEq_conj__17(o,s(A),s(B)) :- 
    fancyEq__16(B,A).
fancyEq_conj__17(s(A),o,o).
fancyEq_conj__17(s(A),s(B),s(C)) :- 
    fancyEq_conj__17(A,B,C).
fancyEq__18(o,o).
fancyEq__18(o,s(A)).
fancyEq__18(s(A),o).
fancyEq__18(s(A),s(B)) :- 
    fancyEq__18(A,B).
