
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 60 ms */
/* Unfolding time: 20 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates: 
sorto__1(A,B) :- sorto(A,B).
smallesto__2(A,B,C,D) :- smallesto(cons(A,B),C,D).
minmaxo_conj__3(A,B,C,D,E,F) :- minmaxo(A,B,G1,C), smallesto(cons(D,E),G1,F).
gto__4(A,B) :- gto(A,s(B)).
leo__5(A,B) :- leo(A,B).
*/

sorto(A,B) :- 
    sorto__1(A,B).
sorto__1(nil,nil).
sorto__1(cons(A,B),cons(C,D)) :- 
    sorto__1(E,D), 
    smallesto__2(A,B,C,E).
smallesto__2(A,nil,A,nil).
smallesto__2(A,cons(B,C),D,cons(E,F)) :- 
    minmaxo_conj__3(D,A,E,B,C,F).
minmaxo_conj__3(o,o,A,B,C,D) :- 
    smallesto__2(B,C,A,D).
minmaxo_conj__3(s(A),s(A),s(B),C,D,E) :- 
    leo__5(A,B), 
    smallesto__2(C,D,s(B),E).
minmaxo_conj__3(o,s(A),s(A),B,C,D) :- 
    smallesto__2(B,C,o,D).
minmaxo_conj__3(s(A),s(s(B)),s(s(B)),C,D,E) :- 
    gto__4(A,B), 
    smallesto__2(C,D,s(A),E).
gto__4(o,A).
gto__4(s(A),s(B)) :- 
    gto__4(A,B).
leo__5(o,A).
leo__5(s(A),s(B)) :- 
    leo__5(A,B).
