
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 16480 ms */
/* Unfolding time: 11420 ms */
/* Post-Processing time: 16480 ms */

/* Specialised Predicates:
checkAnswer__1(A,B,C,D) :- checkAnswer(A,B,C,some(D)).
stations__3(A,B) :- stations(A,B).
goe_conj__5(A,B,C,D,E) :- goe(A,B,true), goe(C,B,true), sub(D,B,E).
calcFuel__6(A,B,C,D,E,F,G,H) :- calcFuel(st(A,B,cons(C,D)),E,s(F),s(G),true,some(H)).
isMove_conj__7(A,B,C,D,E,F,G,H,I) :- isMove(A,false), checkStep(A,st(B,C,cons(D,E)),s(F),s(G),true), step(A,st(B,C,cons(D,E)),s(F),s(G),st(J1,K1,L1)), calcFuel(st(J1,K1,L1),H,s(F),s(G),false,some(M1)), getFuel(A,st(B,C,cons(D,E)),s(G),N1), add(N1,M1,I).
checkStep_conj__8(A,B,C,D,E,F,G,H) :- checkStep(fill,st(A,B,cons(C,D)),s(E),s(F),true), step(fill,st(A,B,cons(C,D)),s(E),s(F),st(A,I1,J1)), calcFuel(st(A,I1,J1),G,s(E),s(F),false,some(K1)), getFuel(fill,st(A,B,cons(C,D)),s(F),L1), add(L1,K1,H).
goe_conj__9(A,B,C) :- goe(A,B,true), sub(A,B,C).
addForElem__10(A,B,C,D,E,F) :- addForElem(cons(A,B),C,s(D),cons(E,F)).
calcFuel__11(A,B,C,D,E,F,G,H) :- calcFuel(st(s(A),B,cons(C,D)),E,s(F),s(G),false,some(H)).
eqNat__12(A,B) :- eqNat(A,B,true).
isMove_conj__13(A,B,C,D,E,F,G,H,I) :- isMove(A,true), checkStep(A,st(s(B),C,cons(D,E)),s(F),s(G),true), step(A,st(s(B),C,cons(D,E)),s(F),s(G),st(J1,K1,L1)), calcFuel(st(J1,K1,L1),H,s(F),s(G),true,some(I)), getFuel(A,st(s(B),C,cons(D,E)),s(G),o).
goe_conj__14(A,B,C,D,E,F,G,H,I) :- goe(A,B,true), goe(C,B,true), sub(A,B,J1), sub(C,B,K1), calcFuel(st(J1,K1,cons(D,E)),F,s(G),s(H),true,some(I)).
add_conj__15(A,B,C,D) :- add(A,s(B),s(E1)), goe(C,E1,true), goe(D,B,true).
add_conj__16(A,B,C,D,E,F,G,H,I,J,K) :- add(A,s(B),s(C)), sub(D,B,L1), calcFuel(st(s(s(E)),L1,cons(F,G)),H,s(s(I)),s(J),true,some(K)).
sub_conj__17(A,B,C,D,E,F,G,H,I) :- sub(A,B,J1), calcFuel(st(s(s(C)),J1,cons(D,E)),F,s(s(G)),s(H),true,some(I)).
goe_conj__18(A,B,C) :- goe(A,B,true), goe(C,B,true).
goe__19(A) :- goe(A,o,true).
goe_conj__20(A,B,C,D,E,F,G) :- goe(A,o,true), calcFuel(st(o,A,cons(B,C)),D,s(E),s(F),true,some(G)).
goe_conj__21(A,B,C,D,E,F,G,H) :- goe(A,o,true), calcFuel(st(s(B),A,cons(C,D)),E,s(F),s(G),true,some(H)).
eqNat__24(A,B) :- eqNat(A,B,false).
sub_conj__25(A,B,C,D) :- sub(A,B,E1), add(E1,C,D).
add__26(A,B,C) :- add(A,B,C).
eqNat_conj__27(A,B,C,D,E,F,G) :- eqNat(A,s(B),false), calcFuel(st(o,s(B),cons(C,D)),E,s(F),s(B),false,some(H1)), sub(s(B),A,I1), add(I1,H1,G).
eqNat__28(A,B) :- eqNat(A,s(B),false).
elem__29(A,B,C) :- elem(cons(A,B),C,s(D1)).
step_conj__30(A,B,C,D,E,F,G,H) :- step(fill,st(s(A),B,cons(C,D)),s(E),s(F),st(s(A),I1,J1)), calcFuel(st(s(A),I1,J1),G,s(E),s(F),false,some(H)).
elem_conj__31(A,B,C,D,E,F,G,H) :- elem(cons(A,B),C,I1), add(D,I1,s(J1)), goe(J1,E,true), sub(J1,E,K1), setForElem(cons(A,B),C,K1,cons(L1,M1)), calcFuel(st(s(C),s(E),cons(L1,M1)),F,s(G),s(E),false,some(H)).
elem_conj__32(A,B,C,D,E,F,G,H) :- elem(cons(A,B),C,I1), add(D,I1,J1), goe(J1,s(E),false), setForElem(cons(A,B),C,o,cons(K1,L1)), calcFuel(st(s(C),J1,cons(K1,L1)),F,s(G),s(E),false,some(H)).
elem_conj__33(A,B,C,D,E,F,G,H,I,J,K,L,M,N) :- elem(cons(A,B),C,O1), add(D,O1,P1), goe(P1,s(E),false), addForElem(cons(A,B),C,o,cons(F,G)), calcFuel(st(s(s(H)),P1,cons(I,cons(J,K))),L,s(M),s(E),false,some(N)).
add_conj__34(A,B,C,D) :- add(A,B,C), goe(C,s(D),false).
calcFuel__35(A,B,C,D,E,F,G,H,I) :- calcFuel(st(s(s(A)),B,cons(C,cons(D,E))),F,s(G),s(H),false,some(I)).
isMove_conj__36(A,B,C,D,E,F,G,H,I,J) :- isMove(A,true), checkStep(A,st(s(s(B)),C,cons(D,cons(E,F))),s(G),s(H),true), step(A,st(s(s(B)),C,cons(D,cons(E,F))),s(G),s(H),st(K1,L1,M1)), calcFuel(st(K1,L1,M1),I,s(G),s(H),true,some(J)), getFuel(A,st(s(s(B)),C,cons(D,cons(E,F))),s(H),o).
goe_conj__37(A,B,C,D,E,F,G,H,I,J) :- goe(s(A),B,true), goe(C,B,true), sub(s(A),B,K1), sub(C,B,L1), calcFuel(st(K1,L1,cons(D,cons(E,F))),G,s(H),s(I),true,some(J)).
goe_conj__38(A,B,C,D,E,F,G,H,I,J) :- goe(A,B,true), goe(C,B,true), sub(A,B,K1), sub(C,B,L1), calcFuel(st(K1,L1,cons(D,cons(E,F))),G,s(H),s(I),true,some(J)).
goe_conj__39(A,B,C,D,E,F,G,H) :- goe(A,o,true), calcFuel(st(o,A,cons(B,cons(C,D))),E,s(F),s(G),true,some(H)).
goe__42(A,B) :- goe(A,s(B),false).
calcFuel__43(A,B,C,D,E,F) :- calcFuel(st(s(o),A,cons(o,B)),C,s(D),s(E),false,some(F)).
isMove_conj__44(A,B,C,D,E,F,G) :- isMove(A,true), checkStep(A,st(s(o),B,cons(o,C)),s(D),s(E),true), step(A,st(s(o),B,cons(o,C)),s(D),s(E),st(H1,I1,J1)), calcFuel(st(H1,I1,J1),F,s(D),s(E),true,some(G)), getFuel(A,st(s(o),B,cons(o,C)),s(E),o).
goe_conj__45(A,B,C,D,E,F) :- goe(A,o,true), calcFuel(st(o,A,cons(o,B)),C,s(D),s(E),true,some(F)).
goe_conj__46(A,B,C,D,E,F,G,H,I,J) :- goe(A,B,true), goe(C,B,true), sub(C,B,K1), calcFuel(st(s(s(D)),K1,cons(E,F)),G,s(s(H)),s(I),true,some(J)).
add_conj__49(A,B,C,D,E,F,G) :- add(A,B,s(H1)), goe(H1,C,true), sub(H1,C,I1), calcFuel(st(s(o),s(C),cons(I1,D)),E,s(F),s(C),false,some(G)).
elem_conj__50(A,B,C,D,E,F,G,H,I,J,K,L,M,N) :- elem(cons(A,B),C,O1), add(D,O1,s(P1)), goe(P1,E,true), sub(P1,E,Q1), addForElem(cons(A,B),C,Q1,cons(F,G)), calcFuel(st(s(s(H)),s(E),cons(I,cons(J,K))),L,s(M),s(E),false,some(N)).
add_conj__51(A,B,C,D) :- add(A,B,s(E1)), goe(E1,C,true), sub(E1,C,D).
calcFuel__52(A,B,C,D,E,F,G,H) :- calcFuel(st(s(s(A)),s(B),cons(C,cons(D,E))),F,s(G),s(B),false,some(H)).
isMove_conj__53(A,B,C,D,E,F,G,H,I) :- isMove(A,true), checkStep(A,st(s(s(B)),s(C),cons(D,cons(E,F))),s(G),s(C),true), step(A,st(s(s(B)),s(C),cons(D,cons(E,F))),s(G),s(C),st(J1,K1,L1)), calcFuel(st(J1,K1,L1),H,s(G),s(C),true,some(I)), getFuel(A,st(s(s(B)),s(C),cons(D,cons(E,F))),s(C),o).
goe_conj__54(A,B,C,D,E,F,G,H,I) :- goe(s(A),B,true), goe(C,B,true), sub(s(A),B,J1), sub(C,B,K1), calcFuel(st(J1,K1,cons(D,cons(E,F))),G,s(H),s(C),true,some(I)).
goe_conj__55(A,B,C,D,E,F,G,H,I,J) :- goe(A,B,true), goe(C,B,true), sub(A,B,K1), sub(C,B,L1), calcFuel(st(K1,L1,cons(D,cons(E,F))),G,s(H),s(s(I)),true,some(J)).
goe_conj__56(A,B,C,D,E,F,G,H) :- goe(A,o,true), calcFuel(st(o,A,cons(B,cons(C,D))),E,s(F),s(s(G)),true,some(H)).
eqNat_conj__59(A,B,C,D,E,F,G,H) :- eqNat(A,s(B),false), calcFuel(st(o,s(s(B)),cons(C,cons(D,E))),F,s(G),s(s(B)),false,some(I1)), sub(s(B),A,J1), add(J1,I1,H).
goe_conj__60(A,B,C,D,E,F,G) :- goe(A,B,true), sub(A,B,H1), calcFuel(st(s(o),s(C),cons(H1,D)),E,s(F),s(C),false,some(G)).
calcFuel__61(A,B,C,D,E) :- calcFuel(st(s(o),s(A),cons(o,B)),C,s(D),s(A),false,some(E)).
calcFuel__62(A,B,C,D,E,F) :- calcFuel(st(s(o),s(A),cons(s(B),C)),D,s(E),s(A),false,some(F)).
isMove_conj__63(A,B,C,D,E,F,G) :- isMove(A,true), checkStep(A,st(s(o),s(B),cons(s(C),D)),s(E),s(B),true), step(A,st(s(o),s(B),cons(s(C),D)),s(E),s(B),st(H1,I1,J1)), calcFuel(st(H1,I1,J1),F,s(E),s(B),true,some(G)), getFuel(A,st(s(o),s(B),cons(s(C),D)),s(B),o).
isMove_conj__64(A,B,C,D,E,F) :- isMove(A,true), checkStep(A,st(s(o),s(B),cons(o,C)),s(D),s(B),true), step(A,st(s(o),s(B),cons(o,C)),s(D),s(B),st(G1,H1,I1)), calcFuel(st(G1,H1,I1),E,s(D),s(B),true,some(F)), getFuel(A,st(s(o),s(B),cons(o,C)),s(B),o).
sub__65(A,B,C) :- sub(A,s(B),C).
sub__66(A,B,C) :- sub(A,B,C).
*/

checkAnswer(A,B,C,some(D)) :-
  checkAnswer__1(A,B,C,D).
checkAnswer__1(nil,o,A,A).
checkAnswer__1(cons(right(s(A)),B),s(C),s(D),E) :-
  stations__3(C,F),
  goe_conj__5(C,A,D,D,G),
  calcFuel__6(s(A),G,o,F,B,C,D,E).
stations__3(o,nil).
stations__3(s(A),cons(o,B)) :-
  stations__3(A,B).
goe_conj__5(o,o,A,B,B) :-
  goe__19(A).
goe_conj__5(s(A),o,B,C,C) :-
  goe__19(B).
goe_conj__5(s(A),s(B),s(C),D,E) :-
  goe_conj__18(A,B,C),
  sub__65(D,B,E).
calcFuel__6(s(A),B,C,D,nil,E,F,s(F)) :-
  eqNat__12(A,E).
calcFuel__6(A,B,C,D,cons(E,F),G,H,I) :-
  isMove_conj__7(E,A,B,C,D,G,H,F,I).
isMove_conj__7(fill,A,B,C,D,E,F,G,H) :-
  checkStep_conj__8(A,B,C,D,E,F,G,H).
isMove_conj__7(pour(s(A)),s(B),s(C),D,E,F,G,H,I) :-
  eqNat__24(B,F),
  goe_conj__9(C,A,J),
  addForElem__10(D,E,B,A,K,L),
  calcFuel__11(B,J,K,L,H,F,G,I).
checkStep_conj__8(o,A,B,C,D,E,F,G) :-
  eqNat_conj__27(A,E,B,C,F,D,G).
checkStep_conj__8(s(A),B,C,D,E,F,G,H) :-
  eqNat__28(B,F),
  elem__29(C,D,A),
  step_conj__30(A,B,C,D,E,F,G,H).
goe_conj__9(o,o,o).
goe_conj__9(s(A),o,s(A)).
goe_conj__9(s(A),s(B),C) :-
  goe_conj__9(A,B,C).
addForElem__10(A,B,o,C,s(D),B) :-
  add__26(C,A,D).
addForElem__10(A,cons(B,C),s(D),E,A,cons(F,G)) :-
  addForElem__10(B,C,D,E,F,G).
calcFuel__11(A,B,C,D,nil,E,F,s(F)) :-
  eqNat__12(A,E).
calcFuel__11(A,B,C,D,cons(E,F),G,H,I) :-
  isMove_conj__13(E,A,B,C,D,G,H,F,I).
eqNat__12(o,o).
eqNat__12(s(A),s(B)) :-
  eqNat__12(A,B).
isMove_conj__13(left(s(A)),B,s(C),D,E,F,G,H,I) :-
  goe_conj__14(B,A,C,D,E,H,F,G,I).
isMove_conj__13(right(s(A)),B,s(C),D,E,s(F),G,H,I) :-
  add_conj__15(B,A,F,C),
  add_conj__16(B,A,J,C,J,D,E,H,F,G,I).
goe_conj__14(o,o,A,B,C,D,E,F,G) :-
  goe_conj__20(A,B,C,D,E,F,G).
goe_conj__14(s(A),o,B,C,D,E,F,G,H) :-
  goe_conj__21(B,A,C,D,E,F,G,H).
goe_conj__14(s(A),s(B),s(C),D,E,F,G,H,I) :-
  goe_conj__14(A,B,C,D,E,F,G,H,I).
add_conj__15(o,A,B,C) :-
  goe_conj__18(B,A,C).
add_conj__15(s(A),B,s(C),D) :-
  add_conj__15(A,B,C,D).
add_conj__16(o,A,A,B,C,D,E,F,G,H,I) :-
  sub_conj__17(B,A,C,D,E,F,G,H,I).
add_conj__16(s(A),B,s(C),D,E,F,G,H,I,J,K) :-
  add_conj__16(A,B,C,D,E,F,G,H,I,J,K).
sub_conj__17(A,o,B,C,D,E,F,G,H) :-
  calcFuel__6(s(s(B)),A,C,D,E,s(F),G,H).
sub_conj__17(o,s(A),B,C,D,E,F,G,H) :-
  calcFuel__6(s(s(B)),o,C,D,E,s(F),G,H).
sub_conj__17(s(A),s(B),C,D,E,F,G,H,I) :-
  sub_conj__17(A,B,C,D,E,F,G,H,I).
goe_conj__18(o,o,A) :-
  goe__19(A).
goe_conj__18(s(A),o,B) :-
  goe__19(B).
goe_conj__18(s(A),s(B),s(C)) :-
  goe_conj__18(A,B,C).
goe__19(o).
goe__19(s(A)).
goe_conj__20(o,A,B,cons(fill,cons(right(s(C)),D)),E,F,s(G)) :-
  goe_conj__5(E,C,F,F,H),
  calcFuel__6(s(C),H,A,B,D,E,F,I),
  add__26(F,I,G).
goe_conj__20(s(A),B,C,cons(fill,cons(right(s(D)),E)),F,G,H) :-
  eqNat__24(A,G),
  goe_conj__5(F,D,G,G,I),
  calcFuel__6(s(D),I,B,C,E,F,G,J),
  sub_conj__25(G,A,J,H).
goe_conj__21(o,A,B,C,D,E,F,G) :-
  calcFuel__6(s(A),o,B,C,D,E,F,G).
goe_conj__21(s(A),B,C,D,E,F,G,H) :-
  calcFuel__6(s(B),s(A),C,D,E,F,G,H).
eqNat__24(o,s(A)).
eqNat__24(s(A),o).
eqNat__24(s(A),s(B)) :-
  eqNat__24(A,B).
sub_conj__25(A,o,B,C) :-
  add__26(A,B,C).
sub_conj__25(o,s(A),B,B).
sub_conj__25(s(A),s(B),C,D) :-
  sub_conj__25(A,B,C,D).
add__26(o,A,A).
add__26(s(A),B,s(C)) :-
  add__26(A,B,C).
eqNat_conj__27(o,A,B,C,cons(right(s(D)),E),F,s(G)) :-
  goe_conj__5(F,D,A,A,H),
  calcFuel__6(s(D),H,B,C,E,F,A,I),
  add__26(A,I,G).
eqNat_conj__27(s(A),B,C,D,cons(right(s(E)),F),G,H) :-
  eqNat__24(A,B),
  goe_conj__5(G,E,B,B,I),
  calcFuel__6(s(E),I,C,D,F,G,B,J),
  sub_conj__25(B,A,J,H).
eqNat__28(o,A).
eqNat__28(s(A),B) :-
  eqNat__24(A,B).
elem__29(s(A),B,o).
elem__29(A,cons(B,C),s(D)) :-
  elem__29(B,C,D).
step_conj__30(A,B,C,D,E,F,G,H) :-
  elem_conj__31(C,D,A,B,F,G,E,H).
step_conj__30(A,B,C,D,E,F,G,H) :-
  elem_conj__32(C,D,A,B,F,G,E,H).
elem_conj__31(A,B,o,C,D,E,F,G) :-
  add_conj__49(C,A,D,B,E,F,G).
elem_conj__31(A,cons(B,C),s(D),E,F,G,H,I) :-
  elem_conj__50(B,C,D,E,F,J,K,D,A,J,K,G,H,I).
elem_conj__32(A,B,o,C,D,E,F,G) :-
  add_conj__34(C,A,H,D),
  calcFuel__43(H,B,E,F,D,G).
elem_conj__32(A,cons(B,C),s(D),E,F,G,H,I) :-
  elem_conj__33(B,C,D,E,F,J,K,D,A,J,K,G,H,I).
elem_conj__33(A,B,o,C,D,A,B,E,F,G,H,I,J,K) :-
  add_conj__34(C,A,L,D),
  calcFuel__35(E,L,F,G,H,I,J,D,K).
elem_conj__33(A,cons(B,C),s(D),E,F,A,cons(G,H),I,J,K,L,M,N,O) :-
  elem_conj__33(B,C,D,E,F,G,H,I,J,K,L,M,N,O).
add_conj__34(o,A,A,B) :-
  goe__42(A,B).
add_conj__34(s(A),B,s(C),s(D)) :-
  add_conj__34(A,B,C,D).
calcFuel__35(A,B,C,D,E,nil,s(F),G,s(G)) :-
  eqNat__12(A,F).
calcFuel__35(A,B,C,D,E,cons(F,G),H,I,J) :-
  isMove_conj__36(F,A,B,C,D,E,H,I,G,J).
isMove_conj__36(left(s(A)),B,s(C),D,E,F,G,H,I,J) :-
  goe_conj__37(B,A,C,D,E,F,I,G,H,J).
isMove_conj__36(right(s(A)),B,s(C),D,E,F,s(s(G)),H,I,J) :-
  add_conj__15(B,A,G,C),
  add_conj__16(B,A,K,C,s(K),D,cons(E,F),I,s(G),H,J).
goe_conj__37(A,o,B,C,D,E,F,G,H,I) :-
  goe_conj__21(B,A,C,cons(D,E),F,G,H,I).
goe_conj__37(A,s(B),s(C),D,E,F,G,H,I,J) :-
  goe_conj__38(A,B,C,D,E,F,G,H,I,J).
goe_conj__38(o,o,A,B,C,D,E,F,G,H) :-
  goe_conj__39(A,B,C,D,E,F,G,H).
goe_conj__38(s(A),o,B,C,D,E,F,G,H,I) :-
  goe_conj__21(B,A,C,cons(D,E),F,G,H,I).
goe_conj__38(s(A),s(B),s(C),D,E,F,G,H,I,J) :-
  goe_conj__38(A,B,C,D,E,F,G,H,I,J).
goe_conj__39(o,A,B,C,cons(fill,cons(right(s(D)),E)),F,G,s(H)) :-
  goe_conj__5(F,D,G,G,I),
  calcFuel__6(s(D),I,A,cons(B,C),E,F,G,J),
  add__26(G,J,H).
goe_conj__39(s(A),B,C,D,cons(fill,cons(right(s(E)),F)),G,H,I) :-
  eqNat__24(A,H),
  goe_conj__5(G,E,H,H,J),
  calcFuel__6(s(E),J,B,cons(C,D),F,G,H,K),
  sub_conj__25(H,A,K,I).
goe__42(o,A).
goe__42(s(A),s(B)) :-
  goe__42(A,B).
calcFuel__43(A,B,nil,o,C,s(C)).
calcFuel__43(A,B,cons(C,D),E,F,G) :-
  isMove_conj__44(C,A,B,E,F,D,G).
isMove_conj__44(left(s(o)),s(A),B,C,D,E,F) :-
  goe_conj__45(A,B,E,C,D,F).
isMove_conj__44(right(s(A)),s(B),C,s(D),E,F,G) :-
  goe_conj__46(D,A,B,A,o,C,F,D,E,G).
goe_conj__45(o,A,cons(fill,cons(right(s(B)),C)),D,E,s(F)) :-
  goe_conj__5(D,B,E,E,G),
  calcFuel__6(s(B),G,o,A,C,D,E,H),
  add__26(E,H,F).
goe_conj__45(s(A),B,cons(fill,cons(right(s(C)),D)),E,F,G) :-
  eqNat__24(A,F),
  goe_conj__5(E,C,F,F,H),
  calcFuel__6(s(C),H,o,B,D,E,F,I),
  sub_conj__25(F,A,I,G).
goe_conj__46(o,o,A,B,C,D,E,F,G,H) :-
  goe_conj__21(A,s(B),C,D,E,s(F),G,H).
goe_conj__46(s(A),o,B,C,D,E,F,G,H,I) :-
  goe_conj__21(B,s(C),D,E,F,s(G),H,I).
goe_conj__46(s(A),s(B),s(C),D,E,F,G,H,I,J) :-
  goe_conj__46(A,B,C,D,E,F,G,H,I,J).
add_conj__49(o,s(A),B,C,D,E,F) :-
  goe_conj__60(A,B,B,C,D,E,F).
add_conj__49(s(A),B,C,D,E,F,G) :-
  add__26(A,B,H),
  goe_conj__60(H,C,C,D,E,F,G).
elem_conj__50(A,B,o,C,D,E,B,F,G,H,I,J,K,L) :-
  add_conj__51(C,A,D,M),
  add__26(M,A,E),
  calcFuel__52(F,D,G,H,I,J,K,L).
elem_conj__50(A,cons(B,C),s(D),E,F,A,cons(G,H),I,J,K,L,M,N,O) :-
  elem_conj__50(B,C,D,E,F,G,H,I,J,K,L,M,N,O).
add_conj__51(o,s(A),B,C) :-
  goe_conj__9(A,B,C).
add_conj__51(s(A),B,C,D) :-
  add__26(A,B,E),
  goe_conj__9(E,C,D).
calcFuel__52(A,B,C,D,E,nil,s(F),s(B)) :-
  eqNat__12(A,F).
calcFuel__52(A,B,C,D,E,cons(F,G),H,I) :-
  isMove_conj__53(F,A,B,C,D,E,H,G,I).
isMove_conj__53(left(s(A)),B,C,D,E,F,G,H,I) :-
  goe_conj__54(B,A,C,D,E,F,H,G,I).
isMove_conj__53(right(s(A)),B,C,D,E,F,s(s(G)),H,I) :-
  add_conj__15(B,A,G,C),
  add_conj__16(B,A,J,C,s(J),D,cons(E,F),H,s(G),C,I).
goe_conj__54(A,o,B,C,D,E,F,G,H) :-
  goe_conj__21(B,A,C,cons(D,E),F,G,B,H).
goe_conj__54(A,s(B),s(C),D,E,F,G,H,I) :-
  goe_conj__55(A,B,C,D,E,F,G,H,C,I).
goe_conj__55(o,o,A,B,C,D,E,F,G,H) :-
  goe_conj__56(A,B,C,D,E,F,G,H).
goe_conj__55(s(A),o,B,C,D,E,F,G,H,I) :-
  goe_conj__21(B,A,C,cons(D,E),F,G,s(H),I).
goe_conj__55(s(A),s(B),s(C),D,E,F,G,H,I,J) :-
  goe_conj__55(A,B,C,D,E,F,G,H,I,J).
goe_conj__56(o,A,B,C,cons(fill,cons(right(s(D)),E)),F,G,s(s(H))) :-
  goe_conj__5(F,D,s(G),s(G),I),
  calcFuel__6(s(D),I,A,cons(B,C),E,F,s(G),J),
  add__26(G,J,H).
goe_conj__56(s(A),B,C,D,cons(fill,E),F,G,H) :-
  eqNat_conj__59(A,G,B,C,D,E,F,H).
eqNat_conj__59(o,A,B,C,D,cons(right(s(E)),F),G,s(H)) :-
  goe_conj__5(G,E,s(A),s(A),I),
  calcFuel__6(s(E),I,B,cons(C,D),F,G,s(A),J),
  add__26(A,J,H).
eqNat_conj__59(s(A),B,C,D,E,cons(right(s(F)),G),H,I) :-
  eqNat__24(A,B),
  goe_conj__5(H,F,s(B),s(B),J),
  calcFuel__6(s(F),J,C,cons(D,E),G,H,s(B),K),
  sub_conj__25(B,A,K,I).
goe_conj__60(o,o,A,B,C,D,E) :-
  calcFuel__61(A,B,C,D,E).
goe_conj__60(s(A),o,B,C,D,E,F) :-
  calcFuel__62(B,A,C,D,E,F).
goe_conj__60(s(A),s(B),C,D,E,F,G) :-
  goe_conj__60(A,B,C,D,E,F,G).
calcFuel__61(A,B,nil,o,s(A)).
calcFuel__61(A,B,cons(C,D),E,F) :-
  isMove_conj__64(C,A,B,E,D,F).
calcFuel__62(A,B,C,nil,o,s(A)).
calcFuel__62(A,B,C,cons(D,E),F,G) :-
  isMove_conj__63(D,A,B,C,F,E,G).
isMove_conj__63(left(s(o)),A,B,C,D,cons(fill,E),F) :-
  goe__19(A),
  eqNat_conj__27(A,A,s(B),C,E,D,F).
isMove_conj__63(right(s(A)),B,C,D,s(E),F,G) :-
  goe_conj__46(E,A,B,A,s(C),D,F,E,B,G).
isMove_conj__64(left(s(o)),A,B,C,cons(fill,D),E) :-
  goe__19(A),
  eqNat_conj__27(A,A,o,B,D,C,E).
isMove_conj__64(right(s(A)),B,C,s(D),E,F) :-
  goe_conj__46(D,A,B,A,o,C,E,D,B,F).
sub__65(o,A,o).
sub__65(s(A),B,C) :-
  sub__66(A,B,C).
sub__66(A,o,A).
sub__66(o,s(A),o).
sub__66(s(A),s(B),C) :-
  sub__66(A,B,C).