module Vanilla_for_fun where

import Stream
import Control.Monad

data Term
    = App Term Term Term
    | Cons Term Term
    | DoubleApp Term Term Term Term
    | My_clause2 Term Term
    | Nil
    | O
    | S Term
    | Solve2 Term
    | Solve_atom2 Term
    deriving (Show, Eq)
helpOOO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8 = msum [do {let {x124 = O};
                                                                                                                                                                                                                                                                                                                      let {x123 = S x124};
                                                                                                                                                                                                                                                                                                                      let {x122 = S x123};
                                                                                                                                                                                                                                                                                                                      let {x127 = O};
                                                                                                                                                                                                                                                                                                                      let {x126 = S x127};
                                                                                                                                                                                                                                                                                                                      let {x131 = O};
                                                                                                                                                                                                                                                                                                                      let {x130 = S x131};
                                                                                                                                                                                                                                                                                                                      let {x129 = S x130};
                                                                                                                                                                                                                                                                                                                      let {x134 = O};
                                                                                                                                                                                                                                                                                                                      let {x133 = S x134};
                                                                                                                                                                                                                                                                                                                      let {x135 = Nil};
                                                                                                                                                                                                                                                                                                                      let {x132 = Cons x133 x135};
                                                                                                                                                                                                                                                                                                                      let {x128 = Cons x129 x132};
                                                                                                                                                                                                                                                                                                                      let {x125 = Cons x126 x128};
                                                                                                                                                                                                                                                                                                                      let {x121 = Cons x122 x125};
                                                                                                                                                                                                                                                                                                                      let {x136 = Nil};
                                                                                                                                                                                                                                                                                                                      x119 <- solveO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8;
                                                                                                                                                                                                                                                                                                                      x120 <- case x119 of
                                                                                                                                                                                                                                                                                                                              {Cons y120
                                                                                                                                                                                                                                                                                                                                    y136 -> do {guard (x136 == y136);
                                                                                                                                                                                                                                                                                                                                                return y120};
                                                                                                                                                                                                                                                                                                                               _ -> mzero};
                                                                                                                                                                                                                                                                                                                      (x0,
                                                                                                                                                                                                                                                                                                                       x1,
                                                                                                                                                                                                                                                                                                                       x2) <- case x120 of
                                                                                                                                                                                                                                                                                                                              {DoubleApp y0
                                                                                                                                                                                                                                                                                                                                         y1
                                                                                                                                                                                                                                                                                                                                         y2
                                                                                                                                                                                                                                                                                                                                         y121 -> do {guard (x121 == y121);
                                                                                                                                                                                                                                                                                                                                                     return (y0,
                                                                                                                                                                                                                                                                                                                                                             y1,
                                                                                                                                                                                                                                                                                                                                                             y2)};
                                                                                                                                                                                                                                                                                                                               _ -> mzero};
                                                                                                                                                                                                                                                                                                                      return (x0,
                                                                                                                                                                                                                                                                                                                              x1,
                                                                                                                                                                                                                                                                                                                              x2)}]
solveO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8 = msum [do {let {x0 = Nil};
                                                                                                                                                                                                                                                                                                                     return x0},
                                                                                                                                                                                                                                                                                                                 do {x1 <- solve_atomO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8;
                                                                                                                                                                                                                                                                                                                     x2 <- solveO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8;
                                                                                                                                                                                                                                                                                                                     let {x0 = Cons x1 x2};
                                                                                                                                                                                                                                                                                                                     return x0}]
solve_atomO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8 = msum [do {(x0,
                                                                                                                                                                                                                                                                                                                           x1) <- my_clauseOO gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8;
                                                                                                                                                                                                                                                                                                                          solveI x1 gen_my_clauseIO_x3 gen_my_clauseIO_x6;
                                                                                                                                                                                                                                                                                                                          return x0}]
my_clauseOO gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8 = msum [do {let {x11 = Nil};
                                                                                                                                                                                                                                                                                    (x10,
                                                                                                                                                                                                                                                                                     x6) <- do {x6 <- gen_my_clauseOO_x6;
                                                                                                                                                                                                                                                                                                return (x6,
                                                                                                                                                                                                                                                                                                        x6)};
                                                                                                                                                                                                                                                                                    (x12,
                                                                                                                                                                                                                                                                                     x7) <- do {x7 <- gen_my_clauseOO_x7;
                                                                                                                                                                                                                                                                                                return (x7,
                                                                                                                                                                                                                                                                                                        x7)};
                                                                                                                                                                                                                                                                                    (x2,
                                                                                                                                                                                                                                                                                     x3) <- case x7 of
                                                                                                                                                                                                                                                                                            {App y2
                                                                                                                                                                                                                                                                                                 y3
                                                                                                                                                                                                                                                                                                 y6 -> do {guard (x6 == y6);
                                                                                                                                                                                                                                                                                                           return (y2,
                                                                                                                                                                                                                                                                                                                   y3)};
                                                                                                                                                                                                                                                                                             _ -> mzero};
                                                                                                                                                                                                                                                                                    (x13,
                                                                                                                                                                                                                                                                                     x8) <- do {x8 <- gen_my_clauseOO_x8;
                                                                                                                                                                                                                                                                                                return (x8,
                                                                                                                                                                                                                                                                                                        x8)};
                                                                                                                                                                                                                                                                                    let {x1 = Cons x12 x13};
                                                                                                                                                                                                                                                                                    x9 <- case x8 of
                                                                                                                                                                                                                                                                                          {Cons y9
                                                                                                                                                                                                                                                                                                y11 -> do {guard (x11 == y11);
                                                                                                                                                                                                                                                                                                           return y9};
                                                                                                                                                                                                                                                                                           _ -> mzero};
                                                                                                                                                                                                                                                                                    (x4,
                                                                                                                                                                                                                                                                                     x5) <- case x9 of
                                                                                                                                                                                                                                                                                            {App y10
                                                                                                                                                                                                                                                                                                 y4
                                                                                                                                                                                                                                                                                                 y5 -> do {guard (x10 == y10);
                                                                                                                                                                                                                                                                                                           return (y4,
                                                                                                                                                                                                                                                                                                                   y5)};
                                                                                                                                                                                                                                                                                             _ -> mzero};
                                                                                                                                                                                                                                                                                    let {x0 = DoubleApp x2 x3 x4 x5};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x14 = Nil};
                                                                                                                                                                                                                                                                                    let {x1 = Nil};
                                                                                                                                                                                                                                                                                    let {x16 = x14};
                                                                                                                                                                                                                                                                                    (x15,
                                                                                                                                                                                                                                                                                     x2) <- do {x2 <- gen_my_clauseOO_x2;
                                                                                                                                                                                                                                                                                                return (x2,
                                                                                                                                                                                                                                                                                                        x2)};
                                                                                                                                                                                                                                                                                    let {x17 = x2};
                                                                                                                                                                                                                                                                                    let {x18 = x15};
                                                                                                                                                                                                                                                                                    let {x0 = App x16 x17 x18};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x25 = Nil};
                                                                                                                                                                                                                                                                                    let {x27 = x25};
                                                                                                                                                                                                                                                                                    (x21,
                                                                                                                                                                                                                                                                                     x2) <- do {x2 <- gen_my_clauseOO_x2;
                                                                                                                                                                                                                                                                                                return (x2,
                                                                                                                                                                                                                                                                                                        x2)};
                                                                                                                                                                                                                                                                                    (x22,
                                                                                                                                                                                                                                                                                     x19) <- do {x19 <- gen_my_clauseOO_x19;
                                                                                                                                                                                                                                                                                                 return (x19,
                                                                                                                                                                                                                                                                                                         x19)};
                                                                                                                                                                                                                                                                                    x3 <- case x19 of
                                                                                                                                                                                                                                                                                          {Cons y2
                                                                                                                                                                                                                                                                                                y3 -> do {guard (x2 == y2);
                                                                                                                                                                                                                                                                                                          return y3};
                                                                                                                                                                                                                                                                                           _ -> mzero};
                                                                                                                                                                                                                                                                                    (x23,
                                                                                                                                                                                                                                                                                     x20) <- do {x20 <- gen_my_clauseOO_x20;
                                                                                                                                                                                                                                                                                                 return (x20,
                                                                                                                                                                                                                                                                                                         x20)};
                                                                                                                                                                                                                                                                                    x5 <- case x20 of
                                                                                                                                                                                                                                                                                          {Cons y21
                                                                                                                                                                                                                                                                                                y5 -> do {guard (x21 == y21);
                                                                                                                                                                                                                                                                                                          return y5};
                                                                                                                                                                                                                                                                                           _ -> mzero};
                                                                                                                                                                                                                                                                                    (x26,
                                                                                                                                                                                                                                                                                     x24) <- do {x24 <- gen_my_clauseOO_x24;
                                                                                                                                                                                                                                                                                                 return (x24,
                                                                                                                                                                                                                                                                                                         x24)};
                                                                                                                                                                                                                                                                                    let {x1 = Cons x26 x27};
                                                                                                                                                                                                                                                                                    x4 <- case x24 of
                                                                                                                                                                                                                                                                                          {App y3
                                                                                                                                                                                                                                                                                               y4
                                                                                                                                                                                                                                                                                               y5 -> do {guard (x3 == y3);
                                                                                                                                                                                                                                                                                                         guard (x5 == y5);
                                                                                                                                                                                                                                                                                                         return y4};
                                                                                                                                                                                                                                                                                           _ -> mzero};
                                                                                                                                                                                                                                                                                    let {x0 = App x22 x4 x23};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x28 = Nil};
                                                                                                                                                                                                                                                                                    let {x30 = x28};
                                                                                                                                                                                                                                                                                    (x29,
                                                                                                                                                                                                                                                                                     x0) <- do {x0 <- gen_my_clauseOO_x0;
                                                                                                                                                                                                                                                                                                return (x0,
                                                                                                                                                                                                                                                                                                        x0)};
                                                                                                                                                                                                                                                                                    let {x1 = Cons x29 x30};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x31 = Nil};
                                                                                                                                                                                                                                                                                    let {x1 = Nil};
                                                                                                                                                                                                                                                                                    let {x32 = x31};
                                                                                                                                                                                                                                                                                    let {x0 = Solve2 x32};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x38 = Nil};
                                                                                                                                                                                                                                                                                    (x34,
                                                                                                                                                                                                                                                                                     x33) <- do {x33 <- gen_my_clauseOO_x33;
                                                                                                                                                                                                                                                                                                 return (x33,
                                                                                                                                                                                                                                                                                                         x33)};
                                                                                                                                                                                                                                                                                    let {x0 = Solve2 x34};
                                                                                                                                                                                                                                                                                    (x2,
                                                                                                                                                                                                                                                                                     x3) <- case x33 of
                                                                                                                                                                                                                                                                                            {Cons y2
                                                                                                                                                                                                                                                                                                  y3 -> return (y2,
                                                                                                                                                                                                                                                                                                                y3);
                                                                                                                                                                                                                                                                                             _ -> mzero};
                                                                                                                                                                                                                                                                                    let {x35 = Solve_atom2 x2};
                                                                                                                                                                                                                                                                                    let {x37 = Solve2 x3};
                                                                                                                                                                                                                                                                                    let {x36 = Cons x37 x38};
                                                                                                                                                                                                                                                                                    let {x39 = x35};
                                                                                                                                                                                                                                                                                    let {x40 = x36};
                                                                                                                                                                                                                                                                                    let {x1 = Cons x39 x40};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x45 = Nil};
                                                                                                                                                                                                                                                                                    (x44,
                                                                                                                                                                                                                                                                                     x3) <- do {x3 <- gen_my_clauseOO_x3;
                                                                                                                                                                                                                                                                                                return (x3,
                                                                                                                                                                                                                                                                                                        x3)};
                                                                                                                                                                                                                                                                                    let {x43 = Solve2 x44};
                                                                                                                                                                                                                                                                                    let {x42 = Cons x43 x45};
                                                                                                                                                                                                                                                                                    let {x47 = x42};
                                                                                                                                                                                                                                                                                    (x46,
                                                                                                                                                                                                                                                                                     x41) <- do {x41 <- gen_my_clauseOO_x41;
                                                                                                                                                                                                                                                                                                 return (x41,
                                                                                                                                                                                                                                                                                                         x41)};
                                                                                                                                                                                                                                                                                    let {x1 = Cons x46 x47};
                                                                                                                                                                                                                                                                                    x2 <- case x41 of
                                                                                                                                                                                                                                                                                          {My_clause2 y2
                                                                                                                                                                                                                                                                                                      y3 -> do {guard (x3 == y3);
                                                                                                                                                                                                                                                                                                                return y2};
                                                                                                                                                                                                                                                                                           _ -> mzero};
                                                                                                                                                                                                                                                                                    let {x0 = Solve_atom2 x2};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x49 = Nil};
                                                                                                                                                                                                                                                                                    let {x51 = Nil};
                                                                                                                                                                                                                                                                                    let {x1 = Nil};
                                                                                                                                                                                                                                                                                    let {x53 = x51};
                                                                                                                                                                                                                                                                                    (x50,
                                                                                                                                                                                                                                                                                     x2) <- do {x2 <- gen_my_clauseOO_x2;
                                                                                                                                                                                                                                                                                                return (x2,
                                                                                                                                                                                                                                                                                                        x2)};
                                                                                                                                                                                                                                                                                    let {x48 = App x49 x2 x50};
                                                                                                                                                                                                                                                                                    let {x52 = x48};
                                                                                                                                                                                                                                                                                    let {x0 = My_clause2 x52 x53};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)},
                                                                                                                                                                                                                                                                                do {let {x63 = Nil};
                                                                                                                                                                                                                                                                                    let {x1 = Nil};
                                                                                                                                                                                                                                                                                    (x57,
                                                                                                                                                                                                                                                                                     x2) <- do {x2 <- gen_my_clauseOO_x2;
                                                                                                                                                                                                                                                                                                return (x2,
                                                                                                                                                                                                                                                                                                        x2)};
                                                                                                                                                                                                                                                                                    (x60,
                                                                                                                                                                                                                                                                                     x3) <- do {x3 <- gen_my_clauseOO_x3;
                                                                                                                                                                                                                                                                                                return (x3,
                                                                                                                                                                                                                                                                                                        x3)};
                                                                                                                                                                                                                                                                                    let {x55 = Cons x2 x3};
                                                                                                                                                                                                                                                                                    (x61,
                                                                                                                                                                                                                                                                                     x4) <- do {x4 <- gen_my_clauseOO_x4;
                                                                                                                                                                                                                                                                                                return (x4,
                                                                                                                                                                                                                                                                                                        x4)};
                                                                                                                                                                                                                                                                                    (x62,
                                                                                                                                                                                                                                                                                     x5) <- do {x5 <- gen_my_clauseOO_x5;
                                                                                                                                                                                                                                                                                                return (x5,
                                                                                                                                                                                                                                                                                                        x5)};
                                                                                                                                                                                                                                                                                    let {x56 = Cons x57 x5};
                                                                                                                                                                                                                                                                                    let {x54 = App x55 x4 x56};
                                                                                                                                                                                                                                                                                    let {x59 = App x60 x61 x62};
                                                                                                                                                                                                                                                                                    let {x58 = Cons x59 x63};
                                                                                                                                                                                                                                                                                    let {x64 = x54};
                                                                                                                                                                                                                                                                                    let {x65 = x58};
                                                                                                                                                                                                                                                                                    let {x0 = My_clause2 x64 x65};
                                                                                                                                                                                                                                                                                    return (x0,
                                                                                                                                                                                                                                                                                            x1)}]
solveI x0 gen_my_clauseIO_x3 gen_my_clauseIO_x6 = msum [do {guard (x0 == Nil);
                                                            return ()},
                                                        do {(x1, x2) <- case x0 of
                                                                        {Cons y1 y2 -> return (y1,
                                                                                               y2);
                                                                         _ -> mzero};
                                                            solve_atomI x1 gen_my_clauseIO_x3 gen_my_clauseIO_x6;
                                                            solveI x2 gen_my_clauseIO_x3 gen_my_clauseIO_x6;
                                                            return ()}]
solve_atomI x0 gen_my_clauseIO_x3 gen_my_clauseIO_x6 = msum [do {x1 <- my_clauseIO x0 gen_my_clauseIO_x3 gen_my_clauseIO_x6;
                                                                 solveI x1 gen_my_clauseIO_x3 gen_my_clauseIO_x6;
                                                                 return ()}]
my_clauseIO x0 gen_my_clauseIO_x3 gen_my_clauseIO_x6 = msum [do {let {x11 = Nil};
                                                                 (x2, x3, x4, x5) <- case x0 of
                                                                                     {DoubleApp y2
                                                                                                y3
                                                                                                y4
                                                                                                y5 -> return (y2,
                                                                                                              y3,
                                                                                                              y4,
                                                                                                              y5);
                                                                                      _ -> mzero};
                                                                 (x10,
                                                                  x6) <- do {x6 <- gen_my_clauseIO_x6;
                                                                             return (x6, x6)};
                                                                 let {x7 = App x2 x3 x6};
                                                                 let {x9 = App x10 x4 x5};
                                                                 let {x8 = Cons x9 x11};
                                                                 let {x12 = x7};
                                                                 let {x13 = x8};
                                                                 let {x1 = Cons x12 x13};
                                                                 return x1},
                                                             do {let {x14 = Nil};
                                                                 let {x1 = Nil};
                                                                 (x16, x17, x18) <- case x0 of
                                                                                    {App y16
                                                                                         y17
                                                                                         y18 -> return (y16,
                                                                                                        y17,
                                                                                                        y18);
                                                                                     _ -> mzero};
                                                                 guard (x16 == x14);
                                                                 let {x2 = x17};
                                                                 let {x15 = x2};
                                                                 guard (x18 == x15);
                                                                 return x1},
                                                             do {let {x25 = Nil};
                                                                 (x22, x4, x23) <- case x0 of
                                                                                   {App y22
                                                                                        y4
                                                                                        y23 -> return (y22,
                                                                                                       y4,
                                                                                                       y23);
                                                                                    _ -> mzero};
                                                                 let {x19 = x22};
                                                                 (x2, x3) <- case x19 of
                                                                             {Cons y2
                                                                                   y3 -> return (y2,
                                                                                                 y3);
                                                                              _ -> mzero};
                                                                 let {x21 = x2};
                                                                 let {x20 = x23};
                                                                 x5 <- case x20 of
                                                                       {Cons y21
                                                                             y5 -> do {guard (x21 == y21);
                                                                                       return y5};
                                                                        _ -> mzero};
                                                                 let {x24 = App x3 x4 x5};
                                                                 let {x26 = x24};
                                                                 let {x27 = x25};
                                                                 let {x1 = Cons x26 x27};
                                                                 return x1},
                                                             do {let {x28 = Nil};
                                                                 let {x29 = x0};
                                                                 let {x30 = x28};
                                                                 let {x1 = Cons x29 x30};
                                                                 return x1},
                                                             do {let {x31 = Nil};
                                                                 let {x1 = Nil};
                                                                 x32 <- case x0 of
                                                                        {Solve2 y32 -> return y32;
                                                                         _ -> mzero};
                                                                 guard (x32 == x31);
                                                                 return x1},
                                                             do {let {x38 = Nil};
                                                                 x34 <- case x0 of
                                                                        {Solve2 y34 -> return y34;
                                                                         _ -> mzero};
                                                                 let {x33 = x34};
                                                                 (x2, x3) <- case x33 of
                                                                             {Cons y2
                                                                                   y3 -> return (y2,
                                                                                                 y3);
                                                                              _ -> mzero};
                                                                 let {x35 = Solve_atom2 x2};
                                                                 let {x37 = Solve2 x3};
                                                                 let {x36 = Cons x37 x38};
                                                                 let {x39 = x35};
                                                                 let {x40 = x36};
                                                                 let {x1 = Cons x39 x40};
                                                                 return x1},
                                                             do {let {x45 = Nil};
                                                                 x2 <- case x0 of
                                                                       {Solve_atom2 y2 -> return y2;
                                                                        _ -> mzero};
                                                                 (x44,
                                                                  x3) <- do {x3 <- gen_my_clauseIO_x3;
                                                                             return (x3, x3)};
                                                                 let {x41 = My_clause2 x2 x3};
                                                                 let {x43 = Solve2 x44};
                                                                 let {x42 = Cons x43 x45};
                                                                 let {x46 = x41};
                                                                 let {x47 = x42};
                                                                 let {x1 = Cons x46 x47};
                                                                 return x1},
                                                             do {let {x49 = Nil};
                                                                 let {x51 = Nil};
                                                                 let {x1 = Nil};
                                                                 (x52, x53) <- case x0 of
                                                                               {My_clause2 y52
                                                                                           y53 -> return (y52,
                                                                                                          y53);
                                                                                _ -> mzero};
                                                                 guard (x53 == x51);
                                                                 let {x48 = x52};
                                                                 (x2, x50) <- case x48 of
                                                                              {App y49
                                                                                   y2
                                                                                   y50 -> do {guard (x49 == y49);
                                                                                              return (y2,
                                                                                                      y50)};
                                                                               _ -> mzero};
                                                                 guard (x50 == x2);
                                                                 return x1},
                                                             do {let {x63 = Nil};
                                                                 let {x1 = Nil};
                                                                 (x64, x65) <- case x0 of
                                                                               {My_clause2 y64
                                                                                           y65 -> return (y64,
                                                                                                          y65);
                                                                                _ -> mzero};
                                                                 let {x54 = x64};
                                                                 (x55, x4, x56) <- case x54 of
                                                                                   {App y55
                                                                                        y4
                                                                                        y56 -> return (y55,
                                                                                                       y4,
                                                                                                       y56);
                                                                                    _ -> mzero};
                                                                 (x2, x3) <- case x55 of
                                                                             {Cons y2
                                                                                   y3 -> return (y2,
                                                                                                 y3);
                                                                              _ -> mzero};
                                                                 (x57, x5) <- case x56 of
                                                                              {Cons y57
                                                                                    y5 -> return (y57,
                                                                                                  y5);
                                                                               _ -> mzero};
                                                                 guard (x57 == x2);
                                                                 let {x60 = x3};
                                                                 let {x61 = x4};
                                                                 let {x62 = x5};
                                                                 let {x59 = App x60 x61 x62};
                                                                 let {x58 = Cons x59 x63};
                                                                 guard (x65 == x58);
                                                                 return x1}]
help gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8 = helpOOO gen_my_clauseIO_x3 gen_my_clauseIO_x6 gen_my_clauseOO_x0 gen_my_clauseOO_x19 gen_my_clauseOO_x2 gen_my_clauseOO_x20 gen_my_clauseOO_x24 gen_my_clauseOO_x3 gen_my_clauseOO_x33 gen_my_clauseOO_x4 gen_my_clauseOO_x41 gen_my_clauseOO_x5 gen_my_clauseOO_x6 gen_my_clauseOO_x7 gen_my_clauseOO_x8