evalo y0 = (evaloEvalo y0 | __evaloEvalo y0 | ___evaloEvalo y0);

evaloEvalo y1 = (fresh q1, q2 in ((y1 == Lit (Trueo) | (y1 == Neg (q1) & _evaloEvalo q1) | (y1 == Disj (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y1 == Disj (q1) (q2) & ___evaloEvalo q1 & evaloEvalo q2) | (y1 == Disj (q1) (q2) & evaloEvalo q1 & ___evaloEvalo q2) | (y1 == Disj (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y1 == Disj (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y1 == Disj (q1) (q2) & __evaloEvalo q1 & ___evaloEvalo q2) | (y1 == Disj (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y1 == Disj (q1) (q2) & ___evaloEvalo q1 & __evaloEvalo q2) | (y1 == Disj (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y1 == Conj (q1) (q2) & evaloEvalo q1 & evaloEvalo q2) | (y1 == Impl (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y1 == Impl (q1) (q2) & _evaloEvalo q1 & ___evaloEvalo q2) | (y1 == Impl (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y1 == Impl (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y1 == Impl (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y1 == Impl (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y1 == Impl (q1) (q2) & ___evaloEvalo q1 & evaloEvalo q2) | (y1 == Impl (q1) (q2) & ___evaloEvalo q1 & ___evaloEvalo q2) | (y1 == Impl (q1) (q2) & evaloEvalo q1 & evaloEvalo q2))));

_evaloEvalo y2 = (fresh q1, q2 in ((y2 == Lit (Falso) | (y2 == Neg (q1) & evaloEvalo q1) | (y2 == Disj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & evaloEvalo q2) | (y2 == Conj (q1) (q2) & __evaloEvalo q1 & ___evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & ___evaloEvalo q2) | (y2 == Conj (q1) (q2) & ___evaloEvalo q1 & __evaloEvalo q2) | (y2 == Conj (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2) | (y2 == Conj (q1) (q2) & ___evaloEvalo q1 & _evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y2 == Conj (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y2 == Conj (q1) (q2) & _evaloEvalo q1 & _evaloEvalo q2) | (y2 == Impl (q1) (q2) & evaloEvalo q1 & _evaloEvalo q2))));

__evaloEvalo y3 = (fresh q1, q2 in (((y3 == Neg (q1) & ___evaloEvalo q1) | (y3 == Disj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y3 == Disj (q1) (q2) & _evaloEvalo q1 & __evaloEvalo q2) | (y3 == Disj (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y3 == Conj (q1) (q2) & __evaloEvalo q1 & evaloEvalo q2) | (y3 == Conj (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2) | (y3 == Conj (q1) (q2) & __evaloEvalo q1 & __evaloEvalo q2) | (y3 == Impl (q1) (q2) & ___evaloEvalo q1 & __evaloEvalo q2) | (y3 == Impl (q1) (q2) & ___evaloEvalo q1 & _evaloEvalo q2) | (y3 == Impl (q1) (q2) & evaloEvalo q1 & __evaloEvalo q2))));

___evaloEvalo y4 = (fresh q1, q2 in (((y4 == Neg (q1) & __evaloEvalo q1) | (y4 == Disj (q1) (q2) & ___evaloEvalo q1 & ___evaloEvalo q2) | (y4 == Disj (q1) (q2) & _evaloEvalo q1 & ___evaloEvalo q2) | (y4 == Disj (q1) (q2) & ___evaloEvalo q1 & _evaloEvalo q2) | (y4 == Conj (q1) (q2) & ___evaloEvalo q1 & evaloEvalo q2) | (y4 == Conj (q1) (q2) & evaloEvalo q1 & ___evaloEvalo q2) | (y4 == Conj (q1) (q2) & ___evaloEvalo q1 & ___evaloEvalo q2) | (y4 == Impl (q1) (q2) & __evaloEvalo q1 & ___evaloEvalo q2) | (y4 == Impl (q1) (q2) & __evaloEvalo q1 & _evaloEvalo q2) | (y4 == Impl (q1) (q2) & evaloEvalo q1 & ___evaloEvalo q2))));


? evalo x0