eval(St, var(X), U) :- elem(X, St, U).
eval(St, conj(X,Y), U) :- and(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, disj(X,Y), U) :- or(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, not(X), U) :- eval(St, X, neg(U)).

elem(zero, [H|T], H).
elem(succ(N), [H|T], V) :- elem(N, T, V).

nand(false, false, true).
nand(false, true,  true).
nand(true,  false, true).
nand(true,  true,  false).

neg(X, R) :- nand(X, X, R).

or(X, Y, R) :- nand(X, X, Xx), nand(Y, Y, Yy), nand(Xx, Yy, R).

and(X, Y, R) :- nand(X, Y, Xy), nand(Xy, Xy, R).

/* Default conjunctive */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 500 ms */
/* Unfolding time: 340 ms */
/* Post-Processing time: 500 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
nand_conj__2(A,B) :- nand(A,A,C1), nand(B,C1,true).
eval_conj__3(A,B,C,D,E) :- eval(A,B,C), eval(A,D,E).
eval__4(A,B,C) :- eval(A,B,neg(C)).
elem__5(A,B,C,D) :- elem(A,[B|C],D).
eval__6(A,B,C) :- eval(A,B,C).
eval_conj__7(A,B,C,D,E) :- eval(A,B,neg(C)), eval(A,D,E).
eval__8(A,B,C,D) :- eval([A|B],C,D).
nand_conj__9(A,B,C,D,E) :- nand(F1,G1,H1), nand(H1,H1,A), eval([B|C],D,F1), eval([B|C],E,G1).
nand__10(A,B) :- nand(A,A,B).
nand_conj__11(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand__12(A,B) :- nand(A,true,B).
nand__13(A) :- nand(A,false,true).
nand_conj__14(A,B,C,D) :- nand(E1,F1,G1), nand(G1,G1,A), eval(B,C,E1), eval(B,D,F1).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__5(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__6(A,B,true),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  nand__10(D,E),
  nand_conj__2(F,E),
  eval_conj__3(A,B,D,C,F).
eval__1(A,not(B)) :-
  eval__4(A,B,true).
nand_conj__2(false,false).
nand_conj__2(true,A) :-
  nand__13(A).
eval_conj__3([A|B],var(C),D,E,F) :-
  elem__5(C,A,B,D),
  eval__8(A,B,E,F).
eval_conj__3(A,conj(B,C),D,E,F) :-
  nand_conj__14(D,A,B,C),
  eval__6(A,E,F).
eval_conj__3(A,disj(B,C),D,E,F) :-
  nand__10(G,H),
  nand_conj__11(I,H,D),
  eval_conj__3(A,B,G,C,I),
  eval__6(A,E,F).
eval_conj__3(A,not(B),C,D,E) :-
  eval_conj__7(A,B,C,D,E).
eval__4([A|B],var(C),D) :-
  elem__5(C,A,B,neg(D)).
eval__4(A,not(B),C) :-
  eval__4(A,B,neg(C)).
elem__5(zero,A,B,A).
elem__5(succ(A),B,[C|D],E) :-
  elem__5(A,C,D,E).
eval__6([A|B],var(C),D) :-
  elem__5(C,A,B,D).
eval__6(A,conj(B,C),D) :-
  nand_conj__14(D,A,B,C).
eval__6(A,disj(B,C),D) :-
  nand__10(E,F),
  nand_conj__11(G,F,D),
  eval_conj__3(A,B,E,C,G).
eval__6(A,not(B),C) :-
  eval__4(A,B,C).
eval_conj__7([A|B],var(C),D,E,F) :-
  elem__5(C,A,B,neg(D)),
  eval__8(A,B,E,F).
eval_conj__7(A,not(B),C,D,E) :-
  eval_conj__7(A,B,neg(C),D,E).
eval__8(A,B,var(C),D) :-
  elem__5(C,A,B,D).
eval__8(A,B,conj(C,D),E) :-
  nand_conj__9(E,A,B,C,D).
eval__8(A,B,disj(C,D),E) :-
  nand__10(F,G),
  nand_conj__11(H,G,E),
  eval__8(A,B,C,F),
  eval__8(A,B,D,H).
eval__8(A,B,not(C),D) :-
  eval__4([A|B],C,D).
nand_conj__9(false,A,B,C,D) :-
  eval__8(A,B,C,false),
  eval__8(A,B,D,false).
nand_conj__9(false,A,B,C,D) :-
  eval__8(A,B,C,false),
  eval__8(A,B,D,true).
nand_conj__9(false,A,B,C,D) :-
  eval__8(A,B,C,true),
  eval__8(A,B,D,false).
nand_conj__9(true,A,B,C,D) :-
  eval__8(A,B,C,true),
  eval__8(A,B,D,true).
nand__10(false,true).
nand__10(true,false).
nand_conj__11(false,A,B) :-
  nand__12(A,B).
nand_conj__11(true,A,true) :-
  nand__13(A).
nand__12(false,true).
nand__12(true,false).
nand__13(false).
nand__13(true).
nand_conj__14(false,A,B,C) :-
  eval__6(A,B,false),
  eval__6(A,C,false).
nand_conj__14(false,A,B,C) :-
  eval__6(A,B,false),
  eval__1(A,C).
nand_conj__14(false,A,B,C) :-
  eval__6(A,B,true),
  eval__6(A,C,false).
nand_conj__14(true,A,B,C) :-
  eval__6(A,B,true),
  eval__1(A,C).

/* Conjunctive fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:a Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 240 ms */
/* Unfolding time: 180 ms */
/* Post-Processing time: 240 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval_conj__2(A,B,C,D,E) :- eval(A,B,C), eval(A,D,E).
eval__3(A,B,C) :- eval(A,B,neg(C)).
elem__4(A,B,C,D) :- elem(A,[B|C],D).
eval__5(A,B,C) :- eval(A,B,C).
nand_conj__6(A,B,C,D) :- nand(E1,F1,G1), nand(G1,G1,A), eval(B,C,E1), eval(B,D,F1).
nand__7(A,B) :- nand(A,A,B).
nand_conj__8(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand__9(A,B) :- nand(A,true,B).
nand__10(A) :- nand(A,false,true).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__4(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval_conj__2(A,B,true,C,true).
eval__1(A,disj(B,C)) :-
  nand__7(D,E),
  nand_conj__8(F,E,true),
  eval_conj__2(A,B,D,C,F).
eval__1(A,not(B)) :-
  eval__3(A,B,true).
eval_conj__2([A|B],var(C),D,E,F) :-
  elem__4(C,A,B,D),
  eval__5([A|B],E,F).
eval_conj__2(A,conj(B,C),D,E,F) :-
  nand_conj__6(D,A,B,C),
  eval__5(A,E,F).
eval_conj__2(A,disj(B,C),D,E,F) :-
  nand__7(G,H),
  nand_conj__8(I,H,D),
  eval_conj__2(A,B,G,C,I),
  eval__5(A,E,F).
eval_conj__2(A,not(B),C,D,E) :-
  eval_conj__2(A,B,neg(C),D,E).
eval__3([A|B],var(C),D) :-
  elem__4(C,A,B,neg(D)).
eval__3(A,not(B),C) :-
  eval__3(A,B,neg(C)).
elem__4(zero,A,B,A).
elem__4(succ(A),B,[C|D],E) :-
  elem__4(A,C,D,E).
eval__5([A|B],var(C),D) :-
  elem__4(C,A,B,D).
eval__5(A,conj(B,C),D) :-
  nand_conj__6(D,A,B,C).
eval__5(A,disj(B,C),D) :-
  nand__7(E,F),
  nand_conj__8(G,F,D),
  eval_conj__2(A,B,E,C,G).
eval__5(A,not(B),C) :-
  eval__3(A,B,C).
nand_conj__6(false,A,B,C) :-
  eval_conj__2(A,B,false,C,false).
nand_conj__6(false,A,B,C) :-
  eval_conj__2(A,B,false,C,true).
nand_conj__6(false,A,B,C) :-
  eval_conj__2(A,B,true,C,false).
nand_conj__6(true,A,B,C) :-
  eval_conj__2(A,B,true,C,true).
nand__7(false,true).
nand__7(true,false).
nand_conj__8(false,A,B) :-
  nand__9(A,B).
nand_conj__8(true,A,true) :-
  nand__10(A).
nand__9(false,true).
nand__9(true,false).
nand__10(false).
nand__10(true).

/* classic */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:x Sel:x Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 160 ms */
/* Unfolding time: 120 ms */
/* Post-Processing time: 160 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval(A,B,false).
eval__3(A,B,C) :- eval(A,B,neg(C)).
elem__4(A,B,C,D) :- elem(A,[B|C],D).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__4(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,not(B)) :-
  eval__3(A,B,true).
eval__2([A|B],var(C)) :-
  elem__4(C,A,B,false).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__2(A,conj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,not(B)) :-
  eval__3(A,B,false).
eval__3([A|B],var(C),D) :-
  elem__4(C,A,B,neg(D)).
eval__3(A,not(B),C) :-
  eval__3(A,B,neg(C)).
elem__4(zero,A,B,A).
elem__4(succ(A),B,[C|D],E) :-
  elem__4(A,C,D,E).

/* Mixtus style */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:x Sel:x Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 280 ms */
/* Unfolding time: 180 ms */
/* Post-Processing time: 280 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B,C) :- eval(A,B,neg(C)).
elem__3(A,B,C,D) :- elem(A,[B|C],D).
eval__4(A,B) :- eval(A,B,false).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__3(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__4(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__4(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,not(B)) :-
  eval__2(A,B,true).
eval__2([A|B],var(C),D) :-
  elem__3(C,A,B,neg(D)).
eval__2(A,not(B),C) :-
  eval__2(A,B,neg(C)).
elem__3(zero,A,B,A).
elem__3(succ(A),B,[C|D],E) :-
  elem__3(A,C,D,E).
eval__4([A|B],var(C)) :-
  elem__3(C,A,B,false).
eval__4(A,conj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,conj(B,C)) :-
  eval__4(A,B),
  eval__1(A,C).
eval__4(A,conj(B,C)) :-
  eval__1(A,B),
  eval__4(A,C).
eval__4(A,disj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,not(B)) :-
  eval__2(A,B,false).

/* Classic fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:n Sel:o Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 60 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
and__3(A,B,C) :- and(A,B,C).
or__4(A,B,C) :- or(A,B,C).
nand__5(A,B) :- nand(true,A,B).
nand__6(A,B) :- nand(A,A,B).
nand__7(A) :- nand(false,A,true).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__1(A,conj(B,C),D) :-
  and__3(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,disj(B,C),D) :-
  or__4(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
and__3(false,false,false).
and__3(false,true,false).
and__3(true,false,false).
and__3(true,true,true).
or__4(false,A,B) :-
  nand__6(A,C),
  nand__5(C,B).
or__4(true,A,true) :-
  nand__6(A,B),
  nand__7(B).
nand__5(false,true).
nand__5(true,false).
nand__6(false,true).
nand__6(true,false).
nand__7(false).
nand__7(true).

/* minimal */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:m InstCheck:a Msv:n NgSlv:n Part:s Prun:n Sel:s Whstl:m Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C) :- elem(A,B,C).
nand__3(A,B,C) :- nand(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1(A,var(B),C) :-
  elem__2(B,A,C).
eval__1(A,conj(B,C),D) :-
  nand__3(E,F,G),
  nand__3(G,G,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,disj(B,C),D) :-
  nand__3(E,E,F),
  nand__3(G,G,H),
  nand__3(F,H,D),
  eval__1(A,B,E),
  eval__1(A,C,G).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
nand__3(false,false,true).
nand__3(false,true,true).
nand__3(true,false,true).
nand__3(true,true,false).

/* Termination */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:n NgSlv:g Part:s Prun:n Sel:j Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:no ParAbs:yes Msvp:no Rrc:no */
/* Transformation time: 340 ms */
/* Unfolding time: 240 ms */
/* Post-Processing time: 340 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval([false|A],B,true).
eval__3(A,B) :- eval(A,B,false).
eval__4(A,B,C) :- eval(A,B,neg(C)).
eval__5(A,B) :- eval([true|A],B,false).
eval__6(A,B,C) :- eval([A|B],C,false).
eval__7(A,B,C) :- eval(A,B,neg(C)).
eval__8(A,B,C) :- eval([A|B],C,true).
eval__9(A,B,C,D) :- eval([A|B],C,neg(D)).
eval__10(A,B) :- eval([true|A],B,true).
eval__11(A,B,C) :- eval([D1|A],B,neg(C)).
elem__12(A,B,C) :- elem(A,[D1|B],C).
elem__13(A,B,C) :- elem(A,B,C).
eval__14(A,B) :- eval([false|A],B,false).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([true|A],var(zero)).
eval__1([A|B],var(succ(C))) :-
  elem__13(C,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1([false|A],disj(var(zero),B)) :-
  eval__2(A,B).
eval__1([A|B],disj(var(succ(C)),D)) :-
  elem__13(C,B,false),
  eval__8(A,B,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(not(B),C)) :-
  eval__7(A,B,false),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__3(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,not(B)) :-
  eval__4(A,B,true).
eval__2(A,var(B)) :-
  elem__12(B,A,true).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__14(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__14(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,not(B)) :-
  eval__11(A,B,true).
eval__3([false|A],var(zero)).
eval__3([A|B],var(succ(C))) :-
  elem__13(C,B,false).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__1(A,C).
eval__3([true|A],conj(var(zero),B)) :-
  eval__5(A,B).
eval__3([A|B],conj(var(succ(C)),D)) :-
  elem__13(C,B,true),
  eval__6(A,B,D).
eval__3(A,conj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(not(B),C)) :-
  eval__4(A,B,true),
  eval__3(A,C).
eval__3(A,disj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,not(B)) :-
  eval__7(A,B,false).
eval__4([neg(A)|B],var(zero),A).
eval__4([A|B],var(succ(C)),D) :-
  elem__13(C,B,neg(D)).
eval__4(A,not(B),C) :-
  eval__4(A,B,neg(C)).
eval__5(A,var(B)) :-
  elem__12(B,A,false).
eval__5(A,conj(B,C)) :-
  eval__5(A,B),
  eval__5(A,C).
eval__5(A,conj(B,C)) :-
  eval__5(A,B),
  eval__10(A,C).
eval__5(A,conj(B,C)) :-
  eval__10(A,B),
  eval__5(A,C).
eval__5(A,disj(B,C)) :-
  eval__5(A,B),
  eval__5(A,C).
eval__5(A,not(B)) :-
  eval__11(A,B,false).
eval__6(false,A,var(zero)).
eval__6(A,[false|B],var(succ(zero))).
eval__6(A,[B|C],var(succ(succ(D)))) :-
  elem__13(D,C,false).
eval__6(A,B,conj(C,D)) :-
  eval__6(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,conj(C,D)) :-
  eval__6(A,B,C),
  eval__8(A,B,D).
eval__6(A,B,conj(C,D)) :-
  eval__8(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,disj(C,D)) :-
  eval__6(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,not(C)) :-
  eval__9(A,B,C,false).
eval__7(A,var(B),C) :-
  elem__13(B,A,neg(C)).
eval__7(A,not(B),C) :-
  eval__4(A,B,neg(C)).
eval__8(true,A,var(zero)).
eval__8(A,[true|B],var(succ(zero))).
eval__8(A,[B|C],var(succ(succ(D)))) :-
  elem__13(D,C,true).
eval__8(A,B,conj(C,D)) :-
  eval__8(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__6(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__8(A,B,C),
  eval__6(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__8(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,not(C)) :-
  eval__9(A,B,C,true).
eval__9(A,B,var(C),D) :-
  elem__13(C,[A|B],neg(D)).
eval__9(A,B,not(C),D) :-
  eval__9(A,B,C,neg(D)).
eval__10(A,var(B)) :-
  elem__13(B,[true|A],true).
eval__10(A,conj(B,C)) :-
  eval__10(A,B),
  eval__10(A,C).
eval__10(A,disj(B,C)) :-
  eval__5(A,B),
  eval__10(A,C).
eval__10(A,disj(B,C)) :-
  eval__10(A,B),
  eval__5(A,C).
eval__10(A,disj(B,C)) :-
  eval__10(A,B),
  eval__10(A,C).
eval__10(A,not(B)) :-
  eval__11(A,B,true).
eval__11(A,var(B),C) :-
  elem__12(B,A,neg(C)).
eval__11(A,not(B),C) :-
  eval__11(A,B,neg(C)).
elem__12(succ(A),B,C) :-
  elem__13(A,B,C).
elem__13(zero,[A|B],A).
elem__13(succ(A),[B|C],D) :-
  elem__13(A,C,D).
eval__14(A,var(B)) :-
  elem__13(B,[false|A],false).
eval__14(A,conj(B,C)) :-
  eval__14(A,B),
  eval__14(A,C).
eval__14(A,conj(B,C)) :-
  eval__14(A,B),
  eval__2(A,C).
eval__14(A,conj(B,C)) :-
  eval__2(A,B),
  eval__14(A,C).
eval__14(A,disj(B,C)) :-
  eval__14(A,B),
  eval__14(A,C).
eval__14(A,not(B)) :-
  eval__11(A,B,false).