eval(St, var(X), U) :- elem(X, St, U).
eval(St, conj(X,Y), U)  :- eval(St, X, V), eval(St, Y, W), and(V, W, U).
eval(St, disj(X,Y), U)  :- eval(St, X, V), eval(St, Y, W), or(V, W, U).
eval(St, not(X), U) :- eval(St, X, V), neg(U, V).

elem(zero, [H|T], H).
elem(succ(N), [H|T], V) :- elem(N, T, V).

nand(false, false, true).
nand(false, true,  true).
nand(true,  false, true).
nand(true,  true,  false).

neg(X, R) :- nand(X, X, R).

or(X, Y, R) :- nand(X, X, Xx), nand(Y, Y, Yy), nand(Xx, Yy, R).

and(X, Y, R) :- nand(X, Y, Xy), nand(Xy, Xy, R).


/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 2480 ms */
/* Unfolding time: 2020 ms */
/* Post-Processing time: 2480 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
eval_conj__3(A,B,C) :- eval(A,B,D1), eval(A,C,E1), nand(D1,D1,F1), nand(E1,E1,G1), nand(F1,G1,true).
eval__4(A,B) :- eval(A,B,false).
eval_conj__5(A,B,C,D,E) :- eval(A,B,C), eval(A,D,F1), nand(E,F1,true).
eval__6(A,B,C) :- eval(A,B,C).
nand__7(A,B,C) :- nand(A,B,C).
nand__8(A,B) :- nand(A,A,B).
nand_conj__9(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand__10(A,B) :- nand(A,true,B).
nand__11(A) :- nand(A,false,true).
nand_conj__12(A,B,C) :- nand(A,B,D1), nand(D1,D1,C).
eval__13(A,B,C,D) :- eval([A|B],C,D).
nand_conj__14(A,B) :- nand(A,A,C1), nand(B,C1,true).
eval_conj__15(A,B,C,D,E) :- eval(A,B,F1), nand(G1,G1,F1), eval(A,C,H1), nand(G1,G1,D), nand(H1,H1,E).
nand__16(A,B) :- nand(A,B,true).
eval_conj__17(A,B,C,D,E) :- eval(A,B,F1), nand(G1,G1,F1), nand(H1,H1,G1), eval(A,C,D), nand(H1,H1,E).
eval_conj__18(A,B,C,D,E) :- eval(A,B,F1), nand(G1,G1,F1), nand(H1,H1,G1), nand(C,C,H1), eval(A,D,E).
eval_conj__19(A,B,C) :- eval(A,B,D1), nand(E1,E1,D1), nand(F1,F1,E1), nand(C,C,F1).
elem_conj__20(A,B,C,D) :- elem(A,[B|C],E1), nand(F1,F1,E1), nand(G1,G1,F1), nand(D,D,G1).
eval_conj__21(A,B,C,D) :- eval(A,B,E1), eval(A,C,F1), nand(E1,F1,G1), nand(G1,G1,H1), nand(D,D,H1).
nand_conj__22(A,B) :- nand(C1,C1,A), nand(B,B,C1).
nand_conj__23(A,B) :- nand(C1,C1,A), nand(D1,D1,C1), nand(B,B,D1).
eval_conj__24(A,B,C,D) :- eval(A,B,E1), nand(C,E1,F1), nand(F1,F1,G1), nand(D,D,G1).
eval_conj__25(A,B,C,D) :- eval(A,B,E1), nand(F1,F1,E1), eval(A,C,G1), nand(F1,G1,H1), nand(H1,H1,D).
eval_conj__26(A,B,C,D) :- eval(A,B,E1), nand(F1,F1,E1), nand(G1,G1,F1), eval(A,C,H1), nand(G1,H1,D).
elem_conj__27(A,B,C,D) :- elem(A,[B|C],E1), nand(F1,F1,E1), nand(D,D,F1).
elem_conj__28(A,B,C,D) :- elem(A,[B|C],E1), nand(D,D,E1).
elem_conj__29(A,B,C,D,E) :- elem(A,[B|C],F1), nand(D,F1,G1), nand(G1,G1,H1), nand(E,E,H1).
eval_conj__30(A,B,C,D,E) :- eval(A,B,F1), eval(A,C,G1), nand(F1,G1,H1), nand(H1,H1,I1), nand(D,I1,E).
nand_conj__31(A,B) :- nand(A,A,C1), nand(B,B,C1).
nand_conj__32(A,B,C) :- nand(A,B,D1), nand(D1,D1,E1), nand(C,C,E1).
eval_conj__33(A,B,C,D) :- eval(A,B,E1), nand(F1,F1,E1), nand(C,F1,G1), nand(G1,G1,D).
elem_conj__34(A,B,C,D,E) :- elem(A,[B|C],F1), nand(G1,G1,F1), nand(D,G1,H1), nand(H1,H1,E).
nand_conj__35(A,B,C) :- nand(D1,D1,A), nand(B,D1,E1), nand(E1,E1,C).
eval_conj__36(A,B,C,D) :- eval(A,B,E1), nand(F1,F1,E1), nand(G1,G1,F1), nand(C,G1,D).
elem_conj__37(A,B,C,D,E) :- elem(A,[B|C],F1), nand(G1,G1,F1), nand(H1,H1,G1), nand(D,H1,E).
nand_conj__38(A,B,C) :- nand(D1,D1,A), nand(B,D1,C).
nand_conj__39(A,B,C) :- nand(D1,D1,A), nand(E1,E1,D1), nand(B,E1,C).
nand_conj__40(A,B) :- nand(A,true,C1), nand(C1,C1,B).
eval_conj__41(A,B,C,D,E) :- eval(A,B,F1), nand(C,F1,G1), nand(G1,G1,H1), nand(D,H1,E).
elem_conj__42(A,B,C,D,E,F) :- elem(A,[B|C],G1), nand(D,G1,H1), nand(H1,H1,I1), nand(E,I1,F).
nand_conj__43(A,B,C,D) :- nand(A,B,E1), nand(E1,E1,F1), nand(C,F1,D).
*/

eval(A,B,true) :-
  eval__1(A,B).

eval__1([A|B],var(C)) :-
  elem__2(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval_conj__3(A,B,C).
eval__1(A,not(B)) :-
  eval__4(A,B).

elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).

eval_conj__3([A|B],var(C),D) :-
  elem__2(C,A,B,E),
  eval__13(A,B,D,F),
  nand__8(E,G),
  nand_conj__14(F,G).
eval_conj__3(A,conj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  nand_conj__12(E,F,G),
  eval__6(A,D,H),
  nand__8(G,I),
  nand_conj__14(H,I).
eval_conj__3(A,disj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  nand__8(E,G),
  nand_conj__9(F,G,H),
  eval__6(A,D,I),
  nand__8(H,J),
  nand_conj__14(I,J).
eval_conj__3(A,not(B),C) :-
  eval_conj__15(A,B,C,D,E),
  nand__16(D,E).
eval__4([A|B],var(C)) :-
  elem__2(C,A,B,false).
eval__4(A,conj(B,C)) :-
  eval_conj__5(A,B,D,C,D).
eval__4(A,disj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,not(B)) :-
  eval__1(A,B).
eval_conj__5([A|B],var(C),D,E,F) :-
  elem__2(C,A,B,D),
  eval__13(A,B,E,G),
  nand__7(F,G,true).
eval_conj__5(A,conj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand_conj__12(G,H,D),
  eval__6(A,E,I),
  nand__7(F,I,true).
eval_conj__5(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,D),
  eval__6(A,E,J),
  nand__7(F,J,true).
eval_conj__5(A,not(B),C,D,E) :-
  eval__6(A,B,F),
  nand__8(C,F),
  eval__6(A,D,G),
  nand__7(E,G,true).
eval__6([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__6(A,conj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  nand_conj__12(E,F,D).
eval__6(A,disj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  nand__8(E,G),
  nand_conj__9(F,G,D).
eval__6(A,not(B),C) :-
  eval__6(A,B,D),
  nand__8(C,D).
nand__7(false,false,true).
nand__7(false,true,true).
nand__7(true,false,true).
nand__7(true,true,false).
nand__8(false,true).
nand__8(true,false).
nand_conj__9(false,A,B) :-
  nand__10(A,B).
nand_conj__9(true,A,true) :-
  nand__11(A).
nand__10(false,true).
nand__10(true,false).
nand__11(false).
nand__11(true).
nand_conj__12(false,false,false).
nand_conj__12(false,true,false).
nand_conj__12(true,false,false).
nand_conj__12(true,true,true).
eval__13(A,B,var(C),D) :-
  elem__2(C,A,B,D).
eval__13(A,B,conj(C,D),E) :-
  eval__13(A,B,C,F),
  eval__13(A,B,D,G),
  nand_conj__12(F,G,E).
eval__13(A,B,disj(C,D),E) :-
  eval__13(A,B,C,F),
  eval__13(A,B,D,G),
  nand__8(F,H),
  nand_conj__9(G,H,E).
eval__13(A,B,not(C),D) :-
  eval__13(A,B,C,E),
  nand__8(D,E).
nand_conj__14(false,false).
nand_conj__14(true,A) :-
  nand__11(A).
eval_conj__15([A|B],var(C),D,E,F) :-
  elem_conj__28(C,A,B,G),
  eval__13(A,B,D,H),
  nand__8(G,E),
  nand__8(H,F).
eval_conj__15(A,conj(B,C),D,E,F) :-
  eval_conj__21(A,B,C,G),
  eval__6(A,D,H),
  nand__8(G,E),
  nand__8(H,F).
eval_conj__15(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,J),
  nand__8(K,J),
  eval__6(A,D,L),
  nand__8(K,E),
  nand__8(L,F).
eval_conj__15(A,not(B),C,D,E) :-
  eval_conj__17(A,B,C,F,D),
  nand__8(F,E).
nand__16(false,false).
nand__16(false,true).
nand__16(true,false).
eval_conj__17([A|B],var(C),D,E,F) :-
  elem_conj__27(C,A,B,G),
  eval__13(A,B,D,E),
  nand__8(G,F).
eval_conj__17(A,conj(B,C),D,E,F) :-
  eval_conj__21(A,B,C,G),
  nand__8(H,G),
  eval__6(A,D,E),
  nand__8(H,F).
eval_conj__17(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,J),
  nand_conj__22(J,K),
  eval__6(A,D,E),
  nand__8(K,F).
eval_conj__17(A,not(B),C,D,E) :-
  eval_conj__18(A,B,F,C,D),
  nand__8(F,E).
eval_conj__18([A|B],var(C),D,E,F) :-
  elem_conj__20(C,A,B,D),
  eval__13(A,B,E,F).
eval_conj__18(A,conj(B,C),D,E,F) :-
  eval_conj__21(A,B,C,G),
  nand_conj__22(G,D),
  eval__6(A,E,F).
eval_conj__18(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,J),
  nand_conj__23(J,D),
  eval__6(A,E,F).
eval_conj__18(A,not(B),C,D,E) :-
  eval_conj__19(A,B,F),
  nand__8(C,F),
  eval__6(A,D,E).
eval_conj__19([A|B],var(C),D) :-
  elem_conj__20(C,A,B,D).
eval_conj__19(A,conj(B,C),D) :-
  eval_conj__21(A,B,C,E),
  nand_conj__22(E,D).
eval_conj__19(A,disj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  nand__8(E,G),
  nand_conj__9(F,G,H),
  nand_conj__23(H,D).
eval_conj__19(A,not(B),C) :-
  eval_conj__19(A,B,D),
  nand__8(C,D).
elem_conj__20(zero,A,B,C) :-
  nand_conj__23(A,C).
elem_conj__20(succ(A),B,[C|D],E) :-
  elem_conj__20(A,C,D,E).
eval_conj__21([A|B],var(C),D,E) :-
  elem__2(C,A,B,F),
  eval__13(A,B,D,G),
  nand_conj__32(F,G,E).
eval_conj__21(A,conj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand_conj__12(F,G,H),
  eval_conj__24(A,D,H,E).
eval_conj__21(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  eval_conj__24(A,D,I,E).
eval_conj__21(A,not(B),C,D) :-
  eval_conj__25(A,B,C,E),
  nand__8(D,E).
nand_conj__22(true,true).
nand_conj__22(false,false).
nand_conj__23(true,false).
nand_conj__23(false,true).
eval_conj__24([A|B],var(C),D,E) :-
  elem_conj__29(C,A,B,D,E).
eval_conj__24(A,conj(B,C),D,E) :-
  eval_conj__30(A,B,C,D,F),
  nand_conj__31(F,E).
eval_conj__24(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  nand_conj__32(D,I,E).
eval_conj__24(A,not(B),C,D) :-
  eval_conj__33(A,B,C,E),
  nand__8(D,E).
eval_conj__25([A|B],var(C),D,E) :-
  elem_conj__28(C,A,B,F),
  eval__13(A,B,D,G),
  nand_conj__12(F,G,E).
eval_conj__25(A,conj(B,C),D,E) :-
  eval_conj__21(A,B,C,F),
  eval__6(A,D,G),
  nand_conj__12(F,G,E).
eval_conj__25(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  nand__8(J,I),
  eval__6(A,D,K),
  nand_conj__12(J,K,E).
eval_conj__25(A,not(B),C,D) :-
  eval_conj__26(A,B,C,E),
  nand__8(E,D).
eval_conj__26([A|B],var(C),D,E) :-
  elem_conj__27(C,A,B,F),
  eval__13(A,B,D,G),
  nand__7(F,G,E).
eval_conj__26(A,conj(B,C),D,E) :-
  eval_conj__21(A,B,C,F),
  nand__8(G,F),
  eval__6(A,D,H),
  nand__7(G,H,E).
eval_conj__26(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  nand_conj__22(I,J),
  eval__6(A,D,K),
  nand__7(J,K,E).
eval_conj__26(A,not(B),C,D) :-
  eval_conj__18(A,B,E,C,F),
  nand__7(E,F,D).
elem_conj__27(zero,A,B,C) :-
  nand_conj__22(A,C).
elem_conj__27(succ(A),B,[C|D],E) :-
  elem_conj__27(A,C,D,E).
elem_conj__28(zero,A,B,C) :-
  nand__8(C,A).
elem_conj__28(succ(A),B,[C|D],E) :-
  elem_conj__28(A,C,D,E).
elem_conj__29(zero,A,B,C,D) :-
  nand_conj__32(C,A,D).
elem_conj__29(succ(A),B,[C|D],E,F) :-
  elem_conj__29(A,C,D,E,F).
eval_conj__30([A|B],var(C),D,E,F) :-
  elem__2(C,A,B,G),
  eval__13(A,B,D,H),
  nand__7(G,H,I),
  nand__8(I,J),
  nand__7(E,J,F).
eval_conj__30(A,conj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand_conj__12(G,H,I),
  eval_conj__41(A,D,I,E,F).
eval_conj__30(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,J),
  eval_conj__41(A,D,J,E,F).
eval_conj__30(A,not(B),C,D,E) :-
  eval_conj__25(A,B,C,F),
  nand__7(D,F,E).
nand_conj__31(false,false).
nand_conj__31(true,true).
nand_conj__32(false,false,true).
nand_conj__32(false,true,true).
nand_conj__32(true,false,true).
nand_conj__32(true,true,false).
eval_conj__33([A|B],var(C),D,E) :-
  elem_conj__34(C,A,B,D,E).
eval_conj__33(A,conj(B,C),D,E) :-
  eval_conj__21(A,B,C,F),
  nand_conj__12(D,F,E).
eval_conj__33(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  nand_conj__35(I,D,E).
eval_conj__33(A,not(B),C,D) :-
  eval_conj__36(A,B,C,E),
  nand__8(E,D).
elem_conj__34(zero,A,B,C,D) :-
  nand_conj__35(A,C,D).
elem_conj__34(succ(A),B,[C|D],E,F) :-
  elem_conj__34(A,C,D,E,F).
nand_conj__35(true,A,false) :-
  nand__11(A).
nand_conj__35(false,A,B) :-
  nand_conj__40(A,B).
eval_conj__36([A|B],var(C),D,E) :-
  elem_conj__37(C,A,B,D,E).
eval_conj__36(A,conj(B,C),D,E) :-
  eval_conj__21(A,B,C,F),
  nand_conj__38(F,D,E).
eval_conj__36(A,disj(B,C),D,E) :-
  eval__6(A,B,F),
  eval__6(A,C,G),
  nand__8(F,H),
  nand_conj__9(G,H,I),
  nand_conj__39(I,D,E).
eval_conj__36(A,not(B),C,D) :-
  eval_conj__19(A,B,E),
  nand__7(C,E,D).
elem_conj__37(zero,A,B,C,D) :-
  nand_conj__39(A,C,D).
elem_conj__37(succ(A),B,[C|D],E,F) :-
  elem_conj__37(A,C,D,E,F).
nand_conj__38(true,A,true) :-
  nand__11(A).
nand_conj__38(false,A,B) :-
  nand__10(A,B).
nand_conj__39(true,A,B) :-
  nand__10(A,B).
nand_conj__39(false,A,true) :-
  nand__11(A).
nand_conj__40(false,false).
nand_conj__40(true,true).
eval_conj__41([A|B],var(C),D,E,F) :-
  elem_conj__42(C,A,B,D,E,F).
eval_conj__41(A,conj(B,C),D,E,F) :-
  eval_conj__30(A,B,C,D,G),
  nand_conj__9(G,E,F).
eval_conj__41(A,disj(B,C),D,E,F) :-
  eval__6(A,B,G),
  eval__6(A,C,H),
  nand__8(G,I),
  nand_conj__9(H,I,J),
  nand_conj__43(D,J,E,F).
eval_conj__41(A,not(B),C,D,E) :-
  eval_conj__33(A,B,C,F),
  nand__7(D,F,E).
elem_conj__42(zero,A,B,C,D,E) :-
  nand_conj__43(C,A,D,E).
elem_conj__42(succ(A),B,[C|D],E,F,G) :-
  elem_conj__42(A,C,D,E,F,G).
nand_conj__43(false,false,A,true) :-
  nand__11(A).
nand_conj__43(false,true,A,true) :-
  nand__11(A).
nand_conj__43(true,false,A,true) :-
  nand__11(A).
nand_conj__43(true,true,A,B) :-
  nand__10(A,B).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:a Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 640 ms */
/* Unfolding time: 600 ms */
/* Post-Processing time: 640 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval(A,B,false).
eval_conj__3(A,B,C,D,E) :- eval(A,B,C), eval(A,D,F1), nand(E,F1,true).
eval__4(A,B,C) :- eval(A,B,C).
nand__5(A,B,C) :- nand(A,B,C).
elem__6(A,B,C,D) :- elem(A,[B|C],D).
nand_conj__7(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand_conj__8(A,B,C) :- nand(A,B,D1), nand(D1,D1,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__6(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__4(A,B,D),
  eval__4(A,C,E),
  nand__5(D,D,F),
  nand_conj__7(E,F,true).
eval__1(A,not(B)) :-
  eval__2(A,B).
eval__2([A|B],var(C)) :-
  elem__6(C,A,B,false).
eval__2(A,conj(B,C)) :-
  eval_conj__3(A,B,D,C,D).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,not(B)) :-
  eval__1(A,B).
eval_conj__3([A|B],var(C),D,E,F) :-
  elem__6(C,A,B,D),
  eval__4([A|B],E,G),
  nand__5(F,G,true).
eval_conj__3(A,conj(B,C),D,E,F) :-
  eval__4(A,B,G),
  eval__4(A,C,H),
  nand_conj__8(G,H,D),
  eval__4(A,E,I),
  nand__5(F,I,true).
eval_conj__3(A,disj(B,C),D,E,F) :-
  eval__4(A,B,G),
  eval__4(A,C,H),
  nand__5(G,G,I),
  nand_conj__7(H,I,D),
  eval__4(A,E,J),
  nand__5(F,J,true).
eval_conj__3(A,not(B),C,D,E) :-
  eval__4(A,B,F),
  nand__5(C,C,F),
  eval__4(A,D,G),
  nand__5(E,G,true).
eval__4([A|B],var(C),D) :-
  elem__6(C,A,B,D).
eval__4(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand_conj__8(E,F,D).
eval__4(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand__5(E,E,G),
  nand_conj__7(F,G,D).
eval__4(A,not(B),C) :-
  eval__4(A,B,D),
  nand__5(C,C,D).
nand__5(false,false,true).
nand__5(false,true,true).
nand__5(true,false,true).
nand__5(true,true,false).
elem__6(zero,A,B,A).
elem__6(succ(A),B,[C|D],E) :-
  elem__6(A,C,D,E).
nand_conj__7(false,A,B) :-
  nand__5(A,true,B).
nand_conj__7(true,A,true) :-
  nand__5(A,false,true).
nand_conj__8(false,false,false).
nand_conj__8(false,true,false).
nand_conj__8(true,false,false).
nand_conj__8(true,true,true).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:x Sel:x Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 20 ms */
/* Unfolding time: 0 ms */
/* Post-Processing time: 20 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or__3(A,B) :- or(A,B,true).
eval__4(A,B,C) :- eval(A,B,C).
elem__6(A,B,C,D) :- elem(A,[B|C],D).
and__7(A,B,C) :- and(A,B,C).
or__8(A,B,C) :- or(A,B,C).
neg__9(A,B) :- neg(A,B).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__6(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__4(A,B,true),
  eval__4(A,C,true).
eval__1(A,disj(B,C)) :-
  eval__4(A,B,D),
  eval__4(A,C,E),
  or__3(D,E).
eval__1(A,not(B)) :-
  eval__4(A,B,false).
or__3(false,true).
or__3(true,false).
or__3(true,true).
eval__4([A|B],var(C),D) :-
  elem__6(C,A,B,D).
eval__4(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  and__7(E,F,D).
eval__4(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  or__8(E,F,D).
eval__4(A,not(B),C) :-
  eval__4(A,B,D),
  neg__9(C,D).
elem__6(zero,A,B,A).
elem__6(succ(A),B,[C|D],E) :-
  elem__6(A,C,D,E).
and__7(false,false,false).
and__7(false,true,false).
and__7(true,false,false).
and__7(true,true,true).
or__8(false,false,false).
or__8(false,true,true).
or__8(true,false,true).
or__8(true,true,true).
neg__9(false,true).
neg__9(true,false).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:x Sel:x Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 220 ms */
/* Unfolding time: 160 ms */
/* Post-Processing time: 220 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
neg__3(A,B) :- neg(A,B).
or__4(A,B,C) :- or(A,B,C).
and__5(A,B,C) :- and(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  and__5(E,F,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  or__4(E,F,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,D),
  neg__3(C,D).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
neg__3(false,true).
neg__3(true,false).
or__4(false,false,false).
or__4(false,true,true).
or__4(true,false,true).
or__4(true,true,true).
and__5(false,false,false).
and__5(false,true,false).
and__5(true,false,false).
and__5(true,true,true).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:n Sel:o Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 60 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or__3(A,B) :- or(A,B,true).
eval__4(A,B) :- eval(A,B,false).
elem__5(A,B,C,D) :- elem(A,[B|C],D).
and__6(A,B) :- and(A,B,false).
eval__7(A,B,C) :- eval(A,B,C).
and__9(A,B,C) :- and(A,B,C).
or__10(A,B,C) :- or(A,B,C).
nand__11(A,B) :- nand(A,A,B).
nand__12(A,B) :- nand(true,A,B).
nand__13(A) :- nand(false,A,true).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__5(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__7(A,B,true),
  eval__7(A,C,true).
eval__1(A,disj(B,C)) :-
  eval__7(A,B,D),
  eval__7(A,C,E),
  or__3(D,E).
eval__1(A,not(B)) :-
  eval__4(A,B).
or__3(false,true).
or__3(true,A) :-
  nand__11(A,B),
  nand__13(B).
eval__4([A|B],var(C)) :-
  elem__5(C,A,B,false).
eval__4(A,conj(B,C)) :-
  eval__7(A,B,D),
  eval__7(A,C,E),
  and__6(D,E).
eval__4(A,disj(B,C)) :-
  eval__7(A,B,false),
  eval__7(A,C,false).
eval__4(A,not(B)) :-
  eval__1(A,B).
elem__5(zero,A,B,A).
elem__5(succ(A),B,[C|D],E) :-
  elem__5(A,C,D,E).
and__6(false,false).
and__6(false,true).
and__6(true,false).
eval__7([A|B],var(C),D) :-
  elem__5(C,A,B,D).
eval__7(A,conj(B,C),D) :-
  eval__7(A,B,E),
  eval__7(A,C,F),
  and__9(E,F,D).
eval__7(A,disj(B,C),D) :-
  eval__7(A,B,E),
  eval__7(A,C,F),
  or__10(E,F,D).
eval__7(A,not(B),C) :-
  eval__7(A,B,D),
  nand__11(C,D).
and__9(false,false,false).
and__9(false,true,false).
and__9(true,false,false).
and__9(true,true,true).
or__10(false,A,B) :-
  nand__11(A,C),
  nand__12(C,B).
or__10(true,A,true) :-
  nand__11(A,B),
  nand__13(B).
nand__11(false,true).
nand__11(true,false).
nand__12(false,true).
nand__12(true,false).
nand__13(false).
nand__13(true).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:m InstCheck:a Msv:n NgSlv:n Part:s Prun:n Sel:s Whstl:m Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 60 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C) :- elem(A,B,C).
nand__3(A,B,C) :- nand(A,B,C).
nand__4(A,B) :- nand(A,A,B).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1(A,var(B),C) :-
  elem__2(B,A,C).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  nand__3(E,F,G),
  nand__3(G,G,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  nand__3(E,E,G),
  nand__3(F,F,H),
  nand__3(G,H,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,D),
  nand__4(C,D).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
nand__3(false,false,true).
nand__3(false,true,true).
nand__3(true,false,true).
nand__3(true,true,false).
nand__4(false,true).
nand__4(true,false).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:n NgSlv:g Part:s Prun:n Sel:j Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:no ParAbs:yes Msvp:no Rrc:no */
/* Transformation time: 60 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C) :- elem(A,B,C).
and__3(A,B) :- and(A,B,true).
eval__4(A,B,C,D) :- eval([A|B],C,D).
or__5(A,B) :- or(A,B,true).
eval__6(A,B,C) :- eval(A,B,C).
neg__7(A,B) :- neg(A,B).
neg__8(A) :- neg(true,A).
and__9(A,B,C) :- and(A,B,C).
or__10(A,B,C) :- or(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([true|A],var(zero)).
eval__1([A|B],var(succ(C))) :-
  elem__2(C,B,true).
eval__1([true|A],conj(var(zero),var(zero))).
eval__1([true,true|A],conj(var(zero),var(succ(zero)))).
eval__1([A,B|C],conj(var(zero),var(succ(succ(D))))) :-
  elem__2(D,C,E),
  and__3(A,E).
eval__1([A|B],conj(var(zero),conj(C,D))) :-
  eval__4(A,B,C,E),
  eval__4(A,B,D,F),
  and__9(E,F,G),
  and__3(A,G).
eval__1([A|B],conj(var(zero),disj(C,D))) :-
  eval__4(A,B,C,E),
  eval__4(A,B,D,F),
  or__10(E,F,G),
  and__3(A,G).
eval__1([A|B],conj(var(zero),not(C))) :-
  eval__4(A,B,C,D),
  neg__7(E,D),
  and__3(A,E).
eval__1([A|B],conj(var(succ(C)),D)) :-
  elem__2(C,B,E),
  eval__4(A,B,D,F),
  and__3(E,F).
eval__1(A,conj(conj(B,C),D)) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  and__9(E,F,G),
  eval__6(A,D,H),
  and__3(G,H).
eval__1(A,conj(disj(B,C),D)) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  or__10(E,F,G),
  eval__6(A,D,H),
  and__3(G,H).
eval__1(A,conj(not(B),C)) :-
  eval__6(A,B,D),
  neg__7(E,D),
  eval__6(A,C,F),
  and__3(E,F).
eval__1([true|A],disj(var(zero),var(zero))).
eval__1([false,true|A],disj(var(zero),var(succ(zero)))).
eval__1([true,false|A],disj(var(zero),var(succ(zero)))).
eval__1([true,true|A],disj(var(zero),var(succ(zero)))).
eval__1([A,B|C],disj(var(zero),var(succ(succ(D))))) :-
  elem__2(D,C,E),
  or__5(A,E).
eval__1([A|B],disj(var(zero),conj(C,D))) :-
  eval__4(A,B,C,E),
  eval__4(A,B,D,F),
  and__9(E,F,G),
  or__5(A,G).
eval__1([A|B],disj(var(zero),disj(C,D))) :-
  eval__4(A,B,C,E),
  eval__4(A,B,D,F),
  or__10(E,F,G),
  or__5(A,G).
eval__1([A|B],disj(var(zero),not(C))) :-
  eval__4(A,B,C,D),
  neg__7(E,D),
  or__5(A,E).
eval__1([A|B],disj(var(succ(C)),D)) :-
  elem__2(C,B,E),
  eval__4(A,B,D,F),
  or__5(E,F).
eval__1(A,disj(conj(B,C),D)) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  and__9(E,F,G),
  eval__6(A,D,H),
  or__5(G,H).
eval__1(A,disj(disj(B,C),D)) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  or__10(E,F,G),
  eval__6(A,D,H),
  or__5(G,H).
eval__1(A,disj(not(B),C)) :-
  eval__6(A,B,D),
  neg__7(E,D),
  eval__6(A,C,F),
  or__5(E,F).
eval__1([false|A],not(var(zero))).
eval__1([A|B],not(var(succ(C)))) :-
  elem__2(C,B,D),
  neg__8(D).
eval__1(A,not(conj(B,C))) :-
  eval__6(A,B,D),
  eval__6(A,C,E),
  and__9(D,E,F),
  neg__8(F).
eval__1(A,not(disj(B,C))) :-
  eval__6(A,B,D),
  eval__6(A,C,E),
  or__10(D,E,F),
  neg__8(F).
eval__1(A,not(not(B))) :-
  eval__6(A,B,C),
  neg__7(D,C),
  neg__8(D).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
and__3(true,true).
eval__4(A,B,var(C),D) :-
  elem__2(C,[A|B],D).
eval__4(A,B,conj(C,D),E) :-
  eval__4(A,B,C,F),
  eval__4(A,B,D,G),
  and__9(F,G,E).
eval__4(A,B,disj(C,D),E) :-
  eval__4(A,B,C,F),
  eval__4(A,B,D,G),
  or__10(F,G,E).
eval__4(A,B,not(C),D) :-
  eval__4(A,B,C,E),
  neg__7(D,E).
or__5(false,true).
or__5(true,false).
or__5(true,true).
eval__6([A|B],var(zero),A).
eval__6([A|B],var(succ(C)),D) :-
  elem__2(C,B,D).
eval__6(A,conj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  and__9(E,F,D).
eval__6(A,disj(B,C),D) :-
  eval__6(A,B,E),
  eval__6(A,C,F),
  or__10(E,F,D).
eval__6(A,not(B),C) :-
  eval__6(A,B,D),
  neg__7(C,D).
neg__7(false,true).
neg__7(true,false).
neg__8(false).
and__9(false,false,false).
and__9(false,true,false).
and__9(true,false,false).
and__9(true,true,true).
or__10(false,false,false).
or__10(false,true,true).
or__10(true,false,true).
or__10(true,true,true).
