eval(St, var(X), U) :- elem(X, St, U).
eval(St, conj(X,Y), U)  :- eval(St, X, V), eval(St, Y, W), and(V, W, U).
eval(St, disj(X,Y), U)  :- eval(St, X, V), eval(St, Y, W), or(V, W, U).
eval(St, not(X), U) :- eval(St, X, neg(U)).

elem(zero, [H|T], H).
elem(succ(N), [H|T], V) :- elem(N, T, V).

nand(false, false, true).
nand(false, true,  true).
nand(true,  false, true).
nand(true,  true,  false).

neg(X, R) :- nand(X, X, R).

or(X, Y, R) :- nand(X, X, Xx), nand(Y, Y, Yy), nand(Xx, Yy, R).

and(X, Y, R) :- nand(X, Y, Xy), nand(Xy, Xy, R).

/* Default Conjunctive */
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 580 ms */
/* Unfolding time: 520 ms */
/* Post-Processing time: 580 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
eval_conj__3(A,B,C) :- eval(A,B,D1), eval(A,C,E1), nand(D1,D1,F1), nand(E1,E1,G1), nand(F1,G1,true).
eval__4(A,B,C) :- eval(A,B,C).
eval_conj__5(A,B,C,D,E) :- eval(A,B,neg(C)), eval(A,D,E).
nand__6(A,B) :- nand(A,A,B).
nand_conj__7(A,B) :- nand(A,A,C1), nand(B,C1,true).
nand__8(A) :- nand(A,false,true).
eval__9(A,B,C,D) :- eval([A|B],C,D).
eval__10(A,B,C) :- eval(A,B,neg(C)).
nand_conj__11(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand__12(A,B) :- nand(A,true,B).
nand_conj__13(A,B,C) :- nand(A,B,D1), nand(D1,D1,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__2(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval_conj__3(A,B,C).
eval__1(A,not(B)) :-
  eval__10(A,B,true).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
eval_conj__3([A|B],var(C),D) :-
  elem__2(C,A,B,E),
  eval__9(A,B,D,F),
  nand__6(E,G),
  nand_conj__7(F,G).
eval_conj__3(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand_conj__13(E,F,G),
  eval__4(A,D,H),
  nand__6(G,I),
  nand_conj__7(H,I).
eval_conj__3(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand__6(E,G),
  nand_conj__11(F,G,H),
  eval__4(A,D,I),
  nand__6(H,J),
  nand_conj__7(I,J).
eval_conj__3(A,not(B),C) :-
  eval_conj__5(A,B,D,C,E),
  nand__6(D,F),
  nand_conj__7(E,F).
eval__4([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__4(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand_conj__13(E,F,D).
eval__4(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand__6(E,G),
  nand_conj__11(F,G,D).
eval__4(A,not(B),C) :-
  eval__10(A,B,C).
eval_conj__5([A|B],var(C),D,E,F) :-
  elem__2(C,A,B,neg(D)),
  eval__9(A,B,E,F).
eval_conj__5(A,not(B),C,D,E) :-
  eval_conj__5(A,B,neg(C),D,E).
nand__6(false,true).
nand__6(true,false).
nand_conj__7(false,false).
nand_conj__7(true,A) :-
  nand__8(A).
nand__8(false).
nand__8(true).
eval__9(A,B,var(C),D) :-
  elem__2(C,A,B,D).
eval__9(A,B,conj(C,D),E) :-
  eval__9(A,B,C,F),
  eval__9(A,B,D,G),
  nand_conj__13(F,G,E).
eval__9(A,B,disj(C,D),E) :-
  eval__9(A,B,C,F),
  eval__9(A,B,D,G),
  nand__6(F,H),
  nand_conj__11(G,H,E).
eval__9(A,B,not(C),D) :-
  eval__10([A|B],C,D).
eval__10([A|B],var(C),D) :-
  elem__2(C,A,B,neg(D)).
eval__10(A,not(B),C) :-
  eval__10(A,B,neg(C)).
nand_conj__11(false,A,B) :-
  nand__12(A,B).
nand_conj__11(true,A,true) :-
  nand__8(A).
nand__12(false,true).
nand__12(true,false).
nand_conj__13(false,false,false).
nand_conj__13(false,true,false).
nand_conj__13(true,false,false).
nand_conj__13(true,true,true).

/* Conjunctive Fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:a Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 560 ms */
/* Unfolding time: 500 ms */
/* Post-Processing time: 560 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval_conj__2(A,B,C) :- eval(A,B,D1), eval(A,C,E1), nand(D1,D1,F1), nand(E1,E1,G1), nand(F1,G1,true).
eval__3(A,B,C) :- eval(A,B,neg(C)).
eval__4(A,B,C) :- eval(A,B,C).
eval_conj__5(A,B,C,D,E) :- eval(A,B,neg(C)), eval(A,D,E).
nand__6(A,B) :- nand(A,A,B).
nand_conj__7(A,B) :- nand(A,A,C1), nand(B,C1,true).
nand__8(A) :- nand(A,false,true).
eval__9(A,B,C,D) :- eval([A|B],C,D).
elem__10(A,B,C,D) :- elem(A,[B|C],D).
nand_conj__11(A,B,C) :- nand(A,A,D1), nand(B,D1,C).
nand__12(A,B) :- nand(A,true,B).
nand_conj__13(A,B,C) :- nand(A,B,D1), nand(D1,D1,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__10(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval_conj__2(A,B,C).
eval__1(A,not(B)) :-
  eval__3(A,B,true).
eval_conj__2([A|B],var(C),D) :-
  elem__10(C,A,B,E),
  eval__4([A|B],D,F),
  nand__6(E,G),
  nand_conj__7(F,G).
eval_conj__2(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand_conj__13(E,F,G),
  eval__4(A,D,H),
  nand__6(G,I),
  nand_conj__7(H,I).
eval_conj__2(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand__6(E,G),
  nand_conj__11(F,G,H),
  eval__4(A,D,I),
  nand__6(H,J),
  nand_conj__7(I,J).
eval_conj__2(A,not(B),C) :-
  eval_conj__5(A,B,D,C,E),
  nand__6(D,F),
  nand_conj__7(E,F).
eval__3([A|B],var(C),D) :-
  elem__10(C,A,B,neg(D)).
eval__3(A,not(B),C) :-
  eval__3(A,B,neg(C)).
eval__4([A|B],var(C),D) :-
  elem__10(C,A,B,D).
eval__4(A,conj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand_conj__13(E,F,D).
eval__4(A,disj(B,C),D) :-
  eval__4(A,B,E),
  eval__4(A,C,F),
  nand__6(E,G),
  nand_conj__11(F,G,D).
eval__4(A,not(B),C) :-
  eval__3(A,B,C).
eval_conj__5([A|B],var(C),D,E,F) :-
  elem__10(C,A,B,neg(D)),
  eval__9(A,B,E,F).
eval_conj__5(A,not(B),C,D,E) :-
  eval_conj__5(A,B,neg(C),D,E).
nand__6(false,true).
nand__6(true,false).
nand_conj__7(false,false).
nand_conj__7(true,A) :-
  nand__8(A).
nand__8(false).
nand__8(true).
eval__9(A,B,var(C),D) :-
  elem__10(C,A,B,D).
eval__9(A,B,conj(C,D),E) :-
  eval__9(A,B,C,F),
  eval__9(A,B,D,G),
  nand_conj__13(F,G,E).
eval__9(A,B,disj(C,D),E) :-
  eval__9(A,B,C,F),
  eval__9(A,B,D,G),
  nand__6(F,H),
  nand_conj__11(G,H,E).
eval__9(A,B,not(C),D) :-
  eval__3([A|B],C,D).
elem__10(zero,A,B,A).
elem__10(succ(A),B,[C|D],E) :-
  elem__10(A,C,D,E).
nand_conj__11(false,A,B) :-
  nand__12(A,B).
nand_conj__11(true,A,true) :-
  nand__8(A).
nand__12(false,true).
nand__12(true,false).
nand_conj__13(false,false,false).
nand_conj__13(false,true,false).
nand_conj__13(true,false,false).
nand_conj__13(true,true,true).

/* Classic */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:x Sel:x Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
and__3(A,B,C) :- and(A,B,C).
or__4(A,B,C) :- or(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  and__3(E,F,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  or__4(E,F,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
and__3(false,false,false).
and__3(false,true,false).
and__3(true,false,false).
and__3(true,true,true).
or__4(false,false,false).
or__4(false,true,true).
or__4(true,false,true).
or__4(true,true,true).

/* Mixtus Style */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:x Sel:x Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 60 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 60 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
or__3(A,B,C) :- or(A,B,C).
and__4(A,B,C) :- and(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  and__4(E,F,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  or__3(E,F,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
or__3(false,false,false).
or__3(false,true,true).
or__3(true,false,true).
or__3(true,true,true).
and__4(false,false,false).
and__4(false,true,false).
and__4(true,false,false).
and__4(true,true,true).

/* Classic Fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:n Sel:o Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 20 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
and__3(A,B,C) :- and(A,B,C).
or__4(A,B,C) :- or(A,B,C).
nand__5(A,B) :- nand(true,A,B).
nand__6(A,B) :- nand(A,A,B).
nand__7(A) :- nand(false,A,true).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1([A|B],var(C),D) :-
  elem__2(C,A,B,D).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  and__3(E,F,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  or__4(E,F,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
and__3(false,false,false).
and__3(false,true,false).
and__3(true,false,false).
and__3(true,true,true).
or__4(false,A,B) :-
  nand__6(A,C),
  nand__5(C,B).
or__4(true,A,true) :-
  nand__6(A,B),
  nand__7(B).
nand__5(false,true).
nand__5(true,false).
nand__6(false,true).
nand__6(true,false).
nand__7(false).
nand__7(true).

/* minimal */
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:m InstCheck:a Msv:n NgSlv:n Part:s Prun:n Sel:s Whstl:m Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 20 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C) :- elem(A,B,C).
nand__3(A,B,C) :- nand(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1(A,var(B),C) :-
  elem__2(B,A,C).
eval__1(A,conj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  nand__3(E,F,G),
  nand__3(G,G,D).
eval__1(A,disj(B,C),D) :-
  eval__1(A,B,E),
  eval__1(A,C,F),
  nand__3(E,E,G),
  nand__3(F,F,H),
  nand__3(G,H,D).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
nand__3(false,false,true).
nand__3(false,true,true).
nand__3(true,false,true).
nand__3(true,true,false).

/* Terminatioin */


/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:n NgSlv:g Part:s Prun:n Sel:j Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:no ParAbs:yes Msvp:no Rrc:no */
/* Transformation time: 320 ms */
/* Unfolding time: 180 ms */
/* Post-Processing time: 320 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
and__2(A,B) :- and(A,B,true).
or__3(A,B) :- or(A,B,true).
eval__4(A,B,C) :- eval(A,B,neg(C)).
elem__5(A,B,C) :- elem(A,B,C).
eval__7(A,B,C,D) :- eval([A|B],C,D).
eval__8(A,B,C) :- eval(A,B,C).
and__10(A,B,C) :- and(A,B,C).
or__11(A,B,C) :- or(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([true|A],var(zero)).
eval__1([A|B],var(succ(C))) :-
  elem__5(C,B,true).
eval__1([true|A],conj(var(zero),var(zero))).
eval__1([true,true|A],conj(var(zero),var(succ(zero)))).
eval__1([A,B|C],conj(var(zero),var(succ(succ(D))))) :-
  elem__5(D,C,E),
  and__2(A,E).
eval__1([A|B],conj(var(zero),conj(C,D))) :-
  eval__7(A,B,C,E),
  eval__7(A,B,D,F),
  and__10(E,F,G),
  and__2(A,G).
eval__1([A|B],conj(var(zero),disj(C,D))) :-
  eval__7(A,B,C,E),
  eval__7(A,B,D,F),
  or__11(E,F,G),
  and__2(A,G).
eval__1([A|B],conj(var(zero),not(C))) :-
  eval__7(A,B,C,neg(D)),
  and__2(A,D).
eval__1([A|B],conj(var(succ(C)),D)) :-
  elem__5(C,B,E),
  eval__7(A,B,D,F),
  and__2(E,F).
eval__1(A,conj(conj(B,C),D)) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  and__10(E,F,G),
  eval__8(A,D,H),
  and__2(G,H).
eval__1(A,conj(disj(B,C),D)) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  or__11(E,F,G),
  eval__8(A,D,H),
  and__2(G,H).
eval__1(A,conj(not(B),C)) :-
  eval__8(A,B,neg(D)),
  eval__8(A,C,E),
  and__2(D,E).
eval__1([true|A],disj(var(zero),var(zero))).
eval__1([false,true|A],disj(var(zero),var(succ(zero)))).
eval__1([true,false|A],disj(var(zero),var(succ(zero)))).
eval__1([true,true|A],disj(var(zero),var(succ(zero)))).
eval__1([A,B|C],disj(var(zero),var(succ(succ(D))))) :-
  elem__5(D,C,E),
  or__3(A,E).
eval__1([A|B],disj(var(zero),conj(C,D))) :-
  eval__7(A,B,C,E),
  eval__7(A,B,D,F),
  and__10(E,F,G),
  or__3(A,G).
eval__1([A|B],disj(var(zero),disj(C,D))) :-
  eval__7(A,B,C,E),
  eval__7(A,B,D,F),
  or__11(E,F,G),
  or__3(A,G).
eval__1([A|B],disj(var(zero),not(C))) :-
  eval__7(A,B,C,neg(D)),
  or__3(A,D).
eval__1([A|B],disj(var(succ(C)),D)) :-
  elem__5(C,B,E),
  eval__7(A,B,D,F),
  or__3(E,F).
eval__1(A,disj(conj(B,C),D)) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  and__10(E,F,G),
  eval__8(A,D,H),
  or__3(G,H).
eval__1(A,disj(disj(B,C),D)) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  or__11(E,F,G),
  eval__8(A,D,H),
  or__3(G,H).
eval__1(A,disj(not(B),C)) :-
  eval__8(A,B,neg(D)),
  eval__8(A,C,E),
  or__3(D,E).
eval__1(A,not(B)) :-
  eval__4(A,B,true).
and__2(true,true).
or__3(false,true).
or__3(true,false).
or__3(true,true).
eval__4([neg(A)|B],var(zero),A).
eval__4([A|B],var(succ(C)),D) :-
  elem__5(C,B,neg(D)).
eval__4([A,B|C],conj(var(zero),var(succ(succ(D)))),E) :-
  elem__5(D,C,F),
  fail.
eval__4([A|B],conj(var(zero),conj(C,D)),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  and__10(F,G,H),
  fail.
eval__4([A|B],conj(var(zero),disj(C,D)),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  or__11(F,G,H),
  fail.
eval__4([A|B],conj(var(zero),not(C)),D) :-
  eval__7(A,B,C,neg(E)),
  fail.
eval__4([A|B],conj(var(succ(C)),D),E) :-
  elem__5(C,B,F),
  eval__7(A,B,D,G),
  fail.
eval__4(A,conj(conj(B,C),D),E) :-
  eval__8(A,B,F),
  eval__8(A,C,G),
  and__10(F,G,H),
  eval__8(A,D,I),
  fail.
eval__4(A,conj(disj(B,C),D),E) :-
  eval__8(A,B,F),
  eval__8(A,C,G),
  or__11(F,G,H),
  eval__8(A,D,I),
  fail.
eval__4(A,conj(not(B),C),D) :-
  eval__8(A,B,neg(E)),
  eval__8(A,C,F),
  fail.
eval__4([A,B|C],disj(var(zero),var(succ(succ(D)))),E) :-
  elem__5(D,C,F),
  fail.
eval__4([A|B],disj(var(zero),conj(C,D)),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  and__10(F,G,H),
  fail.
eval__4([A|B],disj(var(zero),disj(C,D)),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  or__11(F,G,H),
  fail.
eval__4([A|B],disj(var(zero),not(C)),D) :-
  eval__7(A,B,C,neg(E)),
  fail.
eval__4([A|B],disj(var(succ(C)),D),E) :-
  elem__5(C,B,F),
  eval__7(A,B,D,G),
  fail.
eval__4(A,disj(conj(B,C),D),E) :-
  eval__8(A,B,F),
  eval__8(A,C,G),
  and__10(F,G,H),
  eval__8(A,D,I),
  fail.
eval__4(A,disj(disj(B,C),D),E) :-
  eval__8(A,B,F),
  eval__8(A,C,G),
  or__11(F,G,H),
  eval__8(A,D,I),
  fail.
eval__4(A,disj(not(B),C),D) :-
  eval__8(A,B,neg(E)),
  eval__8(A,C,F),
  fail.
eval__4(A,not(B),C) :-
  eval__4(A,B,neg(C)).
elem__5(zero,[A|B],A).
elem__5(succ(A),[B|C],D) :-
  elem__5(A,C,D).
eval__7(A,B,var(C),D) :-
  elem__5(C,[A|B],D).
eval__7(A,B,conj(C,D),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  and__10(F,G,E).
eval__7(A,B,disj(C,D),E) :-
  eval__7(A,B,C,F),
  eval__7(A,B,D,G),
  or__11(F,G,E).
eval__7(A,B,not(C),D) :-
  eval__7(A,B,C,neg(D)).
eval__8([A|B],var(zero),A).
eval__8([A|B],var(succ(C)),D) :-
  elem__5(C,B,D).
eval__8(A,conj(B,C),D) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  and__10(E,F,D).
eval__8(A,disj(B,C),D) :-
  eval__8(A,B,E),
  eval__8(A,C,F),
  or__11(E,F,D).
eval__8(A,not(B),C) :-
  eval__8(A,B,neg(C)).
and__10(false,false,false).
and__10(false,true,false).
and__10(true,false,false).
and__10(true,true,true).
or__11(false,false,false).
or__11(false,true,true).
or__11(true,false,true).
or__11(true,true,true).