and(true, true, true).
and(true, false, false).
and(false, true, false).
and(false, false, false).

or(true, true, true).
or(true, false, true).
or(false, true, true).
or(false, false, false).

not(true, false).
not(false, true).

eval(St, var(X), U) :- elem(X, St, U).
eval(St, conj(X,Y), U) :- and(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, disj(X,Y), U) :- or(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, neg(X), U) :- not(V, U), eval(St, X, V).

elem(zero, [H|T], H).
elem(succ(N), [H|T], V) :- elem(N, T, V).



/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 100 ms */
/* Unfolding time: 100 ms */
/* Post-Processing time: 100 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
or_conj__3(A,B,C) :- or(D1,E1,true), eval(A,B,D1), eval(A,C,E1).
eval__4(A,B) :- eval(A,B,false).
and_conj__5(A,B,C) :- and(D1,E1,false), eval(A,B,D1), eval(A,C,E1).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__2(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or_conj__3(A,B,C).
eval__1(A,neg(B)) :-
  eval__4(A,B).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
or_conj__3(A,B,C) :-
  eval__1(A,B),
  eval__1(A,C).
or_conj__3(A,B,C) :-
  eval__1(A,B),
  eval__4(A,C).
or_conj__3(A,B,C) :-
  eval__4(A,B),
  eval__1(A,C).
eval__4([A|B],var(C)) :-
  elem__2(C,A,B,false).
eval__4(A,conj(B,C)) :-
  and_conj__5(A,B,C).
eval__4(A,disj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,neg(B)) :-
  eval__1(A,B).
and_conj__5(A,B,C) :-
  eval__1(A,B),
  eval__4(A,C).
and_conj__5(A,B,C) :-
  eval__4(A,B),
  eval__1(A,C).
and_conj__5(A,B,C) :-
  eval__4(A,B),
  eval__4(A,C).




/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:a Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 100 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 100 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
or_conj__3(A,B,C) :- or(D1,E1,true), eval(A,B,D1), eval(A,C,E1).
eval__4(A,B) :- eval(A,B,false).
and_conj__5(A,B,C) :- and(D1,E1,false), eval(A,B,D1), eval(A,C,E1).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__2(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or_conj__3(A,B,C).
eval__1(A,neg(B)) :-
  eval__4(A,B).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
or_conj__3(A,B,C) :-
  eval__1(A,B),
  eval__1(A,C).
or_conj__3(A,B,C) :-
  eval__1(A,B),
  eval__4(A,C).
or_conj__3(A,B,C) :-
  eval__4(A,B),
  eval__1(A,C).
eval__4([A|B],var(C)) :-
  elem__2(C,A,B,false).
eval__4(A,conj(B,C)) :-
  and_conj__5(A,B,C).
eval__4(A,disj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,neg(B)) :-
  eval__1(A,B).
and_conj__5(A,B,C) :-
  eval__1(A,B),
  eval__4(A,C).
and_conj__5(A,B,C) :-
  eval__4(A,B),
  eval__1(A,C).
and_conj__5(A,B,C) :-
  eval__4(A,B),
  eval__4(A,C).






/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:x Sel:x Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 80 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 80 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval(A,B,false).
elem__3(A,B,C,D) :- elem(A,[B|C],D).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__3(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__1(A,disj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__1(A,neg(B)) :-
  eval__2(A,B).
eval__2([A|B],var(C)) :-
  elem__3(C,A,B,false).
eval__2(A,conj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,neg(B)) :-
  eval__1(A,B).
elem__3(zero,A,B,A).
elem__3(succ(A),B,[C|D],E) :-
  elem__3(A,C,D,E).






/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:x Sel:x Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 100 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 100 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
elem__2(A,B,C,D) :- elem(A,[B|C],D).
eval__3(A,B) :- eval(A,B,false).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__2(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__3(A,C).
eval__1(A,disj(B,C)) :-
  eval__3(A,B),
  eval__1(A,C).
eval__1(A,neg(B)) :-
  eval__3(A,B).
elem__2(zero,A,B,A).
elem__2(succ(A),B,[C|D],E) :-
  elem__2(A,C,D,E).
eval__3([A|B],var(C)) :-
  elem__2(C,A,B,false).
eval__3(A,conj(B,C)) :-
  eval__1(A,B),
  eval__3(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__1(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,disj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,neg(B)) :-
  eval__1(A,B).




/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:n Sel:o Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or__2(A,B) :- or(A,B,true).
eval__3(A,B) :- eval(A,B,false).
and__4(A,B) :- and(A,B,false).
eval__5(A,B,C) :- eval(A,B,C).
elem__6(A,B,C,D) :- elem(A,[B|C],D).
and__7(A,B,C) :- and(A,B,C).
or__8(A,B,C) :- or(A,B,C).
not__9(A,B) :- not(A,B).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__6(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or__2(D,E),
  eval__5(A,B,D),
  eval__5(A,C,E).
eval__1(A,neg(B)) :-
  eval__3(A,B).
or__2(true,true).
or__2(true,false).
or__2(false,true).
eval__3([A|B],var(C)) :-
  elem__6(C,A,B,false).
eval__3(A,conj(B,C)) :-
  and__4(D,E),
  eval__5(A,B,D),
  eval__5(A,C,E).
eval__3(A,disj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,neg(B)) :-
  eval__1(A,B).
and__4(true,false).
and__4(false,true).
and__4(false,false).
eval__5([A|B],var(C),D) :-
  elem__6(C,A,B,D).
eval__5(A,conj(B,C),D) :-
  and__7(E,F,D),
  eval__5(A,B,E),
  eval__5(A,C,F).
eval__5(A,disj(B,C),D) :-
  or__8(E,F,D),
  eval__5(A,B,E),
  eval__5(A,C,F).
eval__5(A,neg(B),C) :-
  not__9(D,C),
  eval__5(A,B,D).
elem__6(zero,A,B,A).
elem__6(succ(A),B,[C|D],E) :-
  elem__6(A,C,D,E).
and__7(true,true,true).
and__7(true,false,false).
and__7(false,true,false).
and__7(false,false,false).
or__8(true,true,true).
or__8(true,false,true).
or__8(false,true,true).
or__8(false,false,false).
not__9(true,false).
not__9(false,true).





/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:m InstCheck:a Msv:n NgSlv:n Part:s Prun:n Sel:s Whstl:m Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 20 ms */
/* Unfolding time: 20 ms */
/* Post-Processing time: 20 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C) :- elem(A,B,C).
and__3(A,B,C) :- and(A,B,C).
or__4(A,B,C) :- or(A,B,C).
not__5(A,B) :- not(A,B).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1(A,var(B),C) :-
  elem__2(B,A,C).
eval__1(A,conj(B,C),D) :-
  and__3(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,disj(B,C),D) :-
  or__4(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,neg(B),C) :-
  not__5(D,C),
  eval__1(A,B,D).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
and__3(true,true,true).
and__3(true,false,false).
and__3(false,true,false).
and__3(false,false,false).
or__4(true,true,true).
or__4(true,false,true).
or__4(false,true,true).
or__4(false,false,false).
not__5(true,false).
not__5(false,true).





/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:n NgSlv:g Part:s Prun:n Sel:j Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:no ParAbs:yes Msvp:no Rrc:no */
/* Transformation time: 140 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 140 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval([false|A],B,true).
eval__3(A,B) :- eval(A,B,false).
eval__4(A,B) :- eval([true|A],B,false).
eval__5(A,B,C) :- eval([A|B],C,false).
eval__6(A,B,C) :- eval([A|B],C,true).
eval__7(A,B) :- eval([true|A],B,true).
elem__8(A,B,C) :- elem(A,[D1|B],C).
eval__9(A,B) :- eval([false|A],B,false).
elem__10(A,B,C) :- elem(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([true|A],var(zero)).
eval__1([A|B],var(succ(C))) :-
  elem__10(C,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__3(A,C).
eval__1([false|A],disj(var(zero),B)) :-
  eval__2(A,B).
eval__1([A|B],disj(var(succ(C)),D)) :-
  elem__10(C,B,false),
  eval__6(A,B,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(neg(B),C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1([false|A],neg(var(zero))).
eval__1([A|B],neg(var(succ(C)))) :-
  elem__10(C,B,false).
eval__1(A,neg(conj(B,C))) :-
  eval__1(A,B),
  eval__3(A,C).
eval__1(A,neg(conj(B,C))) :-
  eval__3(A,B),
  eval__1(A,C).
eval__1(A,neg(conj(B,C))) :-
  eval__3(A,B),
  eval__3(A,C).
eval__1(A,neg(disj(B,C))) :-
  eval__3(A,B),
  eval__3(A,C).
eval__1(A,neg(neg(B))) :-
  eval__1(A,B).
eval__2(A,var(B)) :-
  elem__8(B,A,true).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__9(A,C).
eval__2(A,disj(B,C)) :-
  eval__9(A,B),
  eval__2(A,C).
eval__2(A,neg(B)) :-
  eval__9(A,B).
eval__3([false|A],var(zero)).
eval__3([A|B],var(succ(C))) :-
  elem__10(C,B,false).
eval__3([true|A],conj(var(zero),B)) :-
  eval__4(A,B).
eval__3([A|B],conj(var(succ(C)),D)) :-
  elem__10(C,B,true),
  eval__5(A,B,D).
eval__3(A,conj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(neg(B),C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__1(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,disj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,neg(B)) :-
  eval__1(A,B).
eval__4(A,var(B)) :-
  elem__8(B,A,false).
eval__4(A,conj(B,C)) :-
  eval__7(A,B),
  eval__4(A,C).
eval__4(A,conj(B,C)) :-
  eval__4(A,B),
  eval__7(A,C).
eval__4(A,conj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,disj(B,C)) :-
  eval__4(A,B),
  eval__4(A,C).
eval__4(A,neg(B)) :-
  eval__7(A,B).
eval__5(false,A,var(zero)).
eval__5(A,[false|B],var(succ(zero))).
eval__5(A,[B|C],var(succ(succ(D)))) :-
  elem__10(D,C,false).
eval__5(A,B,conj(C,D)) :-
  eval__6(A,B,C),
  eval__5(A,B,D).
eval__5(A,B,conj(C,D)) :-
  eval__5(A,B,C),
  eval__6(A,B,D).
eval__5(A,B,conj(C,D)) :-
  eval__5(A,B,C),
  eval__5(A,B,D).
eval__5(A,B,disj(C,D)) :-
  eval__5(A,B,C),
  eval__5(A,B,D).
eval__5(A,B,neg(C)) :-
  eval__6(A,B,C).
eval__6(true,A,var(zero)).
eval__6(A,[true|B],var(succ(zero))).
eval__6(A,[B|C],var(succ(succ(D)))) :-
  elem__10(D,C,true).
eval__6(A,B,conj(C,D)) :-
  eval__6(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,disj(C,D)) :-
  eval__6(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,disj(C,D)) :-
  eval__6(A,B,C),
  eval__5(A,B,D).
eval__6(A,B,disj(C,D)) :-
  eval__5(A,B,C),
  eval__6(A,B,D).
eval__6(A,B,neg(C)) :-
  eval__5(A,B,C).
eval__7(A,var(B)) :-
  elem__10(B,[true|A],true).
eval__7(A,conj(B,C)) :-
  eval__7(A,B),
  eval__7(A,C).
eval__7(A,disj(B,C)) :-
  eval__7(A,B),
  eval__7(A,C).
eval__7(A,disj(B,C)) :-
  eval__7(A,B),
  eval__4(A,C).
eval__7(A,disj(B,C)) :-
  eval__4(A,B),
  eval__7(A,C).
eval__7(A,neg(B)) :-
  eval__4(A,B).
elem__8(succ(A),B,C) :-
  elem__10(A,B,C).
eval__9(A,var(B)) :-
  elem__10(B,[false|A],false).
eval__9(A,conj(B,C)) :-
  eval__2(A,B),
  eval__9(A,C).
eval__9(A,conj(B,C)) :-
  eval__9(A,B),
  eval__2(A,C).
eval__9(A,conj(B,C)) :-
  eval__9(A,B),
  eval__9(A,C).
eval__9(A,disj(B,C)) :-
  eval__9(A,B),
  eval__9(A,C).
eval__9(A,neg(B)) :-
  eval__2(A,B).
elem__10(zero,[A|B],A).
elem__10(succ(A),[B|C],D) :-
  elem__10(A,C,D).
