and(true, true, true).
and(true, false, false).
and(false, true, false).
and(false, false, false).

or(true, true, true).
or(true, false, true).
or(false, true, true).
or(false, false, false).

not(true, false).
not(false, true).

eval(St, var(X), U) :- elem(X, St, U).
eval(St, conj(X,Y), U) :- and(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, disj(X,Y), U) :- or(V, W, U), eval(St, X, V), eval(St, Y, W).
eval(St, not(X), U) :- eval(St, X, neg(U)).

elem(zero, [H|T], H).
elem(succ(N), [H|T], V) :- elem(N, T, V).

/* Default conjunctive */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 400 ms */
/* Unfolding time: 300 ms */
/* Post-Processing time: 400 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or_conj__2(A,B,C) :- or(D1,E1,true), eval(A,B,D1), eval(A,C,E1).
eval_conj__3(A,B,C,D) :- eval(A,B,false), eval(A,C,D).
and_conj__4(A,B,C) :- and(D1,E1,false), eval(A,B,D1), eval(A,C,E1).
eval__5(A,B,C) :- eval(A,B,C).
eval_conj__6(A,B,C,D,E) :- eval(A,B,neg(C)), eval(A,D,E).
eval__7(A,B,C,D) :- eval([A|B],C,D).
and_conj__8(A,B,C,D,E) :- and(F1,G1,A), eval([B|C],D,F1), eval([B|C],E,G1).
or_conj__9(A,B,C,D,E) :- or(F1,G1,A), eval([B|C],D,F1), eval([B|C],E,G1).
eval__10(A,B,C) :- eval(A,B,neg(C)).
and_conj__11(A,B,C,D) :- and(E1,F1,A), eval(B,C,E1), eval(B,D,F1).
or_conj__12(A,B,C,D) :- or(E1,F1,A), eval(B,C,E1), eval(B,D,F1).
elem__13(A,B,C,D) :- elem(A,[B|C],D).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__13(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__5(A,B,true),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or_conj__2(A,B,C).
eval__1(A,not(B)) :-
  eval__10(A,B,true).
or_conj__2(A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
or_conj__2(A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
or_conj__2(A,B,C) :-
  eval_conj__3(A,B,C,true).
eval_conj__3([A|B],var(C),D,E) :-
  elem__13(C,A,B,false),
  eval__7(A,B,D,E).
eval_conj__3(A,conj(B,C),D,E) :-
  and_conj__4(A,B,C),
  eval__5(A,D,E).
eval_conj__3(A,disj(B,C),D,E) :-
  eval__5(A,B,false),
  eval__5(A,C,false),
  eval__5(A,D,E).
eval_conj__3(A,not(B),C,D) :-
  eval_conj__6(A,B,false,C,D).
and_conj__4(A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
and_conj__4(A,B,C) :-
  eval_conj__3(A,B,C,true).
and_conj__4(A,B,C) :-
  eval__5(A,B,false),
  eval__5(A,C,false).
eval__5([A|B],var(C),D) :-
  elem__13(C,A,B,D).
eval__5(A,conj(B,C),D) :-
  and_conj__11(D,A,B,C).
eval__5(A,disj(B,C),D) :-
  or_conj__12(D,A,B,C).
eval__5(A,not(B),C) :-
  eval__10(A,B,C).
eval_conj__6([A|B],var(C),D,E,F) :-
  elem__13(C,A,B,neg(D)),
  eval__7(A,B,E,F).
eval_conj__6(A,not(B),C,D,E) :-
  eval_conj__6(A,B,neg(C),D,E).
eval__7(A,B,var(C),D) :-
  elem__13(C,A,B,D).
eval__7(A,B,conj(C,D),E) :-
  and_conj__8(E,A,B,C,D).
eval__7(A,B,disj(C,D),E) :-
  or_conj__9(E,A,B,C,D).
eval__7(A,B,not(C),D) :-
  eval__10([A|B],C,D).
and_conj__8(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,true).
and_conj__8(false,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,false).
and_conj__8(false,A,B,C,D) :-
  eval__7(A,B,C,false),
  eval__7(A,B,D,true).
and_conj__8(false,A,B,C,D) :-
  eval__7(A,B,C,false),
  eval__7(A,B,D,false).
or_conj__9(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,true).
or_conj__9(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,false).
or_conj__9(true,A,B,C,D) :-
  eval__7(A,B,C,false),
  eval__7(A,B,D,true).
or_conj__9(false,A,B,C,D) :-
  eval__7(A,B,C,false),
  eval__7(A,B,D,false).
eval__10([A|B],var(C),D) :-
  elem__13(C,A,B,neg(D)).
eval__10(A,not(B),C) :-
  eval__10(A,B,neg(C)).
and_conj__11(true,A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
and_conj__11(false,A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
and_conj__11(false,A,B,C) :-
  eval_conj__3(A,B,C,true).
and_conj__11(false,A,B,C) :-
  eval__5(A,B,false),
  eval__5(A,C,false).
or_conj__12(true,A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
or_conj__12(true,A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
or_conj__12(true,A,B,C) :-
  eval_conj__3(A,B,C,true).
or_conj__12(false,A,B,C) :-
  eval__5(A,B,false),
  eval__5(A,C,false).
elem__13(zero,A,B,A).
elem__13(succ(A),B,[C|D],E) :-
  elem__13(A,C,D,E).

/* Conjunctive fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:a Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 360 ms */
/* Unfolding time: 260 ms */
/* Post-Processing time: 360 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or_conj__2(A,B,C) :- or(D1,E1,true), eval(A,B,D1), eval(A,C,E1).
eval__3(A,B,C) :- eval(A,B,neg(C)).
eval_conj__4(A,B,C,D) :- eval(A,B,false), eval(A,C,D).
eval__5(A,B,C) :- eval(A,B,C).
eval_conj__6(A,B,C,D,E) :- eval(A,B,neg(C)), eval(A,D,E).
eval__7(A,B,C,D) :- eval([A|B],C,D).
elem__8(A,B,C,D) :- elem(A,[B|C],D).
and_conj__9(A,B,C,D,E) :- and(F1,G1,A), eval([B|C],D,F1), eval([B|C],E,G1).
or_conj__10(A,B,C,D,E) :- or(F1,G1,A), eval([B|C],D,F1), eval([B|C],E,G1).
and_conj__11(A,B,C,D) :- and(E1,F1,A), eval(B,C,E1), eval(B,D,F1).
or_conj__12(A,B,C,D) :- or(E1,F1,A), eval(B,C,E1), eval(B,D,F1).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__8(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__5(A,B,true),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or_conj__2(A,B,C).
eval__1(A,not(B)) :-
  eval__3(A,B,true).
or_conj__2(A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
or_conj__2(A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
or_conj__2(A,B,C) :-
  eval_conj__4(A,B,C,true).
eval__3([A|B],var(C),D) :-
  elem__8(C,A,B,neg(D)).
eval__3(A,not(B),C) :-
  eval__3(A,B,neg(C)).
eval_conj__4([A|B],var(C),D,E) :-
  elem__8(C,A,B,false),
  eval__5([A|B],D,E).
eval_conj__4(A,conj(B,C),D,E) :-
  and_conj__11(false,A,B,C),
  eval__5(A,D,E).
eval_conj__4(A,disj(B,C),D,E) :-
  eval_conj__4(A,B,C,false),
  eval__5(A,D,E).
eval_conj__4(A,not(B),C,D) :-
  eval_conj__6(A,B,false,C,D).
eval__5([A|B],var(C),D) :-
  elem__8(C,A,B,D).
eval__5(A,conj(B,C),D) :-
  and_conj__11(D,A,B,C).
eval__5(A,disj(B,C),D) :-
  or_conj__12(D,A,B,C).
eval__5(A,not(B),C) :-
  eval__3(A,B,C).
eval_conj__6([A|B],var(C),D,E,F) :-
  elem__8(C,A,B,neg(D)),
  eval__7(A,B,E,F).
eval_conj__6(A,not(B),C,D,E) :-
  eval_conj__6(A,B,neg(C),D,E).
eval__7(A,B,var(C),D) :-
  elem__8(C,A,B,D).
eval__7(A,B,conj(C,D),E) :-
  and_conj__9(E,A,B,C,D).
eval__7(A,B,disj(C,D),E) :-
  or_conj__10(E,A,B,C,D).
eval__7(A,B,not(C),D) :-
  eval__3([A|B],C,D).
elem__8(zero,A,B,A).
elem__8(succ(A),B,[C|D],E) :-
  elem__8(A,C,D,E).
and_conj__9(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__1([A|B],D).
and_conj__9(false,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,false).
and_conj__9(false,A,B,C,D) :-
  eval_conj__4([A|B],C,D,true).
and_conj__9(false,A,B,C,D) :-
  eval_conj__4([A|B],C,D,false).
or_conj__10(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__1([A|B],D).
or_conj__10(true,A,B,C,D) :-
  eval__7(A,B,C,true),
  eval__7(A,B,D,false).
or_conj__10(true,A,B,C,D) :-
  eval_conj__4([A|B],C,D,true).
or_conj__10(false,A,B,C,D) :-
  eval_conj__4([A|B],C,D,false).
and_conj__11(true,A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
and_conj__11(false,A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
and_conj__11(false,A,B,C) :-
  eval_conj__4(A,B,C,true).
and_conj__11(false,A,B,C) :-
  eval_conj__4(A,B,C,false).
or_conj__12(true,A,B,C) :-
  eval__5(A,B,true),
  eval__1(A,C).
or_conj__12(true,A,B,C) :-
  eval__5(A,B,true),
  eval__5(A,C,false).
or_conj__12(true,A,B,C) :-
  eval_conj__4(A,B,C,true).
or_conj__12(false,A,B,C) :-
  eval_conj__4(A,B,C,false).

/* classic */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:x Sel:x Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 120 ms */
/* Unfolding time: 120 ms */
/* Post-Processing time: 120 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval(A,B,false).
eval__3(A,B,C) :- eval(A,B,neg(C)).
elem__4(A,B,C,D) :- elem(A,[B|C],D).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__4(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__1(A,disj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__1(A,not(B)) :-
  eval__3(A,B,true).
eval__2([A|B],var(C)) :-
  elem__4(C,A,B,false).
eval__2(A,conj(B,C)) :-
  eval__1(A,B),
  eval__2(A,C).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__1(A,C).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,not(B)) :-
  eval__3(A,B,false).
eval__3([A|B],var(C),D) :-
  elem__4(C,A,B,neg(D)).
eval__3(A,not(B),C) :-
  eval__3(A,B,neg(C)).
elem__4(zero,A,B,A).
elem__4(succ(A),B,[C|D],E) :-
  elem__4(A,C,D,E).

/* Mixtus */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:x Sel:x Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 580 ms */
/* Unfolding time: 400 ms */
/* Post-Processing time: 580 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B,C) :- eval(A,B,neg(C)).
eval_conj__3(A,B,C,D) :- eval(A,B,false), eval(A,C,D).
eval_conj__4(A,B,C,D,E) :- eval(A,B,C), eval(A,D,E).
eval__5(A,B,C) :- eval(A,B,C).
eval__6(A,B) :- eval(A,B,false).
elem__7(A,B,C,D) :- elem(A,[B|C],D).
eval__8(A,B,C,D) :- eval([A|B],C,D).
eval__9(A,B,C) :- eval([A|B],C,false).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__7(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__6(A,C).
eval__1(A,disj(B,C)) :-
  eval_conj__3(A,B,C,true).
eval__1(A,not(B)) :-
  eval__2(A,B,true).
eval__2([A|B],var(C),D) :-
  elem__7(C,A,B,neg(D)).
eval__2(A,not(B),C) :-
  eval__2(A,B,neg(C)).
eval_conj__3([A|B],var(C),D,E) :-
  elem__7(C,A,B,false),
  eval__8(A,B,D,E).
eval_conj__3(A,conj(B,C),D,E) :-
  eval__1(A,B),
  eval__6(A,C),
  eval__5(A,D,E).
eval_conj__3(A,conj(B,C),D,E) :-
  eval_conj__3(A,B,C,true),
  eval__5(A,D,E).
eval_conj__3(A,conj(B,C),D,E) :-
  eval_conj__3(A,B,C,false),
  eval__5(A,D,E).
eval_conj__3(A,disj(B,C),D,E) :-
  eval_conj__3(A,B,C,false),
  eval__5(A,D,E).
eval_conj__3(A,not(B),C,D) :-
  eval_conj__4(A,B,neg(false),C,D).
eval_conj__4([A|B],var(C),D,E,F) :-
  elem__7(C,A,B,D),
  eval__8(A,B,E,F).
eval_conj__4(A,conj(B,C),true,D,E) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__5(A,D,E).
eval_conj__4(A,conj(B,C),false,D,E) :-
  eval__1(A,B),
  eval__6(A,C),
  eval__5(A,D,E).
eval_conj__4(A,conj(B,C),false,D,E) :-
  eval_conj__3(A,B,C,true),
  eval__5(A,D,E).
eval_conj__4(A,conj(B,C),false,D,E) :-
  eval_conj__3(A,B,C,false),
  eval__5(A,D,E).
eval_conj__4(A,disj(B,C),true,D,E) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__5(A,D,E).
eval_conj__4(A,disj(B,C),true,D,E) :-
  eval__1(A,B),
  eval__6(A,C),
  eval__5(A,D,E).
eval_conj__4(A,disj(B,C),true,D,E) :-
  eval_conj__3(A,B,C,true),
  eval__5(A,D,E).
eval_conj__4(A,disj(B,C),false,D,E) :-
  eval_conj__3(A,B,C,false),
  eval__5(A,D,E).
eval_conj__4(A,not(B),C,D,E) :-
  eval_conj__4(A,B,neg(C),D,E).
eval__5([A|B],var(C),D) :-
  elem__7(C,A,B,D).
eval__5(A,conj(B,C),true) :-
  eval__1(A,B),
  eval__1(A,C).
eval__5(A,conj(B,C),false) :-
  eval__1(A,B),
  eval__6(A,C).
eval__5(A,conj(B,C),false) :-
  eval_conj__3(A,B,C,true).
eval__5(A,conj(B,C),false) :-
  eval_conj__3(A,B,C,false).
eval__5(A,disj(B,C),true) :-
  eval__1(A,B),
  eval__1(A,C).
eval__5(A,disj(B,C),true) :-
  eval__1(A,B),
  eval__6(A,C).
eval__5(A,disj(B,C),true) :-
  eval_conj__3(A,B,C,true).
eval__5(A,disj(B,C),false) :-
  eval_conj__3(A,B,C,false).
eval__5(A,not(B),C) :-
  eval__2(A,B,C).
eval__6([A|B],var(C)) :-
  elem__7(C,A,B,false).
eval__6(A,conj(B,C)) :-
  eval__1(A,B),
  eval__6(A,C).
eval__6(A,conj(B,C)) :-
  eval_conj__3(A,B,C,true).
eval__6(A,conj(B,C)) :-
  eval_conj__3(A,B,C,false).
eval__6(A,disj(B,C)) :-
  eval_conj__3(A,B,C,false).
eval__6(A,not(B)) :-
  eval__2(A,B,false).
elem__7(zero,A,B,A).
elem__7(succ(A),B,[C|D],E) :-
  elem__7(A,C,D,E).
eval__8(A,B,var(C),D) :-
  elem__7(C,A,B,D).
eval__8(A,B,conj(C,D),true) :-
  eval__1([A|B],C),
  eval__1([A|B],D).
eval__8(A,B,conj(C,D),false) :-
  eval__1([A|B],C),
  eval__9(A,B,D).
eval__8(A,B,conj(C,D),false) :-
  eval_conj__3([A|B],C,D,true).
eval__8(A,B,conj(C,D),false) :-
  eval_conj__3([A|B],C,D,false).
eval__8(A,B,disj(C,D),true) :-
  eval__1([A|B],C),
  eval__1([A|B],D).
eval__8(A,B,disj(C,D),true) :-
  eval__1([A|B],C),
  eval__9(A,B,D).
eval__8(A,B,disj(C,D),true) :-
  eval_conj__3([A|B],C,D,true).
eval__8(A,B,disj(C,D),false) :-
  eval_conj__3([A|B],C,D,false).
eval__8(A,B,not(C),D) :-
  eval__2([A|B],C,D).
eval__9(A,B,var(C)) :-
  elem__7(C,A,B,false).
eval__9(A,B,conj(C,D)) :-
  eval__1([A|B],C),
  eval__9(A,B,D).
eval__9(A,B,conj(C,D)) :-
  eval_conj__3([A|B],C,D,true).
eval__9(A,B,conj(C,D)) :-
  eval_conj__3([A|B],C,D,false).
eval__9(A,B,disj(C,D)) :-
  eval_conj__3([A|B],C,D,false).
eval__9(A,B,not(C)) :-
  eval__2([A|B],C,false).

/* classic fast */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:s NgSlv:g Part:s Prun:n Sel:o Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 40 ms */
/* Unfolding time: 40 ms */
/* Post-Processing time: 40 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
or__2(A,B) :- or(A,B,true).
eval__3(A,B,C) :- eval(A,B,C).
eval__4(A,B,C) :- eval(A,B,neg(C)).
elem__5(A,B,C,D) :- elem(A,[B|C],D).
and__6(A,B,C) :- and(A,B,C).
or__7(A,B,C) :- or(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([A|B],var(C)) :-
  elem__5(C,A,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  or__2(D,E),
  eval__3(A,B,D),
  eval__3(A,C,E).
eval__1(A,not(B)) :-
  eval__4(A,B,true).
or__2(true,true).
or__2(true,false).
or__2(false,true).
eval__3([A|B],var(C),D) :-
  elem__5(C,A,B,D).
eval__3(A,conj(B,C),D) :-
  and__6(E,F,D),
  eval__3(A,B,E),
  eval__3(A,C,F).
eval__3(A,disj(B,C),D) :-
  or__7(E,F,D),
  eval__3(A,B,E),
  eval__3(A,C,F).
eval__3(A,not(B),C) :-
  eval__4(A,B,C).
eval__4([A|B],var(C),D) :-
  elem__5(C,A,B,neg(D)).
eval__4(A,not(B),C) :-
  eval__4(A,B,neg(C)).
elem__5(zero,A,B,A).
elem__5(succ(A),B,[C|D],E) :-
  elem__5(A,C,D,E).
and__6(true,true,true).
and__6(true,false,false).
and__6(false,true,false).
and__6(false,false,false).
or__7(true,true,true).
or__7(true,false,true).
or__7(false,true,true).
or__7(false,false,false).

/* minimal */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:m InstCheck:a Msv:n NgSlv:n Part:s Prun:n Sel:s Whstl:m Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 20 ms */
/* Unfolding time: 0 ms */
/* Post-Processing time: 20 ms */

/* Specialised Predicates:
eval__1(A,B,C) :- eval(A,B,C).
elem__2(A,B,C) :- elem(A,B,C).
and__3(A,B,C) :- and(A,B,C).
or__4(A,B,C) :- or(A,B,C).
*/

eval(A,B,true) :-
  eval__1(A,B,true).
eval__1(A,var(B),C) :-
  elem__2(B,A,C).
eval__1(A,conj(B,C),D) :-
  and__3(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,disj(B,C),D) :-
  or__4(E,F,D),
  eval__1(A,B,E),
  eval__1(A,C,F).
eval__1(A,not(B),C) :-
  eval__1(A,B,neg(C)).
elem__2(zero,[A|B],A).
elem__2(succ(A),[B|C],D) :-
  elem__2(A,C,D).
and__3(true,true,true).
and__3(true,false,false).
and__3(false,true,false).
and__3(false,false,false).
or__4(true,true,true).
or__4(true,false,true).
or__4(false,true,true).
or__4(false,false,false).

/* Termination */

/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:c InstCheck:v Msv:n NgSlv:g Part:s Prun:n Sel:j Whstl:h Raf:yesFar:yes Dce:yes Poly:y Dpu:no ParAbs:yes Msvp:no Rrc:no */
/* Transformation time: 180 ms */
/* Unfolding time: 80 ms */
/* Post-Processing time: 180 ms */

/* Specialised Predicates:
eval__1(A,B) :- eval(A,B,true).
eval__2(A,B) :- eval([false|A],B,true).
eval__3(A,B) :- eval(A,B,false).
eval__4(A,B,C) :- eval(A,B,neg(C)).
eval__5(A,B,C) :- eval(A,B,neg(C)).
eval__6(A,B) :- eval([true|A],B,false).
eval__7(A,B,C) :- eval([A|B],C,false).
eval__8(A,B,C) :- eval([A|B],C,true).
eval__9(A,B,C,D) :- eval([A|B],C,neg(D)).
eval__10(A,B) :- eval([true|A],B,true).
eval__11(A,B,C) :- eval([D1|A],B,neg(C)).
elem__12(A,B,C) :- elem(A,[D1|B],C).
elem__13(A,B,C) :- elem(A,B,C).
eval__14(A,B) :- eval([false|A],B,false).
*/

eval(A,B,true) :-
  eval__1(A,B).
eval__1([true|A],var(zero)).
eval__1([A|B],var(succ(C))) :-
  elem__13(C,B,true).
eval__1(A,conj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__1(A,C).
eval__1(A,disj(B,C)) :-
  eval__1(A,B),
  eval__3(A,C).
eval__1([false|A],disj(var(zero),B)) :-
  eval__2(A,B).
eval__1([A|B],disj(var(succ(C)),D)) :-
  elem__13(C,B,false),
  eval__8(A,B,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__1(A,D).
eval__1(A,disj(conj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__3(A,C),
  eval__1(A,D).
eval__1(A,disj(not(B),C)) :-
  eval__5(A,B,false),
  eval__1(A,C).
eval__1(A,not(B)) :-
  eval__4(A,B,true).
eval__2(A,var(B)) :-
  elem__12(B,A,true).
eval__2(A,conj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__2(A,C).
eval__2(A,disj(B,C)) :-
  eval__2(A,B),
  eval__14(A,C).
eval__2(A,disj(B,C)) :-
  eval__14(A,B),
  eval__2(A,C).
eval__2(A,not(B)) :-
  eval__11(A,B,true).
eval__3([false|A],var(zero)).
eval__3([A|B],var(succ(C))) :-
  elem__13(C,B,false).
eval__3([true|A],conj(var(zero),B)) :-
  eval__6(A,B).
eval__3([A|B],conj(var(succ(C)),D)) :-
  elem__13(C,B,true),
  eval__7(A,B,D).
eval__3(A,conj(conj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__1(A,B),
  eval__3(A,C),
  eval__3(A,D).
eval__3(A,conj(disj(B,C),D)) :-
  eval__3(A,B),
  eval__1(A,C),
  eval__3(A,D).
eval__3(A,conj(not(B),C)) :-
  eval__4(A,B,true),
  eval__3(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__1(A,C).
eval__3(A,conj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,disj(B,C)) :-
  eval__3(A,B),
  eval__3(A,C).
eval__3(A,not(B)) :-
  eval__5(A,B,false).
eval__4([neg(A)|B],var(zero),A).
eval__4([A|B],var(succ(C)),D) :-
  elem__13(C,B,neg(D)).
eval__4(A,not(B),C) :-
  eval__4(A,B,neg(C)).
eval__5(A,var(B),C) :-
  elem__13(B,A,neg(C)).
eval__5(A,not(B),C) :-
  eval__4(A,B,neg(C)).
eval__6(A,var(B)) :-
  elem__12(B,A,false).
eval__6(A,conj(B,C)) :-
  eval__10(A,B),
  eval__6(A,C).
eval__6(A,conj(B,C)) :-
  eval__6(A,B),
  eval__10(A,C).
eval__6(A,conj(B,C)) :-
  eval__6(A,B),
  eval__6(A,C).
eval__6(A,disj(B,C)) :-
  eval__6(A,B),
  eval__6(A,C).
eval__6(A,not(B)) :-
  eval__11(A,B,false).
eval__7(false,A,var(zero)).
eval__7(A,[false|B],var(succ(zero))).
eval__7(A,[B|C],var(succ(succ(D)))) :-
  elem__13(D,C,false).
eval__7(A,B,conj(C,D)) :-
  eval__8(A,B,C),
  eval__7(A,B,D).
eval__7(A,B,conj(C,D)) :-
  eval__7(A,B,C),
  eval__8(A,B,D).
eval__7(A,B,conj(C,D)) :-
  eval__7(A,B,C),
  eval__7(A,B,D).
eval__7(A,B,disj(C,D)) :-
  eval__7(A,B,C),
  eval__7(A,B,D).
eval__7(A,B,not(C)) :-
  eval__9(A,B,C,false).
eval__8(true,A,var(zero)).
eval__8(A,[true|B],var(succ(zero))).
eval__8(A,[B|C],var(succ(succ(D)))) :-
  elem__13(D,C,true).
eval__8(A,B,conj(C,D)) :-
  eval__8(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__8(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__8(A,B,C),
  eval__7(A,B,D).
eval__8(A,B,disj(C,D)) :-
  eval__7(A,B,C),
  eval__8(A,B,D).
eval__8(A,B,not(C)) :-
  eval__9(A,B,C,true).
eval__9(A,B,var(C),D) :-
  elem__13(C,[A|B],neg(D)).
eval__9(A,B,not(C),D) :-
  eval__9(A,B,C,neg(D)).
eval__10(A,var(B)) :-
  elem__13(B,[true|A],true).
eval__10(A,conj(B,C)) :-
  eval__10(A,B),
  eval__10(A,C).
eval__10(A,disj(B,C)) :-
  eval__10(A,B),
  eval__10(A,C).
eval__10(A,disj(B,C)) :-
  eval__10(A,B),
  eval__6(A,C).
eval__10(A,disj(B,C)) :-
  eval__6(A,B),
  eval__10(A,C).
eval__10(A,not(B)) :-
  eval__11(A,B,true).
eval__11(A,var(B),C) :-
  elem__12(B,A,neg(C)).
eval__11(A,not(B),C) :-
  eval__11(A,B,neg(C)).
elem__12(succ(A),B,C) :-
  elem__13(A,B,C).
elem__13(zero,[A|B],A).
elem__13(succ(A),[B|C],D) :-
  elem__13(A,C,D).
eval__14(A,var(B)) :-
  elem__13(B,[false|A],false).
eval__14(A,conj(B,C)) :-
  eval__2(A,B),
  eval__14(A,C).
eval__14(A,conj(B,C)) :-
  eval__14(A,B),
  eval__2(A,C).
eval__14(A,conj(B,C)) :-
  eval__14(A,B),
  eval__14(A,C).
eval__14(A,disj(B,C)) :-
  eval__14(A,B),
  eval__14(A,C).
eval__14(A,not(B)) :-
  eval__11(A,B,false).