
/* Specialised program generated by ECCE 2.0 */
/* PD Goal: A */
/* Parameters: Abs:l InstCheck:v Msv:s NgSlv:g Part:e Prun:n Sel:t Whstl:f Raf:yesFar:yes Dce:yes Poly:y Dpu:yes ParAbs:yes Msvp:no Rrc:yes */
/* Transformation time: 120 ms */
/* Unfolding time: 60 ms */
/* Post-Processing time: 120 ms */

/* Specialised Predicates: 
isPath__1(A,B) :- isPath(A,B,true).
elem_conj__2(A,B,C,D,E,F,G) :- elem(pair(A,B),cons(C,D),true), isPath(cons(B,E),cons(F,G),true).
eqPair_conj__3(A,B,C,D,E,F,G,H,I) :- eqPair(pair(A,B),pair(C,D),false), elem(pair(A,B),cons(E,F),true), isPath(cons(B,G),cons(H,I),true).
eqNat__4(A,B) :- eqNat(A,B,true).
eqNat__5(A,B) :- eqNat(A,B,false).
eqNat__6(A,B) :- eqNat(A,B,C1).
isPath__7(A,B,C,D) :- isPath(cons(A,B),cons(C,D),true).
*/

isPath(A,B,true) :- 
    isPath__1(A,B).
isPath__1(nil,A).
isPath__1(cons(A,nil),B).
isPath__1(cons(A,cons(B,C)),cons(D,E)) :- 
    elem_conj__2(A,B,D,E,C,D,E).
elem_conj__2(A,B,pair(C,D),E,F,G,H) :- 
    eqNat__4(A,C), 
    eqNat__4(B,D), 
    isPath__7(B,F,G,H).
elem_conj__2(A,B,pair(C,D),cons(E,F),G,H,I) :- 
    eqPair_conj__3(A,B,C,D,E,F,G,H,I).
eqPair_conj__3(A,B,C,D,E,F,G,H,I) :- 
    eqNat__5(A,C), 
    eqNat__6(B,D), 
    elem_conj__2(A,B,E,F,G,H,I).
eqPair_conj__3(A,B,C,D,E,F,G,H,I) :- 
    eqNat__4(A,C), 
    eqNat__5(B,D), 
    elem_conj__2(A,B,E,F,G,H,I).
eqNat__4(z,z).
eqNat__4(s(A),s(B)) :- 
    eqNat__4(A,B).
eqNat__5(s(A),z).
eqNat__5(z,s(A)).
eqNat__5(s(A),s(B)) :- 
    eqNat__5(A,B).
eqNat__6(z,z).
eqNat__6(s(A),z).
eqNat__6(z,s(A)).
eqNat__6(s(A),s(B)) :- 
    eqNat__6(A,B).
isPath__7(A,nil,B,C).
isPath__7(A,cons(B,C),D,E) :- 
    elem_conj__2(A,B,D,E,C,D,E).
